### ISSUE TITLE
API: return value for the bounds of an empty geometry?

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1023]
From https://github.com/Toblerity/Shapely/pull/983#discussion_r496530155

With current Shapely, you get an empty tuple for the bounds of an empty geometry:

```
>>> from shapely.geometry import Polygon
>>> p = Polygon()
>>> p.bounds
()
```

In PyGEOS, we return 4 NaNs, instead:

```
In [1]: import pygeos

In [2]: pygeos.bounds(pygeos.Geometry("POLYGON EMPTY"))
Out[2]: array([nan, nan, nan, nan])
```

For the vectorized ufuncs, I think this makes sense. And actually also the only possible solution, because when applying this operation on multiple points, we need to be able to put the results in a single array with consistent dimension:

```
In [3]: pygeos.bounds([pygeos.box(0, 0, 1, 1), pygeos.Geometry("POLYGON EMPTY")])
Out[3]: 
array([[ 0.,  0.,  1.,  1.],
       [nan, nan, nan, nan]])
```

So the question is then: for the scalar `.bounds` attribute on the geometry objects, do we keep the current empty tuple `()` result, or do we chagne to 4-length tuple `(nan, nan, nan, nan)` as well? 

I would personally propose to change to 4 NaNs for the scalar attribute: 1) consistency with the vectorized operation, 2) consistency in the length of the returned value (eg `p.bounds[0]` will always work)

**Comment by mwtoews** [comment]
I agree to the proposed changes for the reasons provided above. Hopefully folks are testing the `empty` attribute to evaluate emptiness of geometries rather than the length of the `bounds` attribute.

For now, we'll need to make an API changes section [in the docs](https://shapely.readthedocs.io/en/latest/project.html#changes) (done [here](https://github.com/Toblerity/Shapely/blob/shapely-2.0/CHANGES.txt)).

**Comment by tomplex** [comment]
Probably not a big deal overall, but just to add a real use case, this change breaks a common algorithm for comparing geometry bounding boxes, something I personally do often for quick intersection-ish checks when I don't need a full R-tree:

```python
from shapely.geometry import MultiPoint

def bbox_intersects(b1, b2):
    """https://gamedev.stackexchange.com/a/913"""
    return not (b2[0] > b1[2] or b2[2] < b1[0] or b2[3] < b1[1] or b2[1] > b1[3])

g1 = MultiPoint([[0, 0], [1, 1]])
g2 = MultiPoint([[0.5, 0.5], [1, 1])
g3 = MultiPoint([[3, 3], [4, 4]])
nan_bounds = [float('nan')] * 4

bbox_intersects(g1.bounds, g2.bounds)  # True
bbox_intersects(g1.bounds, g3.bounds)  # False

# Currently this would raise for an empty geometry, with nan bounds it will return True
bbox_intersects(g1.bounds, nan_bounds)
```

I guess I expect the bounds of an empty geometry to be empty, in the same way I'd expect the bounds of a dataset with no spatial component to be "empty"? Maybe I'm biased by past Shapely behavior, though.

**Comment by jorisvandenbossche** [comment]
@tomplex thanks for that example use case. I agree that silently passing this as True is a worse behaviour. 

Another option could be to simply raise an error for the scalar `.bounds` if the geometry is empty. As a user, you would still need to handle this error then (if you want to be robust for empty geometries), but basically you now also need to handle this case to watch out for len-0 tuples (and an explicit error about empty geometry not having bounds will be more informative than an "IndexError: tuple index out of range")

**Comment by jorisvandenbossche** [comment]
We discussed this last week, and were thinking to go with the tuple of length 4 (consisting of NaNs) option. That ensures consistency between the top-level vectorized method and the attribute. Opened a PR to update this -> https://github.com/shapely/shapely/pull/1416
