### ISSUE TITLE
should pyparsing be listed explicitly in requirements.txt?

### ISSUE THREAD

**Issue by suliuzh** [shapely/shapely#1027]
## Please note
As we can see, pyparsing is used as dependency in source code. But when I use "pip install Shapely", it seems pyparsing is not installed automatically. So I am wondering if pyparsing should be listed explicitly in requirements.txt?
![image](https://user-images.githubusercontent.com/27858725/98794759-5fe2b080-2444-11eb-8d54-892f3ced8196.png)

## Expected behavior and actual behavior.

pyparsing should be installed with Shapely

## Operating system
Windows

## Shapely version and provenance
latest version(Shapely-1.7.1)

**Comment by sgillies** [comment]
@suliuzh thanks for pointing this out! Rather, I think the thing to do is vendor pyparsing as well, like pip does: https://github.com/pypa/pip/blob/master/src/pip/_vendor/pyparsing.py.

Maybe in version 2.0 we'll switch entirely over to using a pyproject.toml file to describe build dependencies, or stop using packaging during the build.

**Comment by jorisvandenbossche** [comment]
Isn't pyparsing only a "setup.py" dependency, and not a runtime dependency? In that case, it in theory shouldn't be listed in requirements/`install_requires` (eg setuptools is also not listed)

(there is a `setup_requires`, but I don't know how well that works. Indeed the solution will be to use pyproject.toml, we already started to use that in pygeos so version 2.0 will be a good time to start using it)

**Comment by jorisvandenbossche** [comment]
For shapely >= 2.0, this is no longer an issue. Given there are currently no plans for further 1.8.x releases, going to close this issue.
