### ISSUE TITLE
PROPOSAL: Add densifier support

### ISSUE THREAD

**Issue by snowman2** [shapely/shapely#1037]
https://geos.osgeo.org/doxygen/classgeos_1_1geom_1_1util_1_1Densifier.html

**Comment by jorisvandenbossche** [comment]
See my answer on the PyGEOS tracker: this is currently not exposed in the GEOS C API, so not possible for Shapely to include. This first needs an enhancement on the GEOS side.

**Comment by snowman2** [comment]
Good to know. Thanks for the tip :+1:

**Comment by snowman2** [comment]
https://trac.osgeo.org/geos/ticket/1077

**Comment by jorisvandenbossche** [comment]
This is now available as the `segmentize` function in the main branch (https://github.com/pygeos/pygeos/pull/299), so closing this issue
