### ISSUE TITLE
Windows binaries missing on pypi

### ISSUE THREAD

**Issue by sk1p** [shapely/shapely#104]
The PyPi page of the current version, https://pypi.python.org/pypi/Shapely/1.3.0 does not contain windows binaries which the installation instructions talk about: "Windows users should use the executable installer, [...]"

I found [this page](http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely), is it a credible source?

**Comment by eflister** [comment]
i need shapely as a dependency for a [library](https://pypi.python.org/pypi/sima) i recently started using, so i only have a cursory idea of what shapely does.  their instructions, like your README, say to use http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely on windows, which i do.  this works fine in regular python, but i also want to interact with that library through matlab's [python bridge](http://www.mathworks.com/help/matlab/call-python-libraries.html).  when i `py.importlib.import_module('shapely')` in matlab, i get this:
```
  PyException with properties:

    ExceptionObject: [1x3 py.tuple]
         identifier: 'MATLAB:Python:PyException'
            message: 'Python Error: [Error 1114] A dynamic link library (DLL) initialization routine failed'
              cause: {}
              stack: [1x1 struct]
```
also documented [here](https://github.com/losonczylab/sima/issues/183#issuecomment-110176209)

i can import zillions of other complex libraries no problem -- numpy, scipy, mosek, picos, PIL, scikit's, future, opencv, etc -- shapely is the only error.  any idea what's causing this?  windows binaries aren't available on pypi -- would they have the same problem as chris gohlke's?

other potentially related issues:
https://github.com/Toblerity/Shapely/issues/281
https://github.com/Toblerity/Shapely/issues/43
https://github.com/Toblerity/Shapely/issues/109

the matlab access on osx works fine, btw -- after solving problems with other non-shapely-related modules (by forcing matlab to link the libtiff and libgfortran that python uses rather than the custom mods of these libs they ship just to f with you).

**Comment by eflister** [comment]
here are some more things i've tried:
in matlab:
```
>> x=py.ctypes.util.find_library('geos_c')

x =

  Python NoneType with no properties.

    None
```

but same in python!
```
>>> from ctypes.util import find_library
>>> print find_library('geos_c')
None
```
however, i can use shapely from python:
```
>>> from shapely.geometry import MultiPolygon, Polygon, Point
>>> Point()
<shapely.geometry.point.Point object at 0x000000000399F2E8>
```

in matlab:
```
>> x=py.ctypes.CDLL('C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\Lib\site-packages\shapely\DLLs\geos_c.dll')

x =

  Python CDLL with no properties.

    <CDLL 'C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\Lib\site-packages\shapely\DLLs\geos_c.dll',
handle e3f60000 at 7078b588>

>> x.GEOSversion()
No appropriate method, property, or field 'GEOSversion' for class
'py.ctypes.CDLL'.

>> x.initGEOS()
No appropriate method, property, or field 'initGEOS' for class 'py.ctypes.CDLL'.

>> x=py.ctypes.CDLL('C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\Lib\site-packages\shapely\DLLs\geos_c.dll').GEOSversion()
No appropriate method, property, or field 'GEOSversion' for class
'py.ctypes.CDLL'.

Error: Unexpected MATLAB expression.

>> x=py.ctypes.CDLL('C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\Lib\site-packages\shapely\DLLs\geos_c.dll').initGEOS()
No appropriate method, property, or field 'initGEOS' for class 'py.ctypes.CDLL'.

Error: Unexpected MATLAB expression.

>> py.dir(x)

ans =

  Python list with no properties.

    ['_FuncPtr', '__class__', '__delattr__', '__dict__', '__doc__',
'__format__', '__getattr__', '__getattribute__', '__getitem__',
'__hash__', '__init__', '__module__', '__new__', '__reduce__',
'__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__',
'__subclasshook__', '__weakref__', '_func_flags_', '_func_restype_',
'_handle', '_name']
```

in python:
```
>>> from ctypes import CDLL
>>> x=CDLL("C:\\Users\\nlab\\Downloads\\WinPython-64bit-2.7.9.5\\python-2.7.9.am
d64\\Lib\\site-packages\\shapely\\DLLs\\geos_c.dll")
>>> print x
<CDLL 'C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\Lib\si
te-packages\shapely\DLLs\geos_c.dll', handle e3f60000 at 2292cc0>
>>> x.GEOSversion()
-469489536
>>> x.initGEOS()
36606784
>>> dir(x)
['GEOSversion', '_FuncPtr', '__class__', '__delattr__', '__dict__', '__doc__', '
__format__', '__getattr__', '__getattribute__', '__getitem__', '__hash__', '__in
it__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__se
tattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_func_fla
gs_', '_func_restype_', '_handle', '_name', 'initGEOS']
```

a search for `geos_c.dll` just shows shapely's directory in my python's site-packages.

there is a `geos_c.h` header in PostgreSQL whose bin directory is on my PATH.  but no dll?

**Comment by eflister** [comment]
aha - the problem wasn't with `geos_c.dll`, but with `shapely`'s use of `msvcr`. winpython uses `msvcr90.dll`, but matlab uses `msvcr100.dll`. in `shapely`, replacing `CDLL(find_library('c'))` with `CDLL('C:\\Program Files\\MATLAB\\R2015a\\bin\\win64\\msvcr100.dll')` makes it all work.  [this answer](http://stackoverflow.com/questions/27389227/how-do-i-load-a-c-dll-from-the-sxs-in-python) seems to be a method that would determine that path automatically, appropriate for wherever you are invoking shapely from.

**Comment by snorfalorpagus** [comment]
@eflister Thanks for debugging this. Can you confirm if replacing `CDLL(find_library('c'))` with `ctypes.cdll.msvcrt` also works?

```
>>> import ctypes
>>> ctypes.cdll.msvcrt
<CDLL 'msvcrt', handle 77830000 at 403b750>
```

**Comment by eflister** [comment]
huh, that does work -- i expected it not to, aren't those supposed to be equivalent?  https://docs.python.org/2/library/ctypes.html#ctypes.util.find_library

**Comment by eflister** [comment]
python.org peeps say this solution is dangerous: http://bugs.python.org/issue24429#msg245189

afaict, shapely src says it never even uses the msvcr stuff once it finds it.  why keep this stuff at all?

**Comment by eflister** [comment]
if you want to keep it, i guess this is the officially correct way:
http://stackoverflow.com/a/30814077/1441998

**Comment by snorfalorpagus** [comment]
Shapely does use `free`, for the `WKTWriter.write` and `WKBWriter.write` methods:

https://github.com/Toblerity/Shapely/blob/3bb925a3213505255c7304c149500fb1a925d965/shapely/geos.py#L456
https://github.com/Toblerity/Shapely/blob/3bb925a3213505255c7304c149500fb1a925d965/shapely/geos.py#L253

**Comment by eflister** [comment]
reported [here](http://bugs.python.org/issue24429?@ok_message=msg%20245322%20created%0Aissue%2024429%20message_count%2C%20messages%20edited%20ok&@template=item#msg245476) that you use `GEOSfree`, as you should, but still import msvcr*'s `free` (without using it), but shouldn't.

**Comment by snorfalorpagus** [comment]
@eflister As far as I can see, `GEOSFree` and `free` are the same thing.

GEOSFree is defined here: https://github.com/Toblerity/Shapely/blob/3bb925a3213505255c7304c149500fb1a925d965/shapely/geos.py#L456
```
self.GEOSFree = self._lgeos.free
```

On Windows, free is defined in libgeos (`_lgeos` above) as so: https://github.com/Toblerity/Shapely/blob/3bb925a3213505255c7304c149500fb1a925d965/shapely/libgeos.py#L191-L197
```
    def free(m):
        try:
            cdll.msvcrt.free(m)
        except WindowsError:
            # TODO: http://web.archive.org/web/20070810024932/
            #     + http://trac.gispython.org/projects/PCL/ticket/149
            pass
```

**Comment by eflister** [comment]
@eryksun at that link reports that geos_c.dll exports a `GEOSFree` -- why don't you use that?  isn't geos_c.dll from http://trac.osgeo.org/geos/, not something built from shapely src, right?

**Comment by eflister** [comment]
here's the [comment](https://github.com/Toblerity/Shapely/blob/351c05b6e474b266a7594a775cb48cd7cfe0b833/shapely/libgeos.py#L216) claiming `free` isn't used:
```
# TODO: what to do with 'free'? It isn't used.
```

**Comment by snorfalorpagus** [comment]
Can you comment on this @mwtoews?

**Comment by mwtoews** [comment]
I'm not sure. `free` isn't used in `libgeos.py`, but it is used in `geos.py` for GEOS < 3.1.1. Pretty much everyone is using a later version (GEOS 3.1.1 was released 2009/06/15, [see diff of CAPI](https://github.com/mwtoews/GEOS_CAPI/commit/aa50111798d250e1975dd8ce8d1986559ff42978)), so everyone should be calling `GEOSFree()`.
