### ISSUE TITLE
Expand documentation for newer WK[TB] writers and output

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#105]
First, all documentation (README, manual, etc.) should reflect the trimmed output style for the newer WKT writers. These instances should be easy to spot out in the source tree, since they typically have way too many zeros.

Add details of the WKT/WKB writer output options, including their relevance for dumps. I'm not sure where this should be best documented in the manual. At present, the best source is not obvious:

``` python
from shapely import geos
help(geos.WKTWriter)
help(geos.WKBWriter)
```

The scope should cover how to modify the dumps and default writer defaults to change the WKT and WKB outputs. I'm not sure if it should cover how to make/use a custom writer:

``` python
from shapely import geos
mywriter = geos.WKTWriter(geos.lgeos, rounding_precision=4, trim=False)

from shapely.geometry import Point
p = Point(5, 3.3)
print(mywriter.write(p))  # POINT (5.0000 3.3000)
```

Thoughts?

**Comment by jorisvandenbossche** [comment]
Those writers are now available as `shapely.to_wkt`/`shapely.to_wkb`, and have documentation about their output options: https://shapely.readthedocs.io/en/latest/reference/shapely.to_wkb.html, https://shapely.readthedocs.io/en/latest/reference/shapely.to_wkt.html
