### ISSUE TITLE
Intersection precision

### ISSUE THREAD

**Issue by raul-parada** [shapely/shapely#1054]
## Expected behavior and actual behavior.

No intersection == TRUE. In those two time events the intersection even if the distance between the two objects is above 5 meters. I expect the intersection is False since 5 meters is still a far distance. However is the intersection function deciding what is true or false?

## Steps to reproduce the problem.
```python
from shapely.geometry import Polygon
for x in range (2, len(lat_225)):
    p1 = Polygon([(lat_225['message_basicContainer_reference_position_latitude'].values[x-2]/10000000, lon_225['message_basicContainer_reference_position_longitude'].values[x-2]/10000000), (lat_225['message_basicContainer_reference_position_latitude'].values[x-1]/10000000, lon_225['message_basicContainer_reference_position_longitude'].values[x-1]/10000000),(lat_225['message_basicContainer_reference_position_latitude'].values[2]/10000000, lon_225['message_basicContainer_reference_position_longitude'].values[x]/10000000)])
    p2 = Polygon([(lat_324['message_basicContainer_reference_position_latitude'].values[x-2]/10000000, lon_324['message_basicContainer_reference_position_longitude'].values[x-2]/10000000), (lat_324['message_basicContainer_reference_position_latitude'].values[x-1]/10000000, lon_324['message_basicContainer_reference_position_longitude'].values[x-1]/10000000),(lat_324['message_basicContainer_reference_position_latitude'].values[x]/10000000, lon_324['message_basicContainer_reference_position_longitude'].values[x]/10000000)])
    if (p1.intersects(p2) == True):
        print(p1.intersects(p2))
```
The data is:

User 225:
Time 1
x-2 
41.4059207
2.1740012
x-1 
41.4059084
2.1739784
x 
41.4058952
2.1739538

Time 2
x-2 
41.4059084
2.1739784
x-1 
41.4058952
2.1739538
x 
41.4058812
2.1739277

User 324:
Time 1
x-2 
41.4058153
2.1739523
x-1 
41.4058324
2.1739674
x 
41.4058499
2.173983

Time 2:
x-2 
41.4058324
2.1739674
x-1 
41.4058499
2.173983
x 
41.4058677
2.1739993

distances:
Time 1: 5.594952987961476       
Time 2: 6.157309158258348

## Operating system

Windows 10 (Jupyter Notebook)

## Shapely version and provenance

geos               conda-forge/win-64::geos-3.8.1-he025d50_0
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m
  shapely            conda-forge/win-64::shapely-1.7.1-py37h82f916b_1

**Comment by mwtoews** [comment]
Could this issue be isolated any further? I.e. provide WKT (or hex-encoded WKB) for two geometries with a small code demonstration?

**Comment by jorisvandenbossche** [comment]
@raul-parada can you provide a reproducible code example?

**Comment by jorisvandenbossche** [comment]
Given there is not enough information, going to close this (@raul-parada if you can still provide a reproducer, we can certainly re-open the issue!)
