### ISSUE TITLE
Parameter resolution in buffer method doesn't work properly

### ISSUE THREAD

**Issue by SergeyMalashenko** [shapely/shapely#1089]
## Steps to reproduce the problem.

![image](https://user-images.githubusercontent.com/13943547/107888756-68ed8d00-6f1f-11eb-859a-c0c7ea3eea3b.png)
![image](https://user-images.githubusercontent.com/13943547/107888770-87538880-6f1f-11eb-819f-a29c9fd42628.png)

**Comment by jorisvandenbossche** [comment]
@SergeyMalashenko very late reply, but this seems to work correctly now with the latest GEOS (I am using shapely 2.0 with GEOS 3.11).

With `join_style=2`:


```
from shapely.geometry import LineString
from shapely.plotting import plot_line, plot_polygon

line = LineString([(0, 0), (0, 1), (1, 1), (1, 0)])
buffer = line.buffer(0.1, cap_style=1, join_style=2, mitre_limit=2.0, quad_segs=3)

plot_line(line, color="green")
plot_polygon(buffer, color="C0")
```

![shapely_buffer1](https://user-images.githubusercontent.com/1020496/205442293-b53a21dc-bb54-4f51-bde8-9ca7d0cb424b.png)

and with `join_style=1`

```
buffer = line.buffer(0.1, cap_style=1, join_style=1, mitre_limit=2.0, quad_segs=3)

plot_line(line, color="green")
plot_polygon(buffer, color="C0")
```

![shapely_buffer2](https://user-images.githubusercontent.com/1020496/205442297-c5deb4ef-e1d4-4069-be45-13fa378e119c.png)

In both cases the caps have a limited number of segments.

**Comment by SergeyMalashenko** [comment]
thank you! :)
