### ISSUE TITLE
Support for precision models other than "float"

### ISSUE THREAD

**Issue by sgillies** [shapely/shapely#110]
Upcoming, I will require a fixed-precision mode of Shapely. It's something that's been discussed off and on, but now I have an actual need for it at work and am beginning to plan to make it happen. 

My initial idea is that Shapely will no longer hide the GEOS context (this struct: https://github.com/libgeos/libgeos/blob/svn-trunk/capi/geos_ts_c.cpp#L137) from users, but will adapt it into a Python context manager (as in Fiona and rasterio). That context manager would be where the precision model would be specified, the usage to be something like this:

```
import shapely
from shapely.geometry import Point
with shapely.context(precision='fixed', scale=1.0, offset=(0.0, 0.0)):
    # make a point snapped to a fixed-precision grid
    p = Point(0, 0)
```

Calling shapely.context() will call initGEOS (from libgeos) and instead of creating a default geometry factory (see https://github.com/libgeos/libgeos/blob/svn-trunk/capi/geos_ts_c.cpp#L209) will create a GEOS precision model and a geometry factory based upon the precision model. All geometry operations in that context will use that geometry factory and precision model. When the `with` block ends, finishGEOS (https://github.com/libgeos/libgeos/blob/svn-trunk/capi/geos_ts_c.cpp#L255) will be called and the precision model and geometry factory will be deleted.

Without a context manager, the default floating point model will be used and older code will continue to work as usual. A context manager will be required to use a fixed model. The specific syntax is yet to be determined and I welcome suggestions.

News from the GEOS project is that exposing the precision model classes via the C API might be a GSoC thing for a student. The good of this is that someone will write that code and it'll be tested and be a driver for a new GEOS release. The downside is waiting for it, and what if it takes all summer? I may develop a Shapely-specific shim using the C++ classes in the meantime and then migrate over to the new GEOS code when it's ready.

**Comment by vectorien** [comment]
+1 for a fixed precision model

**Comment by mwtoews** [comment]
Here's some ctypes hackery to explore the GEOS precision model capabilities, based on some data from #821:
```python
from shapely import geos, wkt
from ctypes import c_double, c_int, c_void_p

A = wkt.loads('POLYGON ((0 0, 0 55, 16.8 55, 14.8 43, 13 43.3, 5 0, 0 0))')
B = wkt.loads('POLYGON ((4 45, 20 45, 20 35, 4 35, 4 45))')
C = A.intersection(B)
print(C.wkt)
# POLYGON ((15.13333333333333 45, 14.8 43, 13 43.3, 11.46651270207852 35, 4 35, 4 45, 15.13333333333333 45))

# extern GEOSGeometry GEOS_DLL *GEOSGeom_setPrecision_r(
#     GEOSContextHandle_t handle, const GEOSGeometry *g, double gridSize, int flags);
geos._lgeos.GEOSGeom_setPrecision_r.argtypes = (c_void_p, c_void_p, c_double, c_int)
geos._lgeos.GEOSGeom_setPrecision_r.restype = c_void_p

# extern double GEOS_DLL GEOSGeom_getPrecision_r(
#     GEOSContextHandle_t handle, const GEOSGeometry *g)
geos._lgeos.GEOSGeom_getPrecision_r.argtypes = (c_void_p, c_void_p)
geos._lgeos.GEOSGeom_getPrecision_r.restype = c_double

ctx = geos.lgeos.geos_handle

Ap = geos._lgeos.GEOSGeom_setPrecision_r(ctx, A._geom, 0.1, 0)
Bp = geos._lgeos.GEOSGeom_setPrecision_r(ctx, B._geom, 0.1, 0)
Cp = geos.lgeos.GEOSIntersection(Ap, Bp)
print(geos._lgeos.GEOSGeom_getPrecision_r(ctx, Cp))
# 0.1
print(geos.lgeos.GEOSGeomToWKT(Cp))
# POLYGON ((15.1 45.0, 14.8 43.0, 13.0 43.3, 11.5 35.0, 4.0 35.0, 4.0 45.0, 15.1 45.0))
```
however, I'm not convinced endorsing a fixed precision model will help resolve overlay issues like #821 seeks to get:
```python
Apb = geos.lgeos.GEOSBoundary(Ap)

# using logic in question showing "wrong" output
Cp2 = geos.lgeos.GEOSIntersection(Apb, Cp)
print(geos.lgeos.GEOSGeomToWKT(Cp2))
# MULTILINESTRING ((14.8 43.0, 13.0 43.3), (13.0 43.3, 11.5 35.0))

# "correct" result, avoiding near-parallel lines
Cp3 = geos.lgeos.GEOSIntersection(Apb, Bp)
print(geos.lgeos.GEOSGeomToWKT(Cp3))
# LINESTRING (15.1 45.0, 14.8 43.0, 13.0 43.3, 11.5 35.0)
```

**Comment by mwtoews** [comment]
On the flip-side of a good example where a precision model helps, borrowing from the [LibGEOS.jl folks](https://github.com/JuliaGeo/LibGEOS.jl/pull/66):

```python
from shapely.geometry import Polygon

A = Polygon([(75.9, 30.7), (79.9, 30.7), (77.9, 28.7), (75.9, 30.7)])
B = Polygon([(81.0, 26.8), (76.0, 26.8), (81.0, 31.8), (81.0, 26.8)])

A.intersects(B)  # True
A.touches(B)  # False

Ap = geos._lgeos.GEOSGeom_setPrecision_r(ctx, A._geom, 1.0, 0)
Bp = geos._lgeos.GEOSGeom_setPrecision_r(ctx, B._geom, 1.0, 0)

bool(geos.lgeos.GEOSIntersects(Ap, Bp))  # True
bool(geos.lgeos.GEOSTouches(Ap, Bp))  # True
```

**Comment by noamgat** [comment]
This is very interesting. Has any progress been made o nthis?

**Comment by jorisvandenbossche** [comment]
Note that pygeos, which will be the basis for Shapely 2.0, already supports setting the precision as outlined above: https://pygeos.readthedocs.io/en/latest/geometry.html#pygeos.geometry.set_precision, in case you want to try it today

**Comment by jorisvandenbossche** [comment]
I think this can be closed now that we have `shapely.set_precision(..)` to convert a geometry to a certain fixed precision model (+ the `grid_size` keyword to do this on the fly in the overlay functions) ?
