### ISSUE TITLE
out of memory error creating STRtree 

### ISSUE THREAD

**Issue by bramson** [shapely/shapely#1135]
I've been creating and using STRtrees for a while now under my old installation (with GeoPandas 0.8.0 using the following code:
```
from shapely.strtree import STRtree

Geoms = list(myGeoDataFrame['geometry'])  ##  <--  This is a column of shapely point objects (in the current case)
GeomsIdx = list(myGeoDataFrame.index)
for index, geom in enumerate(Geoms):
    geom.idx = GeomsIdx[index]
geomTree = STRtree(Geoms)  ##  <-- this is where it explodes
```

## Expected behavior and actual behavior.

In the past, this produced an STRtree, which I could then use get rows (by index) of my geodataframe that intersect some geometry.  It was great!

I just updated geopandas from 0.8.0 for 0.9.0, and now that same code blows up my computer due to a series of "bad allocation" messages followed by an "Out of Memory" error.  

Since the code didn't change, and the Shapely version didn't change much, I really don't know what could be the problem.  But my only problem happens when running the code to build the Shapely STRtree, so maybe somebody here knows what is going wrong and how to fix it.  Maybe it's a compatibility issue, but like I said, that STRtree line is the only place with a problem

## Steps to reproduce the problem.

Run the code above.

## Operating system

Windows 10, miniforge Python 3.8

## Shapely version and provenance

1.7.1 installed from conda-forge (my previous build had v1.7.0)

**Comment by mwtoews** [comment]
I can confirm this bug on Windows with GEOS 3.9.1. *Don't* run the following (unless you want to risk crashing a Windows OS):
```python
from shapely.geometry import Point
from shapely.strtree import STRtree

gl = list(Point(x, x) for x in range(1000000))
gt = STRtree(gl) # <- here begins the trouble
```
results with
```
bad allocation
bad allocation
...
ERROR:shapely.geos:bad allocation
ERROR:shapely.geos:bad allocation
```
with lots of screen flickering, other apps dropping off, and sometimes a system crash. I cannot reproduce the bug with the main GEOS branch, so it appears to be fixed upstream. I'd suggest installing "GEOS<3.9", until a new GEOS version comes out.

**Comment by bramson** [comment]
After installing geos=3.8.1 everything runs smoother than butter on a bald monkey.
Thank you so much!

**Comment by mwtoews** [comment]
Upstream ticket here: https://trac.osgeo.org/geos/ticket/1118

This issue can remain open until it's (hopefully) resolved.

**Comment by mwtoews** [comment]
Shapely binary wheels are now build with GEOS 3.10, so this issue doesn't really apply anymore. Anyone affected by this bug should simply upgrade.
