### ISSUE TITLE
Future of descartes documentation dependency?

### ISSUE THREAD

**Issue by musicinmybrain** [shapely/shapely#1145]
I am one of the maintainers of the `python-shapely` package in Fedora Linux. We build the HTML documentation and make it available for installation in an RPM subpackage. Unfortunately, the `python-descartes` package in Fedora, needed for a complete build of the documentation, is in bad shape and likely to be retired because the tests fail with current Shapely, and there is no longer an upstream.

See https://pypi.org/project/descartes/, where the last release was in 2017, and the BitBucket home page has gone away with no apparent replacement.

Is there a plan to replace `descartes` in the documentation source with something that is maintained, or to fork and maintain `descartes`?

**Comment by jorisvandenbossche** [comment]
We will indeed need to update the documentation examples to no longer rely on descartes (luckily, this is quite easy, the actual replacement of descartes' functionality for shapely is basically a long one-liner, see https://github.com/geopandas/geopandas/issues/1039#issuecomment-748625852)

Relatedly, we could also publicly expose this plotting code that is being used in the examples, as I think that would be generally useful. A discussion for which I opened https://github.com/shapely/shapely/issues/1285
