### ISSUE TITLE
Function Polygon.interaction(point) modifies the raw information of point.

### ISSUE THREAD

**Issue by ChenChenGith** [shapely/shapely#1158]
## Expected behavior and actual behavior.

I want to find points that local within a box. 

Here is the box:
```
box = [[687.9957762,   812.05642543],
       [747.60233994,  818.91627661],
       [759.03542526,  719.5720037 ], 
       [699.42886151,  712.71215251]]

box_shapely = Polygon(box)
````
Here are the points:
In fact, the third column is not the true z coordinate, it is used for my own purpose.
```
data_u = DataFrame(
    [[730.649433,  647.409607,  80],
     [730.288982,  767.541422,  81],
     [732.335942,  722.819169,  82],
     [709.822688,  707.826436,  83],
     [694.760950,  755.808402,  84],
     [694.523157,  758.951426,  85],
     [722.209063,  685.462297,  86],
     [652.876367,  719.244102,  87],
     [724.841458,  807.058059,  88],
     [741.936424,  692.909820,  89],
     [727.751086,  666.824982,  90],
     [691.702492,  722.997060,  91],
     [672.091164,  727.408776,  92],
     [726.569128,  740.622060,  93],
     [709.062564,  710.613862,  94],
     [640.499349,  726.643549,  95],
     [730.649433,  647.409607,  96],
     [730.288982,  767.541422,  97],
     [732.335942,  722.819169,  98],
     [709.822688,  707.826436,  99]]
, columns=['X','Y','index'])
```
Here, data is surely out of the box: 
(please note the line whose index or z==90, its coordinates are [727.751086, 666.824982])
```
>>>  data_u[data_u['Y']<712]
	    X	             Y         index
0	730.649433	647.409607	80
3	709.822688	707.826436	83
6	722.209063	685.462297	86
9	741.936424	692.909820	89
10	727.751086	666.824982	90
14	709.062564	710.613862	94
16	730.649433	647.409607	96
19	709.822688	707.826436	99
```
Then I use `MultiPoint` function to convert them to shapely object:
```multi_p = MultiPoint(data_u[['X', 'Y', 'index']].to_numpy())```
And then use the `intersection` function to get points within the box:
```intersec = box_shapely.intersection(multi_p)```
These are the points in `intersec` :
```
>>>for i in intersec:
    print(i)
POINT Z (694.523157 758.951426 85)
POINT Z (694.76095 755.808402 84)
POINT Z (724.841458 807.058059 88)
POINT Z (726.569128 740.62206 93)
POINT Z (730.288982 767.541422 89)
POINT Z (732.335942 722.819169 90)
```
After the function intersection, some bugs occur.
Please note the line whose index, or z==90, now its coordinates are [732.3359424004473, 722.8191689921625] instead of [727.751086, 666.824982]

It very strange because the information of the point have been modified.

## Operating system

Windows 10

## Shapely version and provenance

shapely 1.7.1

**Comment by mwtoews** [comment]
Could you also show the output from:
```python
from shapely import geos
print(geos.geos_version_string)
```
I can see this is an issue with GEOS 3.8.1, but it appears to be resolved with GEOS 3.9.1.

**Comment by ChenChenGith** [comment]
> Could you also show the output from:
> 
> ```python
> from shapely import geos
> print(geos.geos_version_string)
> ```
> 
> I can see this is an issue with GEOS 3.8.1, but it appears to be resolved with GEOS 3.9.1.
```
>>>from shapely import geos
>>>print(geos.geos_version_string)
3.4.3-CAPI-1.8.3 r4285
```
How to upgrade it?

**Comment by ChenChenGith** [comment]
> Could you also show the output from:
> 
> ```python
> from shapely import geos
> print(geos.geos_version_string)
> ```
> 
> I can see this is an issue with GEOS 3.8.1, but it appears to be resolved with GEOS 3.9.1.
```
>>>from shapely import geos
>>>print(geos.geos_version_string)
3.4.3-CAPI-1.8.3 r4285
```
How to upgrade it?

**Comment by ChenChenGith** [comment]
I download "Shapely-1.7.1-cp37-cp37m-win_amd64.whl " in web "https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely". And then using `pip install Shapely-1.7.1-cp37-cp37m-win_amd64.whl` to install the shapely.

**Comment by jorisvandenbossche** [comment]
Since this has been fixed on the GEOS side, closing this.
