### ISSUE TITLE
wkt.loads crashes qgis 3.20

### ISSUE THREAD

**Issue by lmdc45** [shapely/shapely#1186]
on qgis 3.20

opening python console and write

```
from shapely import wkt
wkt.loads('POINT (0 0)')
```

result in qgis crashing. 
python version:
`sys.version
'3.8.10 (default, Jun  2 2021, 10:49:15) \n[GCC 9.4.0]'`

Due to qgis crashing I am not sure how to see the logs and investigate further the issue, would appreciate any help on this

**Comment by sgillies** [comment]
@lmdc45 I'm sorry, but there's not enough information here. Please see https://github.com/Toblerity/Shapely/blob/master/ISSUE_TEMPLATE.md.

**Comment by lmdc45** [comment]
Expected behavior and actual behavior.
wkt loads should parse the geometry, qgis should not crash. It works ok outside of qgis, issue is within qgis only

Steps to reproduce the problem.
In QGIS open python console and type
```
from shapely import wkt
wkt.loads('POINT (0 0)')
```
Then QGIS crash

Operating system
(Elementary OS 6, upstream Ubuntu focal)

Shapely version and provenance
(1.7.1 installed from PyPI using pip)

**Comment by sgillies** [comment]
I suspect that the version of GEOS in the 1.7.1 binary distribution is not compatible with the version of GEOS that QGIS links. This is not a shapely issue, it is a system configuration issue.
