### ISSUE TITLE
Post 1.8 tasks

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#1204]
Now that #1066 is closed, here are a few follow-up tasks:

- [x] Create `maint-1.8` maintenance branch, i.e. this is the last release series with ctypes support, which sometimes require patching
- [x] Review items for the [1.8 milestone](https://github.com/Toblerity/Shapely/milestone/37) and either close or move forward, depending on what makes sense
- [x] Move `master` -> `main` -- this is as good enough of a time as any; see #1148 for a bit of discussion
- [x] Consider moving repo from https://github.com/Toblerity/Shapely to https://github.com/shapely/shapely as vaguely discussed in #819. I'm neutral on this task, but it should be discussed more thoroughly before.
- [x] Add `maint-1.8` version to https://readthedocs.org/projects/shapely/

After these have been cleared, there is plenty of work ahead with #962 and beyond.

Comments before action on any of these tasks is welcome here.

**Comment by sgillies** [comment]
Done! Thank you @jorisvandenbossche .

**Comment by jorisvandenbossche** [comment]
> yes, the repo transfer is just a click, it's all the follow up that is time consuming

@sgillies for the repo transfer: I am now an owner of the github.com/shapely org so I can help with the follow-up tasks after the transfer, but you will still have to click the button for doing the actual transfer (I am not an owner of Toblerity/Shapely, so can't do that)

**Comment by jorisvandenbossche** [comment]
@sgillies small reminder for this (moving the repo)

**Comment by sgillies** [comment]
@jorisvandenbossche thanks for the reminder! Here we go: https://github.com/shapely/shapely.

**Comment by jorisvandenbossche** [comment]
Cool, thanks a lot!

**Comment by hobu** [comment]
What was the reason to move away from the Toblerity org? If it is broken, confusing, or just not functional, we should disband it generally I guess.

**Comment by sgillies** [comment]
@hobu yeah, we're moving away from what are largely mature or defunct projects. It should increase visibility a bit and will be useful in the context of PyPI's upcoming organization accounts.

**Comment by hobu** [comment]
Ok. Rtree and Fiona are not defunct, so we'll need to move them.

**Comment by hobu** [comment]
Actually, can we put Rtree under the Shapely org then? github.com/rtree is taken and I am already the owner of 13+ github orgs.

**Comment by jorisvandenbossche** [comment]
I am not familiar with the history around "Toblerity", so for me it made sense to have shapely in its own org when it was proposed at https://github.com/shapely/shapely/pull/819#issuecomment-575915125

---

Regarding follow-up tasks:

- I did a search replace within the repo -> https://github.com/shapely/shapely/pull/1255
- I updated the readthedocs settings (the build is still failing though, but that's because we need to update the installation config in readthedocs.yml, will take a look at that)

**Comment by hobu** [comment]
> I am not familiar with the history around "Toblerity", 

It was just an organization name so we didn't have to create individual organizations for each project. It was a nod to Tobler's First Law of Geography, where close things are more related to each other. In the before times, these projects were related to each other through `__geo_interface__` and the fact that @sgillies and others were maintaining them. There's no special attachment to it.

**Comment by mwtoews** [comment]
Looks like all tasks here are done!
