### ISSUE TITLE
Issues installing shapely 1.8.0 on windows python 3.10 (amd64)

### ISSUE THREAD

**Issue by einarf** [shapely/shapely#1215]
Python version info
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
```
```
(.venv) >python -m pip install shapely==1.8.0
Collecting shapely==1.8.0
  Using cached Shapely-1.8.0.tar.gz (278 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\efors\projects\moderngl\arcade\.venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\efors\\AppData\\Local\\Temp\\pip-install-nqph4na2\\shapely_2cd47a889668493cbf278e62dc6463e8\\setup.py'"'"'; __file__='"'"'C:\\Users\\efors\\AppData\\Local\\Temp\\pip-install-nqph4na2\\shapely_2cd47a889668493cbf278e62dc6463e8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\efors\AppData\Local\Temp\pip-pip-egg-info-rww_624n'
         cwd: C:\Users\efors\AppData\Local\Temp\pip-install-nqph4na2\shapely_2cd47a889668493cbf278e62dc6463e8\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\efors\AppData\Local\Temp\pip-install-nqph4na2\shapely_2cd47a889668493cbf278e62dc6463e8\setup.py", line 74, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\efors\AppData\Local\Temp\pip-install-nqph4na2\shapely_2cd47a889668493cbf278e62dc6463e8\shapely\_buildcfg.py", line 204, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\efors\.pyenv\pyenv-win\versions\3.10.0\lib\ctypes\__init__.py", line 374, in __init__
        self._handle = _dlopen(self._name, mode)
    FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1c/0c/454c80f71bd5ece52fb06d2905bf956b9122f4be539d5ae5df4b10dd3e14/Shapely-1.8.0.tar.gz#sha256=f5307ee14ba4199f8bbcf6532ca33064661c1433960c432c84f0daa73b47ef9c (from https://pypi.org/simple/shapely/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement shapely==1.8.0 (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0, 1.7.1, 1.8a1, 1.8a2, 1.8a3, 1.8rc1, 1.8rc2, 1.8.0)
ERROR: No matching distribution found for shapely==1.8.0
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\efors\projects\moderngl\arcade\.venv\Scripts\python.exe -m pip install --upgrade pip' command.
```

Just doing a `pip install shapely` on python 3.10 for some reason ends up installing version 1.5.9 after pip manually attempts to install older versions down the version list
```
  Using cached Shapely-1.5.9.tar.gz (165 kB)
Using legacy 'setup.py install' for shapely, since package 'wheel' is not installed.
Installing collected packages: shapely
    Running setup.py install for shapely ... done
Successfully installed shapely-1.5.9
```

Installing shapely 1.8.0 on python 3.9 works out of the box, so there's something werid going on here?

**Comment by einarf** [comment]
I just noticed that 3.10 wheels are missing for windows : https://pypi.org/project/Shapely/1.8.0/#files

I was sure I saw them initially, my bad. This might be a duplicate of another issue.

**Comment by dfremont** [comment]
There is no 3.10 wheel for macOS either, leading to a similar problem as above. I can't find anything in the repo about plans for making such a wheel; should I make a new issue, or is it already in the pipeline?

**Comment by pvcraven** [comment]
Any update on when this Python 3.10 support might happen?

**Comment by MathiasSven** [comment]
Is there any workaround in the meanwhile? Also trying to install Shapely on 3.10 Win64

**Comment by Ghostkeeper** [comment]
For those in the same situation as me, here's a few workarounds around this situation I've tried:

* You could download pre-built binaries for Windows from a third party: https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely However this is no solution for MacOS, and it also involves downloading binaries from a possibly untrusted source (although Gohlke's builds are quite widely used).
* You can compile this yourself with the wheel. This requires [libgeos](https://libgeos.org/), which has to be compiled separately. I couldn't get this to work myself because I couldn't get Shapely to find Geos in a different path than the default library paths (Cura's build system builds its dependencies in a separate folder for each branch). However if you have Geos installed in a path where Python can find it, simply installing Shapely with Pip should not give the error message in the OP: `Could not find module 'geos_c.dll'` because `geos_c.dll` is found then.
* You could try an alternative library such as [pyclipper](https://pypi.org/project/pyclipper/) that does something similar.

**Comment by pvcraven** [comment]
Is this set to go into the next release? It isn't released yet, right?

**Comment by jorisvandenbossche** [comment]
@pvcraven we are currentlyworking on a new release, see https://github.com/shapely/shapely/issues/1290#issuecomment-1041865722. If you would be able to test the new wheels (see the linked comment) and check if they solve the issue, that would be very welcome!
