### ISSUE TITLE
Decide on the repr of the geometry objects

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1248]
I currently skipped the repr tests in https://github.com/Toblerity/Shapely/pull/1241 because they are still failing. 

As an overview, what we have been doing in the past / in the different packages (using a simple Point as example):

- Shapely 1.8 and before: `<shapely.geometry.point.Point at 0x7fae395b7e50>` 
  - This is the default repr inherited from python
- Shapely shapely-2.0 branch: `<shapely.geometry.Point POINT (1 1)>`
  - I changed this in https://github.com/Toblerity/Shapely/pull/983, but wasn't really discussed at the time (and a simple python `__repr__()` using `self.wkt`)
- PyGEOS: `<pygeos.Geometry POINT (1 1)>`
  - This is implemented in C (`GeometryObject_repr`). This also deals with 1) failure in WKT writer, and 2) limiting total length to 80 characters (both could also be done in python of course)

I think the questions to answer are (with the second and third question depending on answering yes on the first:

1) Do we want to include a WKT (preview) or coordinates in the repr?
2) Which class name to show?
3) Implement in C or Python?

----

**1) Do we want to include a WKT (preview) or coordinates in the repr?**

There have been several issues/PRs in the past asking about adding a `repr` (https://github.com/Toblerity/Shapely/issues/718, https://github.com/Toblerity/Shapely/pull/478), but until now there was never added one in Shapely. Some arguments back then were about how to deal with many coordinates (which can easily fill the screen), about ambiguity (if only showing something like `"Point(1, 1)"`), about the "repr-eval" use case / round-trippability (eg doing `"shapely.geometry.Point(1, 1)"` works, but this easily gets complicated  for other geometry types / large geometries)

I personally like the choice me made in PyGEOS for having a *truncated WKT* within a `<pygeos. ...>`:

- It is not "just" a WKT representation (in which case `repr` would be equivalent to `str`, which we don't want I think), by still including the WKT in a `<shapely... >` context.
- Especially when working with arrays of geometries, it is IMO really important to limit the length of the repr (it's annoying to flood your console output when inspecting data), but at the same time it is also very valuable to see some preview of the data (a single object you can also print to get str instead of repr, but for an array this is also less convenient)
- We could also make a more Python-code like repr instead of using WKT (so like `shapely.geometry.LineString([(1, 1), (2, 3)])`), but 1) this is more complex to write (and for more more complex geometry will also get more harder to interpret I think), and 2) it will never be guaranteed to be "eval"-able if we limit the length of the repr. So for those reasons, I would personally not put the effort in writing custom code for this, but just go with truncated WKT (but it would certainly be possible if preferred).

**2) Which class name to show?**

One drawback of using WKT with the full subclass name as I now did in the main branch (eg  `<shapely.geometry.Point POINT (1 1)>`) is that you get a repetition in the class name and geometry type in the WKT. But on the other hand, I think it would be better to use the full subclass name (`shapely.geometry.Point`) instead of the base class (`shapely.Geometry`), since it's the subclass that users actually interact with.

**3) Implement in C or Python?**

A technical point, but I suppose it's actually easier to just do this in Python instead of the current C function (in PyGEOS it was only possible to do this in C, but now with the Python subclasses we can also do it there) 

@sgillies @snorfalorpagus @snorfalorpagus @caspervdw @brendan-ward

**Comment by caspervdw** [comment]
For me the truncated WKT approach works best, so I'd like to stick with that. The WKT is designed as a string representation of a geometry- precisely what we need here.

Concerning the implementation: when starting from scratch I would opt for a Python implementation in some base class, but as we already have a working implementation in C I'd say; lets go with that. We could do `super().__repr__().replace("pygeos.Geometry", "<something else>")` to modify the base implementation.

**Comment by jorisvandenbossche** [comment]
I opened a PR for this, following Casper's super()+replace suggestion -> https://github.com/shapely/shapely/pull/1302
