### ISSUE TITLE
Offsetting a LineString produces a MultiLineString

### ISSUE THREAD

**Issue by jiawlu** [shapely/shapely#1252]
## Issue

Shapely produces a `MultiLineString` when offsetting a `LineString`.

## Steps to reproduce the problem.

from shapely import geometry

```
line = geometry.LineString([[498117.696, 4520099.122], [498152.948, 4520099.213], [498163.454, 4520099.233], [498178.740, 4520099.274], [498204.844, 4520099.345]])
line_offset = line.parallel_offset(distance=3.5, side='right', join_style=2)
print(line_offset.wkt)
```

## Operating system

Windows 7

## Shapely version and provenance

1.7.1 installed from PyPI using pip

**Comment by jiawlu** [comment]
It seems it is a known issue as user's guide mentions it.

**Comment by sgillies** [comment]
Generally speaking, geometry operations don't preserve type.
