### ISSUE TITLE
Is it possible to prevent nearby line segments from affecting "parallel_offset" results?

### ISSUE THREAD

**Issue by 0todd0000** [shapely/shapely#1256]
In the example below I'm using `offset = 0.5` in `parallel_offset` for sine curves. This `offset` is working as I expect for a low-frequency sine wave (left panel), but not as I was expecting for a higher frequency sine wave (right panel). For higher frequency data the offset looks correct for only the local extrema; the offset is much smaller than expected for the rising and falling portions of the sine wave.

Is there a way to achieve an offset closer to the expected `0.5` for high frequency sine waves, like those in the right panel below?

```python
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString


n  = 100
x0 = np.linspace(0, 2*np.pi, n)
x1 = np.linspace(0, 10*np.pi, n)


plt.close('all')
_,axs  = plt.subplots(1, 2, figsize=(8,3), tight_layout=True)
offset = 0.5
for ax,x in zip(axs, [x0,x1]):
    y     = np.sin(x)
    line  = LineString( np.vstack( [x, y] ).T )
    off   = line.parallel_offset(offset, join_style=2, mitre_limit=1)
    ax.plot(x, y, color='k', linewidth=3)
    ax.plot(off.xy[0], off.xy[1], color='r', linewidth=1)
plt.show()
```

![fig](https://user-images.githubusercontent.com/4276626/145706485-5c448966-ed1d-4b99-b952-158d6af9776a.png)

**Comment by jorisvandenbossche** [comment]
I am not familiar with the exact logic for a case like this, but so `line.buffer(offset)` does the same. There are some examples at https://shapely.readthedocs.io/en/latest/manual.html#object.buffer and https://postgis.net/docs/ST_Buffer.html, but those mostly deal with sharp corners.

> For higher frequency data the offset looks correct for only the local extrema

It might be you didn't actually create higher frequency data? With `x1 = np.linspace(0, 10*np.pi, n)`, you only increased the "stop" value, and thus creating a larger range but with the same frequency? (if you zoom in on the right figure to also only include 0-6 x-axis range, it looks very similar as the left figure)

**Comment by jorisvandenbossche** [comment]
Doing something like this:

```
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString

n  = 1000
x = np.linspace(0, 10, n)

plt.close('all')
_,axs  = plt.subplots(1, 2, figsize=(8,3), tight_layout=True)
offset = 0.5
for ax, freq in zip(axs, [0.1, 0.5]):
    y     = np.sin(freq * 2 * np.pi *x)
    line  = LineString( np.vstack( [x, y] ).T )
    off   = line.parallel_offset(offset, join_style=2, mitre_limit=1)
    ax.plot(x, y, color='k', linewidth=3)
    ax.plot(off.xy[0], off.xy[1], color='r', linewidth=1)
plt.show()
```

gives:

![Figure_1](https://user-images.githubusercontent.com/1020496/147605196-4c9ea1fc-7a57-45dd-a563-399e33ae06aa.png)

**Comment by 0todd0000** [comment]
Thanks very much for your reply!

I wonder if this is purely a visual problem, based on the axes [aspect](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_aspect.html)?  The aspects of your two subplots are identical, so the offsets look identical. The aspects of my two subplots are different, so the offsets look different. Is this possible?

If this is truly just a visual problem, then the only way to solve it would be to modify Matplotlib's default display transform...

**Comment by jorisvandenbossche** [comment]
> I wonder if this is purely a visual problem, based on the axes aspect? The aspects of your two subplots are identical, so the offsets look identical. The aspects of my two subplots are different, so the offsets look different. Is this possible?

Yes, it's indeed a visual problem. Your plot has an x-axis with a range of 0 to 30, so the data is much more compressed in the x-direction compared to the y-direction (and compared to the left plot). But this is caused by what I tried to mention: you didn't create higher frequency data, but AFAIU you rather created _more_ data (larger x range) and then visually compressed it to the same figure size.

You can set an equal aspect with matplotlib, but then you will get a _very_ wide figure

**Comment by 0todd0000** [comment]
OK, thanks very much for your help!
