### ISSUE TITLE
[Potentially] unexpected behaviour when subtracting points

### ISSUE THREAD

**Issue by JohnDemand** [shapely/shapely#1269]
I subtracted point `p1 = Point(0, -15)` point from point `p2 = Point(1, -6)` and got a point `p_res = Point(1, -9)` which didn't meet my expectations.
I expected to get `p_exp = Point(1, 9)`, similar to subtracting arrays: -6 -(-15) = 9. 

Is this the normal behaviour?

```
from shapely.geometry import Point
p1 = Point(0, -15)
p2 = Point(1, -6)

p_res = p2 - p1  # POINT (1 -9)
p_exp = Point(1, 9)
```

**Comment by sgillies** [comment]
@JohnDemand your expectation doesn't match the code. Geometry `__sub__` is an alias for point set difference (see https://github.com/shapely/shapely/blob/maint-1.8/shapely/geometry/base.py#L272-L273). This was introduced in https://github.com/shapely/shapely/pull/62. On my computer (Shapely 1.8.0) I observe

```
>>> (Point(1, -6) - Point(0, -15)).wkt
'POINT (1 -6)'
```
