### ISSUE TITLE
C extension could not be compiled on python3.9 for 1.8.0

### ISSUE THREAD

**Issue by akursar** [shapely/shapely#1288]
## Expected behavior and actual behavior.

I have no problem building C extensions on a src install on python3.8. However, there is a failure for python3.9 with this message.

`shapely/speedups/_speedups.c:9568:77: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’`

I have no problem using the binary wheels but want to use my own geos to build to use same version with pygeos and avoid performance penalties when pygeos/shapely are using different geos.

Sorry if this is a duplicate/known issue. I found https://github.com/shapely/shapely/issues/1263 but that does not specifically call out the `tp_print` error (which looks like root cause for me i think ) and isn't trying to explicitly build the extension from src install.

## Steps to reproduce the problem.

This works (prints True):

`docker run --rm python:3.8 /bin/sh -c 'apt-get update && apt-get install -y libgeos-dev && pip install shapely --no-binary shapely -v --no-deps && python -c "from shapely import speedups; print(speedups.available)"'`

but this does not (prints False, includes err message, only diff is python image version):

`docker run --rm python:3.9 /bin/sh -c 'apt-get update && apt-get install -y libgeos-dev && pip install shapely --no-binary shapely -v --no-deps && python -c "from shapely import speedups; print(speedups.available)"'`

## Operating system

docker latest python3.8 / python3.9 images (amd64)

## Shapely version and provenance

1.8.0

**Comment by sgillies** [comment]
This will be fixed in 1.8.1.
