### ISSUE TITLE
RLS: Shapely 1.8.1 release

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1290]
We have a few but relevant fixes in the maint-1.8 branch:

* #1264
* #1224
* #1235

For which it might be worth doing a 1.8.1 release? (@mwtoews @sgillies)

Especially the cython update + removal of .c files is important to have shapely installable from source on newer pythons.

**Comment by mwtoews** [comment]
Yes, a new release is due. It's a blocker for downstream projects that want to use Python 3.10.

Also, the binary wheels should be upgraded from GEOS 3.9.1 to [3.9.2](https://github.com/libgeos/geos/blob/3.9.2/NEWS).

**Comment by jorisvandenbossche** [comment]
Do we want to go to GEOS 3.10.2, or this that a too big of a change for a minor bug fix release?

**Comment by mwtoews** [comment]
There was a bit of discussion [here](https://github.com/shapely/shapely/issues/1066#issuecomment-945189292), and it seems that @sgillies was keen to bump to GEOS 3.10.x for shapely 1.8.1. If this is the case, [GEOS 3.10.2](https://lists.osgeo.org/pipermail/geos-devel/2022-January/010631.html) can be expected in a few days. I'm fine with the latest patch on either GEOS version.

**Comment by sgillies** [comment]
I'm going to pick this one up now while my wheel-building hat is still on my head. I will try backporting the release workflow from the master branch.

**Comment by sgillies** [comment]
Progress: manylinux2010 python 3.6-3.10 wheels for the two linux platforms at https://github.com/shapely/shapely/actions/runs/1813575690#artifacts.

**Comment by sgillies** [comment]
Stumped on macos arm64 wheels right now. Having no such computer it is hard to debug.

Moving on to windows, based on work in https://github.com/shapely/shapely-wheels/blob/master/appveyor.yml.

**Comment by jwhitlock** [comment]
I was able to build the MacOS arm64 wheels on my laptop, an M1 running Monterey (12.2). I tried both with GEOS installed with Homebrew and with `ci/install_geos.sh`. Other than that, I didn't try _too_ hard to emulate the CI environment (macOS 10.15, `cibuildwheel`).

The [Homebrew formula for geos](https://github.com/Homebrew/homebrew-core/blob/master/Formula/geos.rb) lists arm64 builds for Monterey (12) and Big Sur (11). It lists Catalina (10.15), but no arm64 variant. Is it possible that you have to target 11.0 minimum for arm64 builds?

Anything I can do to help debug?

**Comment by abey79** [comment]
@jwhitlock I believe M1 systems were first released with Big Sur and are not compatible with previous macOS version. This is why you won't see arm64 build for Catalina and earlier.

FWIW, I don't have any experience with CI packaging but I'm happy to run tests on my M1 laptop of this helps.

**Comment by sgillies** [comment]
@abey79 @jwhitlock I appreciate the offers to test and will take you up on it. GitHub Actions doesn't offer access to M1 runnners, so we're building arm64 binaries on x86_64 machines. My problems are all about cross-compilation.

**Comment by sgillies** [comment]
Now, I think I've overcome the cross-compilation issues (thanks to pygeos trail-blazing). The current sticking point is that shapely 1.8.x tries to load the GEOS lib to get some information (see https://github.com/shapely/shapely/blob/maint-1.8/setup.py#L74-L75) but macos dlopen() will not (with good reason) load an arm64 lib into an x86_64 process. So, shapely's setup will need to be rewritten.

**Comment by sgillies** [comment]
@abey79 @jwhitlock if you could download the zip file from https://github.com/shapely/shapely/suites/5320005471/artifacts/165628589 and install one of the macosx_arm64 wheels, I would love to hear what you find.

**Comment by abey79** [comment]
I pip-installed `Shapely-1.8.1.dev0-cp39-cp39-macosx_11_0_arm64.whl` in a clean venv, together with my project without any problem. I'm running macOS 12.2, but this didn't seem to offend pip.

I then ran a cursory test by running my project (I guess this is far from an extensive test but I did make sure to run something that *actually* uses Shapely). Everything appeared to work without issue, with the following output:

```
Formed path for globbing: dylib_path='/private/tmp/venv/lib/python3.9/site-packages/shapely/.dylibs/*.dylib'
Contents of .dylibs: ['libgeos.3.10.2.dylib', 'libgeos_c.1.16.0.dylib']
Contents of __file__ parent: ['predicates.py', 'speedups', 'strtree.py', 'coords.py', 'linref.py', 'prepared.py', 'algorithms', 'affinity.py', '__init__.py', 'ctypes_declarations.py', '__pycache__', '.dylibs', 'ops.py', 'geos.py', 'iterops.py', 'examples', 'wkt.py', 'topology.py', 'vectorized', 'impl.py', 'errors.py', 'geometry', 'wkb.py', '_buildcfg.py', '_geos.pxi', 'validation.py']
Globbed: geos_whl_dylib=['/private/tmp/venv/lib/python3.9/site-packages/shapely/.dylibs/libgeos.3.10.2.dylib', '/private/tmp/venv/lib/python3.9/site-packages/shapely/.dylibs/libgeos_c.1.16.0.dylib']
```

FWIW, I'm running a MacPorts python 3.9 install and I do have the MacPorts version of arm64 libgeos in `/opt/local/lib`. I haven't tried to remove it and test, but from the output above it seems that it isn't involved.

I then uninstalled Shapely and reinstalled it from `Shapely-1.8.1.dev0-cp39-cp39-macosx_10_9_universal2.whl`. Same result.

It's getting late now but I can run more tests tomorrow if useful (e.g. with other Python versions than 3.9) -- let me know.

**Comment by jwhitlock** [comment]
I unzipped to `tmp` subfolder and ran:

```shell
> pip install tmp/Shapely-1.8.1.dev0-cp39-cp39-macosx_11_0_arm64.whl
Processing ./tmp/Shapely-1.8.1.dev0-cp39-cp39-macosx_11_0_arm64.whl
Installing collected packages: Shapely
Successfully installed Shapely-1.8.1.dev0
```

and then:

```shell
> python
Python 3.9.10 (main, Jan 15 2022, 11:40:53) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely import speedups
Formed path for globbing: dylib_path='/Users/john/.virtualenvs/ichnaea/lib/python3.9/site-packages/shapely/.dylibs/*.dylib'
Contents of .dylibs: ['libgeos.3.10.2.dylib', 'libgeos_c.1.16.0.dylib']
Contents of __file__ parent: ['predicates.py', 'speedups', 'strtree.py', 'coords.py', 'linref.py', 'prepared.py', 'algorithms', 'affinity.py', '__init__.py', 'ctypes_declarations.py', '__pycache__', '.dylibs', 'ops.py', 'geos.py', 'iterops.py', 'examples', 'wkt.py', 'topology.py', 'vectorized', 'impl.py', 'errors.py', 'geometry', 'wkb.py', '_buildcfg.py', '_geos.pxi', 'validation.py']
Globbed: geos_whl_dylib=['/Users/john/.virtualenvs/ichnaea/lib/python3.9/site-packages/shapely/.dylibs/libgeos.3.10.2.dylib', '/Users/john/.virtualenvs/ichnaea/lib/python3.9/site-packages/shapely/.dylibs/libgeos_c.1.16.0.dylib']
>>> speedups.available
True
```

Success 🎉 , with maybe some extra logging

**Comment by sgillies** [comment]
Yes, I added some extra logging to make sure I wasn't losing my mind :smile:

Thanks for testing! I'm excited about this :champagne:

**Comment by jwhitlock** [comment]
And the Python 3.10 version:

```
> pip install tmp/Shapely-1.8.1.dev0-cp310-cp310-macosx_11_0_arm64.whl 
Processing ./tmp/Shapely-1.8.1.dev0-cp310-cp310-macosx_11_0_arm64.whl
Installing collected packages: Shapely
  Attempting uninstall: Shapely
    Found existing installation: Shapely 1.8.0
    Uninstalling Shapely-1.8.0:
      Successfully uninstalled Shapely-1.8.0
Successfully installed Shapely-1.8.1.dev0
[I] john@johnwhitlock-4zq05n ~/s/ichnaea (main)> python
Python 3.10.2 (main, Feb 15 2022, 20:07:53) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely import speedups
Formed path for globbing: dylib_path='/Users/john/.virtualenvs/ichnaea/lib/python3.10/site-packages/shapely/.dylibs/*.dylib'
Contents of .dylibs: ['libgeos.3.10.2.dylib', 'libgeos_c.1.16.0.dylib']
Contents of __file__ parent: ['predicates.py', 'speedups', 'strtree.py', 'coords.py', 'linref.py', 'prepared.py', 'algorithms', 'affinity.py', '__init__.py', 'ctypes_declarations.py', '__pycache__', '.dylibs', 'ops.py', 'geos.py', 'iterops.py', 'examples', 'wkt.py', 'topology.py', 'vectorized', 'impl.py', 'errors.py', 'geometry', 'wkb.py', '_buildcfg.py', '_geos.pxi', 'validation.py']
Globbed: geos_whl_dylib=['/Users/john/.virtualenvs/ichnaea/lib/python3.10/site-packages/shapely/.dylibs/libgeos.3.10.2.dylib', '/Users/john/.virtualenvs/ichnaea/lib/python3.10/site-packages/shapely/.dylibs/libgeos_c.1.16.0.dylib']
>>> print(speedups.enabled)
True
```

**Comment by sgillies** [comment]
And now here's a zip file with windows wheels: https://github.com/shapely/shapely/suites/5332405931/artifacts/166364965. Anyone on Windows watching this issue?

**Comment by sgillies** [comment]
I'm going to tag 1.8.1 and build wheels. To be uploaded later this afternoon.

**Comment by sgillies** [comment]
Et voilà: https://pypi.org/project/Shapely/1.8.1/#files. The libraries in the manylinux wheels are bigger than I expected, but we will let that slide for now.

**Comment by jorisvandenbossche** [comment]
Thanks for the release work!

> The libraries in the manylinux wheels are bigger than I expected, but we will let that slide for now.

It seems that the libgeos library (in `Shapely.libs` in the wheel) is considerably larger compared to the wheels for 1.8.0 (2.5 MB then vs 3.9 MB now). 
We did do a GEOS update (GEOS 3.9 for the 1.8.0 wheels vs GEOS 3.10 for the new wheels), so that might affect this? But maybe it's also the exact way we build the GEOS library (compared to how it was done on shapely-wheels)? (some compiler flag)

Something else, on conda-forge(https://github.com/conda-forge/shapely-feedstock/pull/96), we see failures on Windows for the new release. It fails when testing the built package, with:

```
Traceback (most recent call last):
  File "D:\bld\shapely_1645066746853\test_tmp\run_test.py", line 21, in <module>
    import shapely.speedups._speedups
ModuleNotFoundError: No module named 'shapely.speedups._speedups'
```

I seem to recall we ran into the same issue before.

**Comment by jorisvandenbossche** [comment]
I also noticed that in the sdist, the cythonized `_speedups.c` is included, but not the cythonized `_vectorized.c`. I suppose that difference was not intentional? (which relates to the discussion in https://github.com/shapely/shapely/pull/1264 as well)

**Comment by mwtoews** [comment]
I've looked at the contents of 1.8.0 and 1.8.1 on x86_64-linux, and the difference is that all compiled objects for 1.8.0 are all "stripped" (thus compact), while 1.8.1 are either "not stripped" or "with debug_info, not stripped". So it seems something to do with flags, somehow.

**Comment by jorisvandenbossche** [comment]
We are now using the build script included in the repo to build the GEOS that gets included in the wheels, and that seems to specify a release build:

https://github.com/shapely/shapely/blob/3078195d1bfd10f69d89d038411b72d41567e1ac/ci/install_geos.sh#L44

But in the shapely-wheels repo, the `build_geos` function includes an `-O2` flag:

https://github.com/shapely/shapely-wheels/blob/ea124b7bf026f149f335fa7249b602e7edb2e1e6/config.sh#L51-L55

**Comment by mwtoews** [comment]
Typically, `-DCMAKE_BUILD_TYPE=Release` sets CXXFLAGS to something like `-O3 -DNDEBUG -fPIC ...`

**Comment by jorisvandenbossche** [comment]
`Release` is the default build anyway, but I don't directly see any flags like O3 set in the GEOS cmake config (unless that is something that is done by cmake itself): https://github.com/libgeos/geos/blob/main/CMakeLists.txt (`NDEBUG` is specified though)

Given that @dbaston added that flag explicitly to the conda-forge recipe, that might mean that we indeed need to specify it manually.

**Comment by dbaston** [comment]
At one point GEOS did not default to a `Release` build type, so I added it to a conda recipe. It should no longer be necessary, though it never hurts to be clear. It shouldn't be necessary to set any other flags.

**Comment by jorisvandenbossche** [comment]
Ah, yes, when the conda recipe was convert to use cmake (https://github.com/conda-forge/geos-feedstock/pull/61/), the extra flags were removed. So the conda recipe is also not setting any other flags now.

**Comment by abey79** [comment]
Just to let you know, I'm having issue with 1.8.1.pre1 on PyInstaller running on Windows GH runner (#1326). I don't understand yet the exact cause, but I'm taking this as an indication that there might still be some issue with the Windows build.
