### ISSUE TITLE
Feature: concave hulls

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#1296]
The GEOS C API main branch has a new feature [`GEOSConcaveHull`](https://github.com/libgeos/geos/blob/70d2111bd66ea848809e5738896256199d9a7cba/capi/geos_c.h.in#L2585-L2608) which was [ported from JTS](https://github.com/locationtech/jts/pull/823) to evaluate concave hulls [described here](https://lin-ear-th-inking.blogspot.com/2022/01/concave-hulls-in-jts.html) by Martin Davis.

See also [PostGIS docs for `ST_ConcaveHull`](https://postgis.net/docs/ST_ConcaveHull.html).

**Comment by jorisvandenbossche** [comment]
There are still some other "new" features from previous GEOS versions as well that are not yet exposed in Shapely. We should probably move over a cleaned-up version of https://github.com/pygeos/pygeos/issues/126 to the Shapely repo.
