### ISSUE TITLE
OSError: Could not find lib geos_c.dll or load any of its variants [].

### ISSUE THREAD

**Issue by geoexploring** [shapely/shapely#1297]
Hello,
I called Python code with C++, and then the Python code import the shapely library, and there was a problem: `OSError: Could not find lib geos_c.dll or load any of its variants [].`.

I found two key points: 
- When running directly in Python code, the problem doesn't occur; 
- Shapley is a CDLL, and calls to other libraries that don't have problems are WinDLL.

Could you give me some advice?  Thanks!

**Comment by geoexploring** [comment]
```python
from ctypes import *
dll = CDLL('.../lib/scipy/.libs/msvcp140.dll')
dll___ = CDLL('.../lib/shapely/DLLs/geos_c.dll')
```

The above code will not be a problem if it is executed directly in Python, but there will be a problem if you use C++ to call the Python code. The problem is still in `geos_c.dll`. Is it a flaw in the design of `geos_c.dll`?

 Thanks!

**Comment by sgillies** [comment]
@geoexploring versions of shapely < 2.0 don't support embedding in C++ programs. I think the situation will be better in version 2.0 when we stop using ctypes, but I don't guarantee it.
