### ISSUE TITLE
Improving performance of `shapely.algorithms.cga.signed_area`

### ISSUE THREAD

**Issue by whophil** [shapely/shapely#1315]
I have a program whose performance is limited by the method `shapely.algorithms.cga.signed_area`, which is not vectorized.

https://github.com/shapely/shapely/blob/7396b0823ca7fdb8b4115fb5b458bbb1057de59d/shapely/algorithms/cga.py#L4-L13

Benchmarks and a proposal follow.

## Expected behavior and actual behavior.

`shapely.algorithms.cga.signed_area` should be faster. This affects the performance of:
- `shapely.geometry.polygon.orient`
- `shapely.geometry.LinearRing.is_ccw`

## Benchmarking

```python
import numpy as np
import shapely.geometry as sg
import shapely.speedups
from shapely.algorithms.cga import signed_area
shapely.speedups.enable()

from time import time


def fast_signed_area(ring):
    """Vectorized version of shapely.algorithms.cga.signed_area"""
    coords = np.array(ring.coords)[:, :2]
    xs, ys = np.vstack([coords, coords[1]]).T
    return np.sum(xs[1:-1] * (ys[2:] - ys[:-2])) / 2.0


n_repeats = 200


cir = sg.Point((0, 0)).buffer(1.0, resolution=1024)
ring = cir.exterior

t0 = time()
[cir.area for _ in range(n_repeats)]
print('cir.area', time() - t0)

t0 = time()
[signed_area(ring) for _ in range(n_repeats)]
print('signed_area(ring)', time() - t0)

t0 = time()
[ring.is_ccw for _ in range(n_repeats)]
print('ring.is_ccw', time() - t0)

t0 = time()
[fast_signed_area(ring) for _ in range(n_repeats)]
print('fast_signed_area(ring)', time() - t0)

t0 = time()
[sg.polygon.orient(cir) for _ in range(n_repeats)]
print('orient(ring)', time() - t0)
```

Which yields
```
cir.area               0.009488105773925781
signed_area(ring)     11.10140085220337
ring.is_ccw           10.961623668670654
fast_signed_area(ring) 0.07963943481445312
orient(ring)          11.738571882247925
```
## Proposal
The vectorized `fast_signed_area` method in the benchmarking code should be a drop-in replacement. Is there any reason not to use it?

## Operating system

Linux

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)
```
shapely                   1.8.0           py310h1b8dd88_5    conda-forge
```

**Comment by whophil** [comment]
Doing a bit more digging, it seems that in prep for shapely 2.0, `shapely.algorithms.cga.is_ccw` delegates to a `pygeos` call.

The only other place I can find `shapely.algorithms.cga.signed_area` being used is in `shapely.geometry.polygon.orient`, but that could easily be swapped out for `shapely.algorithms.cga.is_ccw`, rendering the `signed_area` method useless.

**Comment by jorisvandenbossche** [comment]
Thanks for opening the issue!

Running your code on the main branch (so which indeed now uses the `is_ccw` from GEOS), I get the following timings:

```
cir.area               0.0037021636962890625
signed_area(ring)      0.43762755393981934
ring.is_ccw            0.004311800003051758
fast_signed_area(ring) 0.02290034294128418
orient(ring)           1.0624608993530273
```

So if your purpose is just to know the orientation of the ring, then `ring.is_ccw` (or `shapely.is_ccw(ring)`) is now fast (and faster as your `fast_signed_area`).

> which would render the `signed_area` method useless.

I suppose that depends on how you use it? (although even if you want the actual area (and not directly check if the signed_area > 0), combining the results of `.area` and `.is_ccw` will still be faster)

I was checking the GEOS project, and they actually also have a "signed_area" algorithm (but only for internal use, not exposed in the public API). The comments here (https://github.com/libgeos/geos/blob/d94038f2f88cee336a074b659558a75e081bc2f8/include/geos/algorithm/Orientation.h#L70-L115) give some detail about the difference. It seems that using "signed_area" to determine the orientation of a ring can be more robust in case of invalid geometries (self-intersections).

**Comment by whophil** [comment]
@jorisvandenbossche thanks for looking into this!

I should have clarified - I don't actually use `signed_area` directly, I only encounter it when using `shapely.geometry.polygon.orient`.

My point about `signed_area` being "useless" could have been made more clearly. As far as I can tell, within Shapely itself that method is only used by `shapely.polygon.orient`. The two calls to it (lines 326 and 331 in the snippet below) could be replaced with faster calls to `ring.is_ccw`, thus rendering `shapely.algorithms.cga.signed_area` unused. If it's considered part of the public API then it could either be left alone, or swapped with the vectorized version.

https://github.com/shapely/shapely/blob/d2da26aea0a2d49ea37acca4e9edc111f686aabe/shapely/geometry/polygon.py#L322-L335

**Comment by whophil** [comment]
Suggested changes here - 

https://github.com/whophil/shapely/commit/c9d10d7df97e481b45bbf784385ec37e2b257d09

**Comment by jorisvandenbossche** [comment]
A PR with that change is certainly welcome!

**Comment by whophil** [comment]
@jorisvandenbossche should the target of this change be `main`? If so, is this a feature that would be backported to 1.8.x?

**Comment by jorisvandenbossche** [comment]
This was fixed by https://github.com/shapely/shapely/pull/1323
