### ISSUE TITLE
Different maximum precision in 1.8.1

### ISSUE THREAD

**Issue by Wim-De-Clercq** [shapely/shapely#1320]
## Expected behavior and actual behavior.
I have a test which does essentially this:

_(I am aware that is an oddly high amount of decimals in the context of coordinates)_
```
geojson_string = '{"crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:EPSG::31370"}}, "type": "MultiPoint", "coordinates": [[68546.17488485049, 225804.2764637507]], "precision": 11}'
geojson_shape = geojson.loads(geojson_string)
shapely_shape = geometry.shape(geojson_shape)
print(shapely_shape.wkt)
```
With 1.8.0 this resulted in:
```
MULTIPOINT (68546.17488485049 225804.2764637507)
```
Since 1.8.1 this results in:
```
MULTIPOINT (68546.1748848505 225804.2764637507)
```
So I lost my precision of 11 and got a 10 instead.

I did try to set the `WKTWriter`'s rounding_precision, via defaults or anything. But it seems more than 10 is no longer possible?
Could this be confirmed this is a new and intended limitation now?

## Operating system
Kubuntu 20.10

## Shapely version and provenance
1.8.1 from pypi via pip.

**Comment by jorisvandenbossche** [comment]
One important different in Shapely 1.8.1, is that the wheels are now built with GEOS 3.10.2, while the Shapely 1.8.0 wheels included GEOS 3.9.1. 

So it might be caused by a change in GEOS. 
I know that GEOS 3.10 included a change in determining the precision for the WKT display (https://github.com/libgeos/geos/blob/8ca284fcca4c947fb0aad81f2f397defa5942644/NEWS.md?plain=1#L28-L29), although that should be supposed to print the necessary precision to have roundtrip safety.

But so it might be that it is only a display issue in getting the WKT through `shapely_shape.wkt`. Can you check the actual coordinates?

**Comment by jorisvandenbossche** [comment]
I suppose it is a display change. For example, if you ask Python to display 68546.17488485049, it also shows it with "less" precision:

```
>>> 68546.17488485049
68546.1748848505
```

I think this is expected for a float64 (to show a precision up to 15 numbers)

**Comment by Wim-De-Clercq** [comment]
aah yes, that (https://trac.osgeo.org/geos/ticket/868) will most likely be the reason of the change. Thanks for pointing me in the right direction.

**Comment by jorisvandenbossche** [comment]
Yep, and with the WKT conversion options, you can also tweak the display if you would want:

```
import shapely
from shapely.geometry import MultiPoint

mp = MultiPoint([[68546.17488485049, 225804.2764637507]])

>>> shapely.to_wkt(mp)
'MULTIPOINT (68546.174885 225804.276464)'

>>> shapely.to_wkt(mp, rounding_precision=-1)
'MULTIPOINT (68546.1748848505 225804.2764637507)'

>>> shapely.to_wkt(mp, rounding_precision=-1, trim=False)
'MULTIPOINT (68546.1748848504939815 225804.2764637506916188)'
```

(this is using shapely main branch, on 1.8 it looks a bit different, with `shapely.wkt.dumps`)

**Comment by mwtoews** [comment]
GEOS >= 3.10 uses [Ryu](https://github.com/ulfjack/ryu) as an [internal dependency](https://github.com/libgeos/geos/tree/main/src/deps/ryu), which will inevitably change some WKT to look a bit more compact in some cases.
