### ISSUE TITLE
What to do with the `Geometry()` class constructor?

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1330]
In pygeos, there is a single `pygeos.Geometry` class (we didn't have the Point, LineString, etc subclasses), and this was exposed in the top-level namespace. It also provided an alternative constructor for creating scalar geometries, accepting WKT or WKB, in addition to the specialized and vectorized functions:

```python
# using one of the vectorized functions (with scalar inputs, it also gives a scalar geometry as result)
>>> pygeos.points(1, 1)
<pygeos.Geometry POINT (1 1)>
>>> pygeos.from_wkt("POINT (1 1)")
<pygeos.Geometry POINT (1 1)>

# or using the Geometry class constructor
>>> pygeos.Geometry("POINT (1 1)")
<pygeos.Geometry POINT (1 1)>
```

In Shapely, we have the geometry subclasses that also provide a class constructor:

```python
>>> shapely.geometry.Point(1, 1)
<shapely.geometry.Point POINT (1 1)>
```

But as a left-over from the pygeos merger, we now also have this top-level Geometry class constructor, that returns one of the subclasses:

```python
>>> shapely.Geometry("POINT (1 1)")
<shapely.geometry.Point POINT (1 1)>
```

Having this constructor might still be useful (it can be nicer than the `from_wkt`), but it is a bit strange that this lives in the top-level namespace, while the other subclasses live in `shapely.geometry`. It is also a bit strange that `BaseGeometry` is actually a subclass of `Geometry`

In the pygeos documentation, we made heavy use of this class constructor in the docstring examples (see eg https://pygeos.readthedocs.io/en/stable/predicates.html), and so this is also still present in the new shapely docstrings after the merger.

----

The above describes the current situation in the main branch and the history behind it, but we have to decide what to do with this situation for Shapely 2.0. 

One option is to keep it as is, but I would find it a bit strange (as mentioned above) to have a top-level `Geometry()` constructor while the other classes are in a submodule, especially if this is getting used heavily in the docs. 
Of course, now we have the subclass constructors (which didn't exist in pygeos), we can also make use of those more in the docstring examples.

But some other ideas to consider:

- Completely remove the `shapely.Geometry` class from the public (top-level) namespace, and only keep it as a private `shapely.lib.Geometry` as the parent class for the concrete subclasses.
  - This means that we would need to remove it from all docs (in favor of the subclass constructors or `from_wkt`)
- Move `shapely.Geometry` to the `shapely.geometry` submodule (so all geometry classes are consistently only available from that submodule). On the long term, we could maybe also have it take the role of BaseGeomety (switch the naming of those two)
- Make all geometry subclasses available in the top-level namespace (so all geometry classes are consistently available in the top-level namespace). For backwards compatibility we of course keep them in `shapely.geometry` as well.
  - This would actually make the subclasses more accessible and easier to use (doesn't need an additional `import shapely.geometry` or `from shapely.geometry import ..`, just `import shapely` is enough). 
  - Since we are also making all the vectorized functions available in the top-level namespace (which already breaks with the pre-2.0 pattern of Shapely, xref https://github.com/shapely/shapely/issues/1225), this is also somewhat consistent with that.
  - Extra bonus: this could also help with reducing the length of the repr (xref https://github.com/shapely/shapely/pull/1302#discussion_r799844326)

cc @sgillies @mwtoews @caspervdw @brendan-ward @shapely/shapely-2

**Comment by brendan-ward** [comment]
> Make all geometry subclasses available in the top-level namespace
I like this idea the best, for all the reasons you outline.  These are core objects, rather than optional things, so in this case having them under a secondary namespace is not helpful. (though fine to keep them aliased there as well, for backward compatibility)

**Comment by snowman2** [comment]
> Move shapely.Geometry to the shapely.geometry submodule (so all geometry classes are consistently only available from that submodule). On the long term, we could maybe also have it take the role of BaseGeomety (switch the naming of those two)

I vote for this option. I think it adds clarity to have things organized into namespaces versus having everything available at the top level.

**Comment by sgillies** [comment]
I feel like using the base class as a factory for instances of sub-classes is an unusual pattern. And since `Geometry(wkt)` is redundant with `from_wkt(wkt)`, I'd prefer we omit it from the API. Keep it in geometry only and rename it to _Geometry perhaps?

:+1: on exposing concrete geometry types in the shapely namespace.

**Comment by caspervdw** [comment]
I also vote in favour of dropping the Geometry base class from the API. Shapely has made the decision of having one class per geometry type and the project should stick to that in my opinion.

I also prefer moving them into the root namespace.

**Comment by jorisvandenbossche** [comment]
OK, sounds like a combination of the first and third bullet point is the winner. Remove the `

**Comment by jorisvandenbossche** [comment]
OK, in the meantime, the subclasses are exposed in the shapely namespace (https://github.com/shapely/shapely/pull/1339), as discussed above.

For the `Geometry` base class itself, I didn't yet change anything. I was thinking that I would prefer to keep it _exposed_ in the main namespace (eg as a base class that you can use for isinstance, or for typing annotations, ...). But we can still make it not callable (the init can raise an informative error message), to effectively remove the ability to use `Geometry(wkt)`. 

So @sgillies and @caspervdw voted for dropping the `Geometry(wkt)` use to create geometries. I am still a little bit in doubt about that myself. Some (weak / subjective) arguments to maybe keep it as a way to create a geometry from a WKT string:

- When you do `Geometry(wkt)`, it is guaranteed that you get a single geometry, while `from_wkt(wkt)` can actually return an array of geometries depending on the input (so if you use this in a location where you need a scalar geometry, you need to do an additional check before/after)
- Subjectively, but for documentation / example code snippets that create the scalar geometry from WKT, I think I would prefer seeing `Geometry(..)` instead of `from_wkt(..)` 
  Although it is maybe also the question whether we should, in docstring examples like https://shapely.readthedocs.io/en/docs-restructure/measurement.html#shapely.measurement.area, rather move towards using the subclass constructors from python sequences instead of constructing from WKT (but that is quite some work to update, although something we can do progressively)

(but that is certainly not a strong opinion)

**Comment by jorisvandenbossche** [comment]
All usage of the base class `Geometry(..)` constructor has already been removed in https://github.com/shapely/shapely/pull/1414 by @brendan-ward. I am now also actually removing the ability to call the base class in https://github.com/shapely/shapely/pull/1476
