### ISSUE TITLE
RuntimeWarning: invalid value encountered in intersection

### ISSUE THREAD

**Issue by orbisvicis** [shapely/shapely#1345]
## Expected behavior and actual behavior.

``` python
>>> ls1 = shapely.geometry.LineString([(0,0), (3,0), (3,3), (0,3)])
>>> ls2 = shapely.geometry.LineString([(5,1), (6,1)])
>>> r = ls1.intersection(ls2)
>>> print(r)
.../pyvenv38/lib/python3.8/site-packages/shapely-2.0.0.dev0+31.gf048c18-py3.8-cygwin-3.3.4-x86_64.egg/shapely/set_operations.py:134:
RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
<shapely.geometry.LineString LINESTRING Z EMPTY>
```

Since verbose mode of `geosop` doesn't display any warning, I'm leaning towards reporting this for shapely rather than libgeos.
```
$ geosop -a "LINESTRING (0 0, 3 0, 3 3, 0 3)" -b "LINESTRING (5 1, 6 1)" -v -e -f wkt intersection
Input A: WKT literal
Read 1 geometries, 4 vertices  -- 1,928 usec
Input B: WKT literal
Read 1 geometries, 2 vertices  -- 9 usec
[ 1] intersection: A[1] LineString( 4 ) B[1] LineString( 2 ) -> LineString( 0 )  --  65 usec
LINESTRING EMPTY
Ran 1 intersection ops ( 6 vertices)  -- 65 usec    (GEOS 3.10.2)
```

## Operating system
Cygwin 2.918
Python 3.8.12
Numpy 1.21.4 (local build)
Shapely 2.0.0.dev0+31.gf048c18 (local build)
Geos 3.10.2

**Comment by mwtoews** [comment]
I can confirm this warning in shapely with GEOS 3.10.2, but it does not happen with GEOS 3.10.1. There's nothing in the [NEWS](https://github.com/libgeos/geos/blob/3.10/NEWS) to indicate why GEOS 3.10.2 would return invalid values for empty geometries.

It's also a bit troubling why `r.wkt` is "LINESTRING Z" yet `r.has_z` is False (as it should be). `geosop` has correct WKB/WKT outputs.

**Comment by jorisvandenbossche** [comment]
Related issue and PR: https://github.com/pygeos/pygeos/issues/357, https://github.com/pygeos/pygeos/pull/441. The last one mentions that there is "binary predicates on empty geometries set an invalid flag" that needs to be fixed upstream (in GEOS)

I think the reason that shapely now shows those warnings and eg `geosop` does not has to do with GEOS (wrongly or not) setting a floating point invalid flag, and Python or numpy checking for this and propagating that as a warning to the user.

**Comment by jorisvandenbossche** [comment]
The more relevant issue for this that was reported upstream is https://github.com/libgeos/geos/issues/515

**Comment by jorisvandenbossche** [comment]
> It's also a bit troubling why `r.wkt` is "LINESTRING Z" yet `r.has_z` is False (as it should be). `geosop` has correct WKB/WKT outputs.

GEOS seems to be inconsistent in its own functions (both below map directly to a GEOS function):

```
In [15]: shapely.has_z(r)
Out[15]: False

In [16]: shapely.get_coordinate_dimension(r)
Out[16]: 3
```

It seems that GEOSHasZ specifically special cases empty geometries: https://github.com/libgeos/geos/blob/804abffe76c4e3fbc32399b82835d6b97cda7714/capi/geos_ts_c.cpp#L2241-L2252

And for WKT, we have some custom logic of our own to handle empty 3D geometries:

https://github.com/shapely/shapely/blob/f048c1816ad5782c2e70b42c55e5d74fd19ce7e7/src/geos.c#L297-L361

The PR that made this change is https://github.com/pygeos/pygeos/pull/403 (upstream ticket: https://trac.osgeo.org/geos/ticket/1129)

But so the main question is why the empty intersection of two 2D geometries results in a 3D geometry ..

**Comment by dr-jts** [comment]
> But so the main question is why the empty intersection of two 2D geometries results in a 3D geometry ..

Currently GEOS really only supports 3D geometry (with a bit of a hack to detect if a geometry has no Z values at all).

**Comment by ronif** [comment]
Hey. Just FYI, this also happens with GEOS 3.11.x
```python
from pygeos import Geometry, intersection
aa = Geometry('POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))')
bb = Geometry('POLYGON((2 2, 2 3, 3 3, 3 2, 2 2))')
intersection(aa, bb)
```
raises
```
.../lib/python3.10/site-packages/pygeos/set_operations.py:129: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
```

Versions:
```
geos                      3.11.0               h27087fc_0    conda-forge
numpy                     1.23.4          py310h53a5b5f_1    conda-forge
pygeos                    0.13            py310h5e49deb_1    conda-forge
shapely                   1.8.5           py310h5e49deb_1    conda-forge
```
(And also for GEOS 3.11.1)

**Comment by wala-nias** [comment]
I also had this warning when trying to calculate the IoU between two Polygons.

I think the warning occurs when there is no intersection at all between the two geometries, so what I did is to check if there is an intersection first with intersects() and only then calculate the intersection between them. 

You can then handle the case where no intersection occurs according to your application.


```python
def get_iou( polygon1, polygon2):
    if polygon1.intersects(polygon2): 
        intersect = polygon1.intersection(polygon2).area
        union = polygon1.union(polygon2).area
        return intersect/union
    return 0
```

**Comment by jorisvandenbossche** [comment]
@wala-nias it's correct that this happened if there is no intersection al all, but just to note for future reference: this is fixed with latest GEOS, so you shouldn't need that workaround anymore (also, for older GEOS, an alternative workaround would also be to suppress the warning with `with np.errstate(invalid="ignore"):  ..` around the `intersection()` call.

**Comment by smacaijicoder** [comment]
sorry to ask, can you tell me how to update GEOS to 3.12.0

**Comment by zkailinzhang** [comment]
with np.errstate(invalid="ignore"):  
its ok..

**Comment by smacaijicoder** [comment]
已收到邮件，将尽快回复！

**Comment by caibengbu** [comment]
Hi,

I ran into a similar problem but in 2D.
```
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely
>>> a = shapely.from_wkt("LINESTRING (3204829.4290424557 1055076.4036336886, 3204925.3898779843 1055146.0506127975, 3204988.805030482 1055189.9383375845, 3205049.7546766037 1055230.0172892173, 3205085.648839902 1055254.1485954972, 3205129.8655231264 1055288.309059578, 3205168.702252141 1055314.9522445833, 3205199.2716745273 1055335.9284758945, 3205261.752557573 1055379.1198984436, 3205299.0476874365 1055403.2178082722, 3205324.9942403813 1055422.4915808183, 3205386.6897492786 1055465.0037103663, 3205451.4483903893 1055510.0224676146, 3205475.5766814547 1055526.127753226, 3205517.2476654723 1055553.404360999)")
>>> b  = shapely.from_wkt("LINESTRING (3205475.5766814547 1055526.127753226, 3205482.9799319166 1055515.7812855502)")
>>> c = a.intersection(b)
/Users/yesun/miniconda3/envs/pakistan-gps/lib/python3.12/site-packages/shapely/set_operations.py:131: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
>>> a.distance(c)
0.0
>>> b.distance(c)
0.0
>>> shapely.__version__
'2.0.4'
```

It seems that `c` is indeed the intersection of `a` and `b`. I am running this piece of code on a Mac with M2 chip.

Best regards,

**Comment by smacaijicoder** [comment]
已收到邮件，将尽快回复！
