### ISSUE TITLE
Wheel distribution for Python 3.10 on macosx x86_64 is missing

### ISSUE THREAD

**Issue by kvashchuka** [shapely/shapely#1348]
## Expected behavior and actual behavior.

After installing Shapely using pip, I import `lgeos` from` shapely.geos` on Mac with Intel processor and python version 3.10 (in GitHub Actions and on my machine). This results in the following error:
```
... Python/3.10.2/x64/lib/python3.10/site-packages/shapely/geos.py:54: in load_dll
    raise OSError(
E   OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib']
```
I believe it happens due to the fact that there is no wheel for Python 3.10 Intel Mac OS on PyPi, and therefore, Shapely is build from source. 

Could you please provide a wheel distribution?

## Steps to reproduce the problem.

```
pip install Shapely
python
import shapely.geometry
```
or
```
pip install Shapely
python
from shapely.geos import lgeos
```

## Operating system

Mac OS 11.6.5

## Shapely version and provenance

1.8.1.post1 installed from PyPI using pip

**Comment by mwtoews** [comment]
Looking at the [files for 1.8.1.post1](https://pypi.org/project/Shapely/1.8.1.post1/#files), there are indeed `*macosx_10_9_x86_64.whl` files for Python 3.6 to 3.9, but not 3.10. Unfortunately I'm not familiar enough with the [build recipe](https://github.com/shapely/shapely/blob/maint-1.8/.github/workflows/release.yml) to understand why Python 3.10 was not built. Perhasp @sgillies knows?

**Comment by adamjstewart** [comment]
I'm guessing https://github.com/shapely/shapely/blob/maint-1.8/.github/workflows/release.yml#L120 is the culprit and explains why cp310-win32 and cp310-manylinux_i686 are also missing. @sgillies any reason why these were excluded?

**Comment by adamjstewart** [comment]
@sgillies? I can submit a PR to remove those skips, but I'm not sure which branch(es) to submit it against. I'm also sure they were there for a reason, so maybe it will cause the tests to fail. Will this require a post2 release or can they be applied to the existing release?

**Comment by jorisvandenbossche** [comment]
> but I'm not sure which branch(es) to submit it against

It would be against the `maint-1.8` branch for a possible Shapely 1.8.2, although I see that the `main` branch (for a next Shapely 2.0 release) actually includes the same skip. It's probably easiest to first try to fix it for maint-1.8 though

**Comment by jorisvandenbossche** [comment]
This skip for Python 3.10 was originally added in pygeos (https://github.com/pygeos/pygeos/pull/427), although I don't remember why (cc @caspervdw). It might have been a mistake though (the PR changelog mentions that it dropped 32bit wheels support for Python 3.10, but cp310-macosx_x86_64 is not 32bit though)

**Comment by caspervdw** [comment]
The `cp310-win32 cp310-macosx_x86_64 cp310-manylinux_i686` builds were skipped because at that time, the latest numpy (https://pypi.org/project/numpy/1.21.3/#files) didn' t distribute for these platforms.

However a newer 1.21.x version (https://pypi.org/project/numpy/1.21.6/#files) does have support for everything but the `manylinux_i686`. I'll make a PR to the `maint-1.8` branch to incorporate the missing platforms.

**Comment by jorisvandenbossche** [comment]
@caspervdw there is already a PR for that -> https://github.com/shapely/shapely/pull/1367

**Comment by caspervdw** [comment]
Thanks for the headsup. I was just reviewing it!

**Comment by mwtoews** [comment]
See `
Shapely-1.8.2-cp310-cp310-macosx_10_9_x86_64.whl ` in https://pypi.org/project/Shapely/1.8.2/#files

**Comment by sgillies** [comment]
We've got 3.10 wheels for 7 different platforms now :open_mouth:
