### ISSUE TITLE
Point.within is not pickable

### ISSUE THREAD

**Issue by pooya-mohammadi** [shapely/shapely#1361]
The Point.within method is not pickable and can't be used in a multiprocessing pool. Are you planning to upgrade it?
shapely-version 1.8.0

**Comment by jorisvandenbossche** [comment]
I think the methods on the main branch (to become shapely 2.0) are pickleable. From a quick test:

```
In [1]: import shapely

In [2]: import pickle

In [3]: buf = pickle.dumps(shapely.Point.within)

In [4]: within_method = pickle.loads(buf)

In [5]: point = shapely.Point(1, 1)

In [6]: polygon = shapely.box(0, 0, 2, 2)

In [7]: within_method(point, polygon)
Out[7]: True
```

**Comment by pooya-mohammadi** [comment]
@jorisvandenbossche 
Thank you for your answer, the method you tested is correct. Shapes and records that are created using `shapefile` library are not pickable. My bad! I should open an issue for that library. I close the issue.
```
import shapefile
import pickle

counties = shapefile.Reader("counties.shp")
records = counties.records()

buf = pickle.dumps(records[0])
record_0 = pickle.loads(buf)
```
