### ISSUE TITLE
nearest_points on macOS and geopandas

### ISSUE THREAD

**Issue by Mikeprod** [shapely/shapely#1372]
Hello, I am facing a behaviour issue of the nearest_points with a geodataframe on MacOS, that I cannot reproduce on a Debian Linux instance.

Even with the fix from #1098 the result is the same.

## Expected behavior and actual behavior.
The nearest point between a point located inside a geometry and the geometry is not the same as the one expected.
The returned point on the geometry is `Point (0, 0.1)` but is expected to be `Point (0.1, 0.1)`.

I did not know that the nearest_points method considered "closed" polygons as surfaces, because this is mentioned nowhere in the documentation. Using the boundary of the polygon consistantly resulted in `Point (0, 0.1)` as nearest point on the polygon - boundary.

## Steps to reproduce the problem.
On macOS
```python
import pandas as pd
import geopandas as gpd
from shapely.geometry import Polygon
from shapely.ops import nearest_points

point_df = pd.DataFrame([{"x": 0.1, "y": 0.1}])
points = gpd.GeoDataFrame(point_df.copy(), crs=4326, geometry=gpd.points_from_xy(point_df.x, point_df.y))
square= Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
print(*nearest_points(square, points.geometry.iloc[0]))
```
Outputs `Point (0 0.1) Point(0.1 0.1)`

However 
```python
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, Polygon
from shapely.ops import nearest_points

point_df = pd.DataFrame([{"x": 0.1, "y": 0.1, "geometry": Point(0.1, 0.1)}])
square= Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
print(*nearest_points(square, point_df.geometry.iloc[0]))
```
Outputs `Point (0.1 0.1) Point (0.1 0.1)`

In both cases:
- `square.is_closed` equals `False`
- Identical attributes of the Point geometries 

## Operating system

Mac OS X 11.6 where the issue occured
No issue on Debian 11

## Shapely version and provenance

1.8.0 from pypi
Geopandas 0.10.2 from pypi

**Comment by sgillies** [comment]
@Mikeprod can you try shapely 1.8.1 and let us know if the problem persists?

**Comment by jorisvandenbossche** [comment]
I cannot reproduce this (but on Ubuntu).

I simplified your code snippet a bit to remove the use of geopandas, and boil it down to what should be the difference in both cases. Can you try to run the following and see if those still give different results?

```
point = Point(0.1, 0.1)
square = Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
print(*nearest_points(square, point))
```

vs

```
import numpy as np

point = Point(np.float64(0.1), np.float64(0.1))
square = Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
print(*nearest_points(square, point))
```

So the difference is that in the second case, we are passing a numpy float64 scalar as coordinates to `Point(..)`, while in the first case it is a Python float object (I wouldn't expect a difference for this, but that's the only thing I can currently think of that the `gpd.points_from_xy` would do differently).

**Comment by Mikeprod** [comment]
As suggested, with a bump to Shapely 1.8.1post1 the issue is gone. And since the upgrade, I cannot even reproduce the issue on another project with the same old dependencies.

Thanks for your help. I am closing this
