### ISSUE TITLE
Turn off self-intersection warnings

### ISSUE THREAD

**Issue by laniuros** [shapely/shapely#1374]
## Expected behavior and actual behavior.

when I run the code with CLASS MultiPolygon, messages like 
"I0427 10:00:01.197631 139759619375296 geos.py:289] Self-intersection at or near point 165.02.. 1095.701.."
would appear many times.

Is there any way to turn off these messages?

## Steps to reproduce the problem.
```python
# union_segments is a Polygon CLASS
if union_segments.geom_type != 'MultiPolygon':
    union_segments  = MultiPolygon([union_segments])
```
## Operating system

linux Ubuntu 18.04

## Shapely version and provenance

pip version 1.8.1.post1

**Comment by jorisvandenbossche** [comment]
@laniuros could you provide a small reproducible code example? (the code block above is not runnable, since `union_segments` is not defined)

Typically this is an indication that you have invalid geometries (one way to fix this is to make the geometries valid, eg with `shapely.validation.make_valid`)

**Comment by laniuros** [comment]
Is there a way to just turn off the info if it doesn't make the geometries valid?

**Comment by Romeo-PHILLIPS** [comment]
Yes I seem to be getting the same issue. For some reason I get random info logs when it can't make it valid, but I can't seem to find where the log is coming from.

**Comment by mwtoews** [comment]
There is a solution in #447 worth trying:
```python
import logging
logger = logging.getLogger()
logger.setLevel(logging.ERROR)
```

**Comment by jorisvandenbossche** [comment]
The logs typically come from a call to `is_valid` (which might get called under the hood for some other operations?)

Without reproducible example it is hard to say for sure, but my understanding is that those logs will be removed in the upcoming Shapely 2.0 release. On the shorter term for Shapely 1.8.x you can use the workaround mentioned by @mwtoews

**Comment by Romeo-PHILLIPS** [comment]
This is true is_valid is called, here is my part of code calling it:

`try:
             unchecked_polygon = Polygon(coordinates)
             polygon = (
                 unchecked_polygon
                 if unchecked_polygon.is_valid
                 else make_valid(unchecked_polygon)
             )
         except ValueError as _:
             continue `

**Comment by laniuros** [comment]
Thanks a lot, I currently only need the "logger" method to solve my problem
