### ISSUE TITLE
Set up Zenodo for Shapely

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#1379]
This task is to set up Zenodo for Shapely, to generate DOI for releases. Additional metadata in a `.zenodo.json` should be included. Also, we may need to discuss some general criteria on who should be included as authors. See, for example, [GDAL](https://github.com/OSGeo/gdal/blob/master/.zenodo.json) or [PROJ](https://github.com/OSGeo/PROJ/blob/master/.zenodo.json).

_Originally posted by @mwtoews in https://github.com/shapely/shapely/pull/1378#discussion_r862535396_

**Comment by jorisvandenbossche** [comment]
For pygeos, we didn't have such a `.zenodo.json` file. I suppose that is used to control the list of authors and description etc, if not using the default autogenerated list

**Comment by mwtoews** [comment]
Learning more about this process, no extra files are needed (althought #1455 helps). The only main thing that is required is that Zenodo needs to be configured.

@sgillies if you want [Zenodo](https://en.wikipedia.org/wiki/Zenodo) to do this (archive releases with a DOI), you'll need to authorize and enable this repo [with these steps](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content). If you are a sceptic, you can do this with [their sandbox version](https://sandbox.zenodo.org/) which mostly works, but generates fake DOIs. The mysterious thing that I find about Zenodo is that you can't delete or remove these after their published, except to email Zenodo about request. Also, you may decline to complete this task without offending anyone!

**Comment by sgillies** [comment]
@mwtoews I'm okay with Zenodo. However, at https://zenodo.org/account/settings/github/, I don't see shapely/shapely in my list. I'm involved with a lot of repos, I wonder if I've exceeded some Zenodo limit?

**Comment by mwtoews** [comment]
Have you [checked this step](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)? I pressed a "request access" button, perhaps you might have been pushed a notification for it.

**Comment by sgillies** [comment]
@mwtoews I accepted. I was unable to do anything like requesting access from Zenodo, which made me suspect that paging of repositories on the Zenodo side wasn't working.

**Comment by mwtoews** [comment]
@sgillies try checking https://zenodo.org/account/settings/github/ again, as a "sync" may have taken longer. Do you see "shapely/shapely" in the list of Repositories yet? If so, flip the switch to "ON".

**Comment by sgillies** [comment]
Done. Sorry for the delay @mwtoews !

![Screenshot from 2022-10-12 20-54-42](https://user-images.githubusercontent.com/33697/195488405-713cc79b-09f8-434d-aa2a-ade5e0b9ea7f.png)

**Comment by mwtoews** [comment]
Thanks! We'll see what happens with the upcoming 2.0 beta.
