### ISSUE TITLE
`MultiPoint` boundary iteration

### ISSUE THREAD

**Issue by adishavit** [shapely/shapely#1401]
I was trying to get the first `Point` of a `LineString`.
I ran the following code with Shapely 1.8.2:

```
line = LineString([(0, 0), (0, 1)])
p0 = line.boundary[0]  # deprecation warning
p1 = line.boundary.geom[0]  # error
```
This results in a warning and an error:
```
test.py:5: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  p0 = line.boundary[0]  # deprecation warning
  
  
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    p1 = line.boundary.geom[0]  # error
AttributeError: 'MultiPoint' object has no attribute 'geom'
```
The warning is for using the new (towars Shapely 2) `.geoms` for iteration.
The error is that for some reason "'MultiPoint' object has no attribute 'geom'".
(For example: the area of my geometry is `1.417` when it should be `1.414`.)

FWIW, I eventually used `Point(line.coords[0])` - but this mandates a call to the `Point()` constructor - a cost I was hoping to avoid (and from my measurements was slower in previous Shapely versions). 

[Shapely 1.8.2 on Windows from conda]

**Comment by jorisvandenbossche** [comment]
There is a small error in your code: the warning points to `geoms` (with "s") and not `geom` attribute. So the following code works both with older and newer versions of Shapely:

```
In [2]: line = LineString([(0, 0), (0, 1)])

In [3]: line.boundary.geoms[0]
Out[3]: <shapely.geometry.point.Point at 0x7f30bd361f40>
```

**Comment by adishavit** [comment]
🤦‍♂️ My bad. Thanks!
