### ISSUE TITLE
GEOS C Error when creating a geometry on an M1 Mac

### ISSUE THREAD

**Issue by arielkaluzhny** [shapely/shapely#1441]
Getting different flavors of a GEOS C Error whenever I try to create a geometry. `Point` & `LineString` work fine, but `Polygon`, `MultiPoint`, `MultiLineString`, and `MultiPolygon` all fail. 

I know the geometry is valid because it can be created via `GEOSGeometry`. Example:

```
from django.contrib.gis.geos import Point, Polygon, MultiPoint, MultiPolygon, MultiLineString, LineString
from django.contrib.gis.geos.geometry import GEOSGeometry

poly = GEOSGeometry('POLYGON((4 4, 4 4, 4 4, 4 4))')
poly.coords()
>>> (((4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)),)

poly2 = Polygon(((4, 4), (4, 4), (4, 4), (4, 4)))
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createPolygon_r".

ls1 = LineString((0, 0), (1, 1))
ls2 = LineString((2, 2), (3, 3))
mls = MultiLineString(ls1, ls2)
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createCollection_r".

 MultiPoint(Point(0, 0), Point(1, 1))
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createCollection_r".
```

Operating System & other info:

- MacOS Monterey 12.4, M1 chip
- gdal installed via homebrew (3.5.1)
- Python 3.8.12, Django 3.2
- also have geos and proj installed previously as dependencies via homebrew
- Have set:
    ```
    GDAL_LIBRARY_PATH="/opt/homebrew/lib/libgdal.dylib"`
    GEOS_LIBRARY_PATH="/opt/homebrew/lib/libgeos_c.dylib"
    ```

Exact same code is working on an older Mac setup w/ the same environment just fine.

Have also now tried Python 3.9 and reinstalling all related brew packages.

--- 

> I think this is the right place for this, please let me know if not or if you need any other information! Thank you.

**Comment by jorisvandenbossche** [comment]
@arielkaluzhny it seems your example is using django geometries, and not Shapely geometries (both packages provide bindings to GEOS). You will need to report it to django instead (see https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/ for how to do that)

**Comment by arielkaluzhny** [comment]
> You will need to report it to django instead

Will do, thank you!

**Comment by esauser** [comment]
@arielkaluzhny did you end up opening an issue with `Django`?  I'm seeing this same problem but didn't see your issue.

**Comment by arielkaluzhny** [comment]
> @arielkaluzhny did you end up opening an issue with `Django`? I'm seeing this same problem but didn't see your issue.

@esauser - Yes! Turns out it's already fixed. If you upgrade to Django 4.0.1 or higher it should work.

https://github.com/django/django/blob/4f284115a9181990f713d5167b25628fa171a5e4/docs/releases/4.0.1.txt#L67-L70

**Comment by progiri** [comment]
> @esauser - Yes! Turns out it's already fixed. If you upgrade to Django 4.0.1 or higher it should work.

Is there any solution without upgrading Django version? I can't upgrade Django now on production

**Comment by arielkaluzhny13** [comment]
> Is there any solution without upgrading Django version? I can't upgrade Django now on production

Not that I personally know of -- also haven't worked on this in 2 years. There may be workarounds of using different types of shapes and converting, but not sure.

**Comment by arielkaluzhny** [comment]
> Is there any solution without upgrading Django version? I can't upgrade Django now on production

Not that I personally know of -- also haven't worked on this in 2 years. There may be workarounds of using different types of shapes and converting, but not sure.
