### ISSUE TITLE
Segmentation Fault on geos_linestring_from_py (linestring.py)

### ISSUE THREAD

**Issue by davideluque** [shapely/shapely#1463]
## Expected behavior and actual behavior.

The library should not throw a segmentation fault.

## Steps to reproduce the problem.

```python
from shapely.geometry import LineString

LineString([[1, 1], [2, 2], [3, 3], [4, 4]])
```

When I try this on the Python interpreter it works but it does not work in a Unit Test I have on Django Project

## Operating system

MacOS Monterey 12.5 (21G72)

## Shapely version and provenance

Shapely==1.8.2 through pip

**Comment by jorisvandenbossche** [comment]
@davideluque thanks for the report! 
I don't have a Mac myself, so can't help with diagnosing this (but in any case I can't reproduce this on linux). Potentially related to https://github.com/shapely/shapely/issues/1449. Given that you mention it works in a Python interpreter but not when running unittests, it might have something to do with GEOS discovery at runtime / how the environment is created and activated in both cases.

**Comment by jorisvandenbossche** [comment]
> The only reason I can think of is that I could have (unintentionally) updated packages through brew. I have to do research on the packages that are installed through brew and the library uses. If you could mention them here that would be very much appreciated.

The main one I can think of is `geos` (and having `geos` installed from multiple sources is certainly a potential issue)

**Comment by davideluque** [comment]
Closing for now as I do not have this issue anymore (not working anymore in the related project)
