### ISSUE TITLE
polygon.py example at http://toblerity.org/shapely/manual.html#polygons doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [shapely/shapely#149]
kbriggs:~> python polygon.py 
Traceback (most recent call last):
  File "polygon.py", line 3, in <module>
    from descartes.patch import PolygonPatch
ImportError: No module named descartes.patch

**Comment by gavanderhoorn** [comment]
@pelson wrote:
> Looks like figures is in the same directory. Are you running from within the folder containing polygon?

Most likely I'm missing something, but I'm running into the same issue (`ImportError: No module named figures`). To which directory are you referring to exactly?

**Comment by mangtronix** [comment]
I believe the example code isn't installed by pip. You can get the full source of the examples on github, including the necessary figures.py https://github.com/Toblerity/Shapely/tree/master/docs/code
