### ISSUE TITLE
distance() on 3D geometries *silently* projects to 2D

### ISSUE THREAD

**Issue by jonaraphael** [shapely/shapely#1495]
Hi there, and thanks for making such an incredibly useful product!!!
I wanted to let you know about some math that appears to be broken in this library. 

Issue:
**Despite allowing 3D geometries [e.g. Point(0,0,0) and LineString(((0,0,1), (1,1,0))], when I try to do any Cartesian math with them, the result seems to first (silently) project back down to 2D, by throwing away the Z coordinate, before returning the result.**

Example:
> Point(0,0,0).distance(LineString(((0,0,1), (1,1,0))))

Expected Behavior:
In 3D Cartesian math, this should should return "0.81649..." or sqrt(2/3).
However, in shapely it returns "0" (even though you can see these two geometries do not intersect).

Desired Behavior:
Ideally, the library would do the actual calculations in 3-space. 
If it can't do that, then it should at least raise a warning anytime it does an automatic discarding of data (e.g. removing the Z coord), and then proceed with the 2D calculation.
pygeos has the same undesirable behavior, so I don't expect it will be resolved automatically during the integration.

Thanks, and apologies if you've already addressed this in another issue!

**Comment by jonaraphael** [comment]
Oops! 
Of course, immediately after posting, I found this https://github.com/shapely/shapely/issues/613

I do, of course, understand that this is intended behavior (as described in the shapely docs), but nonetheless, it seems like an extremely useful extension to existing functionality, and is implicitly implied by the ability to do math on 3D objects. 

Perhaps you might just consider this note as an additional request for this feature (3D math) to be supported.

**Comment by jorisvandenbossche** [comment]
> even though you can see these two geometries do not intersect

Note that also for predicates like intersects, shapely (GEOS) will ignore the 3rd dimension, so while I know those don't intersect in 3D, shapely will actually say they do:

```
In [6]: Point(0,0,0).intersects(LineString(((0,0,1), (1,1,0))))
Out[6]: True
```

While distance might be relatively simple in 3D, other operations like those predicates or overlays are not at all, so I suppose that is the main reason this is not supported. An actual feature request would also need to be directed to https://github.com/libgeos/geos

**Comment by jonaraphael** [comment]
Thanks for the additional information, @jorisvandenbossche!

Just curious if you know offhand of any Python libraries that are nearly as powerful as shapely, but are designed to handle 3D math properly? 
I always think of shapely as the leader in the field, but it seems like I'll need to patch over this hole in functionality by bringing in another library.

**Comment by jorisvandenbossche** [comment]
`scikit-geometry` (https://scikit-geometry.github.io/scikit-geometry/index.html) might handle this, as CGAL bindings (https://www.cgal.org/). But I have no experience with that, so can't say for sure.

**Comment by patrickcgray** [comment]
Hi @jonaraphael I'm curious if you ended up finding any good distance function for your use case?

**Comment by jonaraphael** [comment]
@patrickcgray , It's been a while, but I believe that I ended up writing custom functions that performed actual 3D math on the coordinates, instead of using another library. The math itself isn't too complicated--but it was certainly frustrating to not have a single-stop solution at hand. Good luck with your endeavor!
