### ISSUE TITLE
Add a pygeos migration guide for Shapely 2.0 

### ISSUE THREAD

**Issue by caspervdw** [shapely/shapely#1500]
The Shapely 2.0 migration guide is now focused on shapely users, but we need to inform existing pygeos users as well.

@jorisvandenbossche

**Comment by akadouri** [comment]
The change of segmentize's `tolerance` parameter to `max_segment_length` is one item that needs to be documented. https://github.com/shapely/shapely/pull/1506

**Comment by jorisvandenbossche** [comment]
The relevant changes from https://github.com/shapely/shapely/issues/1276 are:

- `preserve_topology=True` now default in `simplify` function(https://github.com/shapely/shapely/pull/1392)
- renamed `apply` to `transform` (https://github.com/shapely/shapely/pull/1393)
- The buffer keyword `quadsegs` -> `quad_segs` (https://github.com/shapely/shapely/pull/1512)
