### ISSUE TITLE
Shapely not publishing aarch64 wheels starting at 1.8.3

### ISSUE THREAD

**Issue by AWSjswinney** [shapely/shapely#1504]
## Expected behavior and actual behavior.

aarch64 wheels are no longer being published to pypi.org

## Steps to reproduce the problem.

Attempt to install shapely from pip on an aarch64 linux system.

## Operating system

manylinux/aarch64

## Shapely version and provenance

Shapely versions 1.8.3 and newer

**Comment by sjev** [comment]
Confirmed.  Had to revert to 1.8.2 to run on arm.

**Comment by jorisvandenbossche** [comment]
I was a bit puzzled about this since we didn't change any wheel build configuration between 1.8.2 and 1.8.3/4, but so it seems that the aarch64 wheels are still build at https://github.com/shapely/shapely-wheels, and we didn't update that for 1.8.3

cc @sgillies

**Comment by sgillies** [comment]
`manylinux_2_17_aarch64.manylinux2014_aarch64` wheels for 1.8.4 (only, not 1.8.3) are on PyPI now. Thanks for the report!

**Comment by jorisvandenbossche** [comment]
@sgillies it seems we have the same issue with 1.8.5 of missing aarch64 wheels

**Comment by sgillies** [comment]
There are 3 new wheels (Python 3.9-3.10) here: https://pypi.org/project/Shapely/1.8.5.post1/#files. Python 3.11 has some different problems that I can't address today.

**Comment by jorisvandenbossche** [comment]
Thanks @sgillies !
