### ISSUE TITLE
geos.py: frozen is missing _lgeos (darwin)

### ISSUE THREAD

**Issue by kaalleen** [shapely/shapely#1526]
Introduced in [#c04f8c68130c8a4da04ef2cf92b38b7f1a4d4db7](https://github.com/shapely/shapely/commit/c04f8c68130c8a4da04ef2cf92b38b7f1a4d4db7)

Add `_lgeos = load_dll('geos_c', fallbacks=alt_paths)` in

https://github.com/shapely/shapely/blob/2621cf13787b7de8944a9f7eb327095ce94cf6ac/shapely/geos.py#L148

**Comment by jorisvandenbossche** [comment]
@kaalleen thanks for the report! I am not familiar with frozen / mac myself (and also wouldn't be able to test). Could you open a PR with the change that you think is needed?

**Comment by kaalleen** [comment]
Sure, I created a pull request. Hope this adds to the correct branch (maint-1.8), geos.py looks completely different in main.

Without _lgeos set shapely will break for frozen darwin apps and outputs this error:

`AttributeError: 'NoneType' object has no attribute GEOSversion`

**Comment by jorisvandenbossche** [comment]
Thanks for the PR! I see now what you meant, that's an unfortunate oversight from https://github.com/shapely/shapely/commit/c04f8c68130c8a4da04ef2cf92b38b7f1a4d4db7

**Comment by mwtoews** [comment]
Closed by #1528
