### ISSUE TITLE
Subclasses of numpy.ndarray

### ISSUE THREAD

**Issue by mikedh** [shapely/shapely#1539]
Thanks for all the great work on Shapely 2! I was updating a test suite to pass with Shapely 2, and I noticed that one of the failures was caused by a subclassed `numpy.ndarray` not being handled. I can add a `values.view(np.ndarray)` to fix my cases of this but it seems like it could also be handled in shapely (although I'm not sure exactly where):

## Expected behavior and actual behavior.
```
In [21]: vertices.shape
Out[21]: (394, 2)

In [22]: type(vertices)
Out[22]: trimesh.caching.TrackedArray

In [23]: isinstance(vertices, np.ndarray)
Out[23]: True

In [24]: Point([0,0])
Out[24]: <POINT (0 0)>

In [25]: Point(np.zeros(2))
Out[25]: <POINT (0 0)>

In [26]: Point(vertices[0])
----------------------------------------------------------------
ValueError                     Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 Point(vertices[0])

File ~/venv/lib/python3.10/site-packages/shapely/geometry/point.py:78, in Point.__new__(self, *args)
     75     geom = shapely.points(*args)
     77 if not isinstance(geom, Point):
---> 78     raise ValueError("Invalid values passed to Point constructor")
     79 return geom

ValueError: Invalid values passed to Point constructor

In [31]: Point(vertices[0].view(np.ndarray))
Out[31]: <POINT (2.983 4.944)>
```

## Operating system

Ubuntu 20.04

## Shapely version and provenance

`pip install --pre shapely==2.0a1`

**Comment by jorisvandenbossche** [comment]
@mikedh Thanks a lot for testing shapely 2.0, and for reporting this issue!

Could you show what `shapely.points(vertices[0])` returns?

**Comment by mikedh** [comment]
Good call! Looks like `shapely.points` works, but `shapely.geometry.Point` raises:

```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '2.0a1'

In [3]: import trimesh

In [4]: v = trimesh.creation.box().vertices

In [5]: v.__class__
Out[5]: trimesh.caching.TrackedArray

In [6]: import numpy as np

In [7]: shapely.points(np.zeros(2))
Out[7]: <POINT (0 0)>

In [8]: shapely.points(v[0])
Out[8]: TrackedArray(<POINT Z (-0.5 -0.5 -0.5)>, dtype=object)

In [9]: from shapely.geometry import Point

In [10]: Point(v[0])
----------------------------------------------------------------
ValueError                     Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 Point(v[0])

File ~/venv/lib/python3.8/site-packages/shapely/geometry/point.py:78, in Point.__new__(self, *args)
     75     geom = shapely.points(*args)
     77 if not isinstance(geom, Point):
---> 78     raise ValueError("Invalid values passed to Point constructor")
     79 return geom

ValueError: Invalid values passed to Point constructor

In [11]: Point(np.zeros(2))
Out[11]: <POINT (0 0)>
```

**Comment by jorisvandenbossche** [comment]
> ```
> In [7]: shapely.points(np.zeros(2))
> Out[7]: <POINT (0 0)>
> 
> In [8]: shapely.points(v[0])
> Out[8]: TrackedArray(<POINT Z (-0.5 -0.5 -0.5)>, dtype=object)
> ```

So it seems that numpy converts 0d arrays to scalars, while your subclass does not? 

We also see this in other shapely ufuncs, that if you pass a 0d numpy array with a single geometry object, the output doesn't preserve this 0d array, but returns a scalar instead:

```
In [1]: import shapely

In [2]: p = shapely.Point(1, 1)

In [3]: arr = np.array(p)

In [4]: arr
Out[4]: array(<POINT (1 1)>, dtype=object)

In [5]: shapely.is_empty(arr)
Out[5]: False

In [6]: np.isscalar(arr)
Out[6]: False

In [7]: np.isscalar(shapely.is_empty(arr))
Out[7]: True
```

I know that the distinction between 0d arrays vs scalars is a long ongoing topic in numpy, so it might be that numpy has some custom logic here for ufuncs with 0d arrays/scalars.

**Comment by jorisvandenbossche** [comment]
Based on a quick search in the numpy issues, it seems this is a known issue:

* https://github.com/numpy/numpy/issues/4563
* https://github.com/numpy/numpy/issues/5819

**Comment by jorisvandenbossche** [comment]
You might be able to "fix" this on the trimesh side, by adding a `__array_wrap__` that converts the 0d array to a scalar (eg https://github.com/pyvista/pyvista/pull/2770)

**Comment by mikedh** [comment]
Thanks for the debugging and suggestion! Great point, I'll do the same thing as pyvista until upstream numpy fixes that.
