### ISSUE TITLE
Set operations do not explicitly document `None` return value for empty input sequences

### ISSUE THREAD

**Issue by kveretennicov** [shapely/shapely#1545]
Shapely 2.0a1 from pypi

For example:
```
>>> from shapely.ops import unary_union
>>> unary_union([]) is None
True
```

Documentation only mentions this as the case for returning `None`:
> If all elements of the given axis are None, None is returned.

**Comment by kveretennicov** [comment]
I could not spot any tests for this behaviour neither, which makes me question: is it intentional or accidental?

**Comment by jorisvandenbossche** [comment]
We are actually in the process of changing this behaviour to return an empty geometry instead (to preserve the behaviour of shapely <= 1.8), see https://github.com/shapely/shapely/issues/1332 for more details.

**Comment by kveretennicov** [comment]
Oh, apologies for the noise. I'll close given that #1332 already tracks this code/docs discrepancy.
