### ISSUE TITLE
pyproject.toml: 'wheel' missing in build requirements

### ISSUE THREAD

**Issue by rmvanhees** [shapely/shapely#1568]
When I install Shapely using:
 > pip3 install -U --no-binary=Shapely Shapely
      
Then I get the following warnings:
> WARNING: Missing build requirements in pyproject.toml for Shapely from https://files.pythonhosted.org/packages/21/d0/82ea9573c9ba8e7a5709ee08681249ad25411382f6440f548981286f3b74/Shapely-1.8.5.tar.gz.
> WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.

This can easily be fixed by added 'wheel' to the list of required packages under [build-system] in the file pyproject.toml

Thanks, Richard van Hees

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

So we removed `wheel` in https://github.com/shapely/shapely/pull/1481 (see comment at https://github.com/shapely/shapely/pull/1481#discussion_r946453465), but so I suppose this is only for recent setuptools versions that it is not needed anymore to specify `wheel`

We should also add `build-backend = "setuptools.build_meta"` (as is done on the main branch)

**Comment by rmvanhees** [comment]
You are right. I looked at the main branch. I assumed that pyproject.toml of the main branch would be equal to 1.8.5. 

Adding build-backend to pyproject.toml of the 1.8 branch should fix the warnings. 

I tried the main branch which compiles fine on my Ubuntu system (custom Python 3.10.8 installation GEOS 3.11, PROJ 9.1) without warnings from setuptools 65.4.1 :-) 

Thanks
