### ISSUE TITLE
ENH: allow arrays as argument to Geometry methods

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1588]
Currently, the Geometry scalars typically accept only scalar arguments in their methods. Take for example the `contains` method:

```python
import shapely
polygon = shapely.Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
point = shapely.Point(0.5, 0.5)
points = shapely.points([(0, 0), (0.5, 0.5), (1, 1)])
```

We can check this using the method for a single point:

```python
>>> polygon.contains(point)
True
```

But when passing the array of points (which might seem a logical thing to do for the user), we get an error at the moment:

```python
>>> polygon.contains(points)
...
~/scipy/repos/shapely/shapely/geometry/base.py in contains(self, other)
    596     def contains(self, other):
    597         """Returns True if the geometry contains the other, else False"""
--> 598         return bool(shapely.contains(self, other))
    599 
    600     def crosses(self, other):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

And for this case you need to use the top-level function instead:

```python
>>> shapely.contains(polygon, points)
array([False,  True, False])
```

This of course works fine, but I think it can be surprising for users that it doesn't work for the Polygon method, and in any case the current error you get is quite unclear. 
The only reason we get the error, is because inside the method we call `bool(..)` on result of `shapely.contains(..)`, with the goal to convert the numpy boolean scalar to a Python bool. 

But we could easily relax this and do this conversion to a Python bool _only if_ the result is a scalar, and not an array. For example, if the implementation would look like:

```python
def contains(self, other):
    result = shapely.contains(self, other)
    return bool(result) if result.ndim == 0 else result
```

then `polygon.contains(points)` would also work and return the array `array([False,  True, False])`.

I think this would be a nice convenience for users (also especially for GeoPandas users since we have methods on GeoSeries that also accept array likes of geometries), and would also make it consistent for _all_ methods, since the above actually already works for methods that return geometries (where we don't have this conversion step from numpy to python scalar):

```python
# for methods that return geometries, this already works
>>> polygon.intersection(points)
array([<POINT (0 0)>, <POINT (0.5 0.5)>, <POINT (1 1)>], dtype=object)
```

cc @shapely/shapely-2

**Comment by martinfleis** [comment]
Is there a plan to make this part of 2.0 release? I think it is really handy and the implementation overhead is quite small.

**Comment by jorisvandenbossche** [comment]
Yes, I hope so, was planning to make a PR in the coming days
