### ISSUE TITLE
LineString creation is 167x slower than it needs to be

### ISSUE THREAD

**Issue by Lyle-Alloy** [shapely/shapely#1601]
Found this because we upgraded our codebase to shapely 2.0b1 (We're very excited!!!!) and I noticed a serious performance regression on some of our code

## Expected behavior and actual behavior.

Calling `geometry.LineString()` with a numpy array as the argument should be fast, but it has become ~167x slower. I suspect that this is because it iterates and calls a function to check for points on every coordinate (!!!). 

We could refactor to use `creation.linestrings()` everywhere in our codebase, but I'm not sure I understand why the `__new__` implementation for one of the base types should do something so slow.

## Steps to reproduce the problem.

```
>>> import timeit
>>> timeit.timeit("LineString(points)", setup="from shapely import LineString; import numpy.random; points = numpy.random.default_rng().uniform(0, 1000, (10000, 2))", number=1000)
<<< Out[6]: 5.013867567000034
>>> timeit.timeit("linestrings(points)", setup="from shapely.creation import linestrings; import numpy.random; points = numpy.random.default_rng().uniform(0, 1000, (10000, 2))", number=1000)
<<< 0.030582338000158416
```

## Proposed fix

Remove this check 

https://github.com/shapely/shapely/blob/main/shapely/geometry/linestring.py#L52-L59

## Operating system

MacOS 12.6.1

## Shapely version and provenance

2.0b1

**Comment by jorisvandenbossche** [comment]
Thanks for testing shapely 2.0 beta, and for the report!

This iteration through all points was preserved from the [1.8.x codebase](https://github.com/shapely/shapely/blob/9cf3cdfae7c9aa01b56c7151a51e6a517cceabdd/shapely/geometry/linestring.py#L261-L265), but, something that was missed when refactoring this for 2.0, is that for 1.8x there was a cython version of this function that had a different logic to special case numpy array input. This can actually be seen when disabling/enabling those speed-ups:

```
import numpy as np
from shapely.geometry import LineString
import shapely.speedups

points = np.random.default_rng().uniform(0, 1000, (10000, 2))

In [5]: shapely.speedups.disable()

In [6]: %timeit LineString(points)
16.3 ms ± 490 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: shapely.speedups.enable()

In [8]: %timeit LineString(points)
118 µs ± 2.77 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

For 2.0, we can't simply remove this check (that would break behaviour for constructing LineString(..) from a sequence of points), but we can of course do again a similar check for a numeric numpy array, and in that case directly pass this to the linestrings constructor.

With the current shapely 2.0, I get:

```
In [2]: %timeit LineString(points)
4.02 ms ± 50.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

(so even slower than 1.8 with speedups disabled)

With a small patch to pass through numeric numpy arrays, I get:

```
In [2]: %timeit LineString(points)
24.2 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

which makes it almost as fast as `shapely.linestrings(points)` (just a bit of extra overhead), and which is then even faster than 1.8 with the special handling for numpy arrays enabled.

Will open a PR with that change.

**Comment by Lyle-Alloy** [comment]
Thanks for getting to this so quickly! I was ready to come in Monday morning and open a pull request for it but you triaged, fixed and merged it all before I could blink!

I'll try installing off of main and trying it now
