### ISSUE TITLE
Polygon.difference is wrong for enclosed polygons, and there's seemingly no way to check this condition

### ISSUE THREAD

**Issue by TysonRayJones** [shapely/shapely#1621]
As per [this](https://stackoverflow.com/questions/74482846/check-whether-an-enclosed-polygon-shares-a-boundary-in-shapely-and-python) stackoverflow question, when `a` and `b` are polygons where `a` completely encloses `b`, the result of
```
a.difference(b)
```
will be erroneous (because the true result cannot be expressed as polygon).  That's irksome, but even checking the condition of "completely encloses" is seemingly not possible due to that behaviour!

Full details in the linked SO post.

**Comment by TysonRayJones** [comment]
Oops indeed there *is* an interior polygon collection (`a.difference(b).interiors`). Likely my misconception caused my problem

**Comment by jorisvandenbossche** [comment]
FYI, the upcoming shapely 2.0 release includes a `shapely.plotting` module that will help to inspect the polygons in such cases.
