### ISSUE TITLE
DOC: Enhance description of STRtree to indicate that geometries are indexed and queried based on extents

### ISSUE THREAD

**Issue by adishavit** [shapely/shapely#1622]
## Expected behavior and actual behavior.

`STRTree` returns a collision where there is none.
A minimal case:
![image](https://user-images.githubusercontent.com/1814800/203543996-a7112095-d178-4049-a72e-3341e576852a.png)

## Steps to reproduce the problem.

```python
from shapely import wkt
from shapely.strtree import STRtree

poly_query = wkt.loads('POLYGON ((58.27 44.72, 56.96 47.18, '
                       '58.47 47.98, 59.78 45.52, '
                       '58.27 44.72))')
poly_in_tree = wkt.loads('POLYGON ((57.94 44.73, 57.94 44.42, '
                         '56.02 44.42, 56.02 44.73, '
                         '57.94 44.73))')

query_tree = STRtree([poly_in_tree])
collide_objects = query_tree.query_geoms(poly_query)

assert not poly_in_tree.intersects(poly_query)
assert 0 == len(collide_objects)
```
## Operating system
Windows

## Shapely version and provenance
Shapely 1.8.2 via `conda`.

**Comment by brendan-ward** [comment]
@adishavit by default, tree queries return results based on intersecting extents, not intersections of the underlying geometries.  STRtree is based on the extents of geometries.

In Shapely 1.8, it is expected that you would need to do a predicate (intersects) test against the tree query results to find those geometries that actually intersect.

In [Shapely 2.0](https://shapely.readthedocs.io/en/latest/strtree.html#shapely.STRtree.query), you can now query the tree and perform the predicate test at the same time using: `query_tree.query(poly_query, predicate="intersects")`.

**Comment by adishavit** [comment]
OK, so there is no reason to pre-prep the tree geoms. Lazy prepping is usually sufficient. 

IIUC, what you are also saying is that due to "caching" of the prep geoms, it would be better to filter by `[query.intersects(p) for p in hits]` than `[p.intersects(query) for p in hits]`?

I thought that when `.intersects()` is called, both args are preped symmetrically.

**Comment by brendan-ward** [comment]
Note that my guidance is targeted at Shapely 2+; not all of it holds true for Shapely 1.8.  Prepared geometries are indeed cached as part of their corresponding geometry.

I don't believe that Shapely is (yet) automatically preparing geometries for you when you call predicate functions, with the exception of the predicates used within STRtree and `contains_properly` predicate which only exists for prepared geometries.  In both cases, the prepared geometries are automatically destroyed if they are automatically created.

You can get the tree to do the filtering for you by `query_tree.query(poly_query, predicate="intersects")`; you only need to filter afterward if you are wanting to use a different predicate against the tree versus afterward.

**Comment by adishavit** [comment]
I’m using Shapely 1.8, so I have to do the filtering manually.
