### ISSUE TITLE
TST: Intermittent failure in test_remove_repeated_points_invalid_result on Linux

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1650]
The Linux builds for GEOS 3.11 and main started to regularly fail (but not always) in the `test_remove_repeated_points_invalid_result` test (`remove_repeated_points` is new in GEOS 3.11, so those two builds are the only ones that run this test):

```
 =================================== FAILURES ===================================
_____________ test_remove_repeated_points_invalid_result[geom0-2] ______________

geom = <POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))>, tolerance = 2

    @pytest.mark.skipif(shapely.geos_version < (3, 11, 0), reason="GEOS < 3.11")
    @pytest.mark.parametrize(
        "geom, tolerance", [[Polygon([(0, 0), (1, 0), (1, 1), (0, 1), (0, 0)]), 2]]
    )
    def test_remove_repeated_points_invalid_result(geom, tolerance):
>       with pytest.raises(shapely.GEOSException, match="Invalid number of points"):
            shapely.remove_repeated_points(geom, tolerance)
E       Failed: DID NOT RAISE <class 'shapely.errors.GEOSException'>
```

I can't reproduce it locally.

**Comment by jorisvandenbossche** [comment]
Adding some print debug statements in https://github.com/shapely/shapely/pull/1651 indicates that _if_ it fails to raise the expected error, then it returns the (invalid) polygon `POLYGON ((0 0, 0 0, 0 0))` (which is strange that this could be returned, because normally GEOS should error when trying to construct a LinearRing of 3 points)

I opened an issue about this on the GEOS side: https://github.com/libgeos/geos/issues/759

**Comment by mwtoews** [comment]
One consideration is to use a [flaky plug-in](https://github.com/box/flaky) for [flaky tests](https://docs.pytest.org/en/7.1.x/explanation/flaky.html).

**Comment by jorisvandenbossche** [comment]
To not have red CI on our side, you mean? (so we can ignore it for now) I could also add an xfail strict=False (to not have to add an additional test dependency)

**Comment by mwtoews** [comment]
Yes, either approach to "ignore it for now", since it's an upstream issue.

**Comment by jorisvandenbossche** [comment]
This is already fixed upstream in GEOS main, so I will just skip the test for now for 3.11 and only run it with GEOS main (if 3.11 gets a bugfix release with this included, we could revert that) -> https://github.com/shapely/shapely/pull/1656
