### ISSUE TITLE
Version missing in 2.0rc2

### ISSUE THREAD

**Issue by sebastic** [shapely/shapely#1653]
## Expected behavior and actual behavior.

geoalchemy2 fails because the version comparison fails:
```python
if parse_version(shapely.__version__) < parse_version("1.7"):  # pragma: no cover
```

Shapely doesn't provide a usable version:
```
>>> shapely.__version__ 
'0+unknown'
>>> shapely._version.get_versions()
{'date': None, 'dirty': None, 'error': 'unable to compute version', 'full-revisionid': None, 'version': '0+unknown'}
```

`shapely.__version__` should return `2.0rc2`.

`cfg.versionfile_source` in `_version.py` is wrong:
```python
$ grep cfg.versionfile_source shapely/_version.py 
    cfg.versionfile_source = "pygeos/_version.py"
        for i in cfg.versionfile_source.split("/"):
```
`pygeos/_version.py` does not exist in the source tree.

## Steps to reproduce the problem.

On Debian unstable with experimental sources:
```
apt install -t experimental python3-shapely
python3 -c 'import shapely; print(shapely._version.get_versions())'
```

## Operating system

Debian unstable

## Shapely version and provenance

2.0rc2 Debian package.

**Comment by sebastic** [comment]
versioneer doesn't work for package builds, it doesn't provide a way to set the version like setuptools_scm:

 https://github.com/python-versioneer/python-versioneer/labels/fallback

**Comment by mwtoews** [comment]
I was scheming to propose setuptools_scm a few weeks ago (https://github.com/mwtoews/shapely/tree/setuptools-scm), but held back as to accumulate too many changes / delay any further. Is it worthwhile pushing this thru for another rc?

**Comment by sebastic** [comment]
Yes, rc3 should include a fix this issue.

The changes in #1654 may suffice.

The _version.py in the GitHub tarball should be correct then.

**Comment by jorisvandenbossche** [comment]
Yes, certainly will do a rc3 with this fix

**Comment by jorisvandenbossche** [comment]
@sebastic I suppose the reason you run into this is because you use the github created archive for debian packaging? (for example on https://github.com/shapely/shapely/releases/tag/2.0rc2, the "Source code (tar.gz)" download link, not the sdist that was uploaded (first link "shapely-2.0rc2.tar.gz")).

Is the reason for that because there are additional files you need that are not included in the sdist? 
(I would always recommend to start from the sdist if possible, since that is the official release artifact, and also has proper versions without relying on the file name)

**Comment by sebastic** [comment]
The tag tarball is present for all GitHub projects, only a subset also publish release assets.

The generated files in sdist are of little value for Debian packages, those are regenerated during the package build. Many projects are also not good at maintaining MANIFEST.in, making the sdist unusable due to missing test files, etc.

**Comment by jorisvandenbossche** [comment]
Makes sense!

> The generated files in sdist are of little value for Debian packages

I don't think there are generated files in our case (except for the `_version.py` file in question, where it is actually useful)

**Comment by sebastic** [comment]
These are the generated files in the release tarball:

 * PKG-INFO
 * shapely.egg-info/*

The package clean targets removes them before starting the build where they are regenerated when using setuptools, and with the use pybuild-plugin-pyproject PEP517 .dist-info is generated instead.

**Comment by jorisvandenbossche** [comment]
Ah, OK, I was thinking about generated files in the package itself (eg generated C files that some packages might include).

In any case, 2.0 rc3 has been ragged!

**Comment by jorisvandenbossche** [comment]
Good to hear, thanks!
