### ISSUE TITLE
REGR: Constucting Polygon from Point list fails

### ISSUE THREAD

**Issue by snowman2** [shapely/shapely#1662]
## Expected behavior and actual behavior.

Error message:

```
self = <class 'shapely.geometry.polygon.Polygon'>
shell = array([<POINT (-95 41)>, <POINT (-95 42)>, <POINT (-94 42)>,
       <POINT (-94 41)>], dtype=object)
holes = None
    def __new__(self, shell=None, holes=None):
        if shell is None:
            # empty geometry
            # TODO better way?
            return shapely.from_wkt("POLYGON EMPTY")
        elif isinstance(shell, Polygon):
            # return original objects since geometries are immutable
            return shell
        # else:
        #     geom_shell = LinearRing(shell)
        #     if holes is not None:
        #         geom_holes = [LinearRing(h) for h in holes]
    
        if holes is not None:
            if len(holes) == 0:
                # shapely constructor cannot handle holes=[]
                holes = None
            else:
                holes = [LinearRing(ring) for ring in holes]
    
        if not isinstance(shell, BaseGeometry):
            if not isinstance(shell, (list, np.ndarray)):
                # eg emtpy generator not handled well by np.asarray
                shell = list(shell)
            shell = np.asarray(shell)
    
            if len(shell) == 0:
                # empty geometry
                # TODO better constructor + should shapely.polygons handle this?
                return shapely.from_wkt("POLYGON EMPTY")
    
            if not np.issubdtype(shell.dtype, np.number):
                # conversion of coords to 2D array failed, this might be due
                # to inconsistent coordinate dimensionality
>               raise ValueError("Inconsistent coordinate dimensionality")
E               ValueError: Inconsistent coordinate dimensionality
.../lib/python3.9/site-packages/shapely/geometry/polygon.py:251: ValueError

```
## Steps to reproduce the problem.

This fails:
```python
from shapely.geometry import Point, Polygon

geom = Polygon([Point(-95, 41), Point(-95, 42), Point(-94, 42), Point(-94, 41)])
```

This works:
```python
from shapely.geometry import LinearRing, LineString, Point, Polygon

geom = Polygon([(-95, 41), (-95, 42), (-94, 42), (-94, 41)])
geom = Polygon(LinearRing([Point(-95, 41), Point(-95, 42), Point(-94, 42), Point(-94, 41)]))
geom = Polygon(LineString([(-95, 41), (-95, 42), (-94, 42), (-94, 41)]))
geom = Polygon(LineString([Point(-95, 41), Point(-95, 42), Point(-94, 42), Point(-94, 41)]))
```

## Operating system

Ubuntu 22

## Shapely version and provenance

2.0 - pypi

**Comment by tlaz4** [comment]
I'm seeing this too with `Decimal` type objects being passed into `Polygon`

Looks like its related to casting the passed list into a [numpy array]([https://github.com/shapely/shapely/commit/e027985cef648c5ce07c26a06dbd986c222e107e#diff-7faa6f2d4a82c2add8f83b9b2e[…]d998c31de7a169c15a58fb8cfbc9R81](https://github.com/shapely/shapely/commit/e027985cef648c5ce07c26a06dbd986c222e107e#diff-7faa6f2d4a82c2add8f83b9b2eefc8a46a35d998c31de7a169c15a58fb8cfbc9R81)). I think any type that numpy doesn't support will raise this error.

**Comment by jorisvandenbossche** [comment]
Temporary workaround that you could use and works with both shapely <=1.8 and >= 2.0 to convert a sequence of Points to a Polygon, is to first convert it to a LinearRing:

```
Polygon(LinearRing([Point(-95, 41), Point(-95, 42), Point(-94, 42), Point(-94, 41)]))
```

**Comment by gplanansky** [comment]
Thank you for this fix. 
 It 1671 does the trick accepting either a list of tuples, a list of Points, or a list of both tuples and points.  (I didn't check with decimal objects).

This is by replacing the old polygon.py from conda-forge build below, with the one  from the pull request (less the "test" changes).

fwiw macos system specs:

$ uname -a Darwin xxxxx 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

$ conda list | grep shapely
shapely                   2.0.0           py311h24f10cc_0    conda-forge

file name   : shapely-2.0.0-py311h24f10cc_0.conda
name        : shapely
version     : 2.0.0
build       : py311h24f10cc_0
build number: 0
size        : 437 KB
license     : BSD-3-Clause
subdir      : osx-arm64
url         : https://conda.anaconda.org/conda-forge/osx-arm64/shapely-2.0.0-py311h24f10cc_0.conda
md5         : f3c05a6c71d9052b84d56a3b6a67f905
timestamp   : 2022-12-12 14:33:15 UTC
dependencies: 
  - geos >=3.11.1,<3.11.2.0a0
  - numpy >=1.23.5,<2.0a0
  - python >=3.11,<3.12.0a0
  - python >=3.11,<3.12.0a0 *_cpython
  - python_abi 3.11.* *_cp311

**Comment by jorisvandenbossche** [comment]
@gplanansky thanks for testing!

**Comment by snowman2** [comment]
Thanks @jorisvandenbossche :+1:

**Comment by idanmiara** [comment]
> Thank you for this fix. It 1671 does the trick accepting either a list of tuples, a list of Points, or a list of both tuples and Points. (I didn't check with decimal objects).

It seems that this fix doesn't help for decimal objects. Should we fix it for decimals or declare as won't fix ?
https://github.com/shapely/shapely/issues/1707
