### ISSUE TITLE
Cannot import name 'xxx' from 'shapely'

### ISSUE THREAD

**Issue by peekxc** [shapely/shapely#1666]
What am I doing wrong here at the install here?

```python
from shapely import minimum_bounding_circle
```
> ImportError                               Traceback (most recent call last)
----> 1 from shapely import minimum_bounding_circle
ImportError: cannot import name 'minimum_bounding_circle' from 'shapely' (...)

Shapely installed fine, and I have GEOS > v8.0.0.

```bash 
$ brew info geos
==> geos: stable 3.11.1 (bottled) 
...

$pip show shapely
Name: Shapely
Version: 2.0.0
...
```

I have the geometries, but many of the algorithms presumably exported form __init__.py are missing. I even checked to submodules incase the docs were wrong:

```python
import shapely
'minimum_bounding_circle' in dir(shapely)
# False 

import importlib
modules = ['affinity', 'algorithms', 'coords', 'ctypes_declarations', 'errors', 'geometry', 'geos', 'impl', 'linref', 'predicates', 'speedups', 'topology']
any(['minimum_bounding_circle' in dir(importlib.import_module("shapely."+mod_str)) for mod_str in modules])
# False 
```

I also tried down-dating to the 1.8.x version but the result was the same. Am I missing something very basic here?

## Operating system

Mac OS X 10.15.7

**Comment by jorisvandenbossche** [comment]
Can you show the result of running `import shapely; shapely.__version__` ? 
First guess is that you are actually using 1.8 for some reason.

**Comment by jorisvandenbossche** [comment]
Also, the `modules` you try to import to check if those have "minimum_bounding_circle" are the modules from 1.8. If you run that code with shapely 2.0, that should raise an error about some of those modules not being found.

**Comment by peekxc** [comment]
Ahh after digging in for about 25 minutes I found out my `geos-config` was not pointing things to the correct location(s). After re-linking a few things and forcibly re-installing `shapely` 2.0.0, it is now working...

Sorry, I'm not sure why it wasn't working before after several re-install attempts... thanks for the response though!

**Comment by jorisvandenbossche** [comment]
Good to hear it is working now!
