### ISSUE TITLE
'MultiLineString' object is not subscriptable

### ISSUE THREAD

**Issue by zhubing1996** [shapely/shapely#1675]
In shapely2.0, how do I convert MultiLineString' to LineString'？When using an index, an error is reported.The code and errors are as follows:
from shapely.geometry import LineString, Point, MultiLineString
ML_1 = MultiLineString([[[0,0],[1,1]], [[2,2],[3,3]]])
print(ML_1)
L_1 = ML_1[0]
print(L_1)
TypeError: 'MultiLineString' object is not subscriptable.

**Comment by zhubing1996** [comment]
The problem has been solved：code as follows:
from shapely.geometry import LineString, Point, MultiLineString
ML_1 = MultiLineString([[[0,0],[1,1]], [[2,2],[3,3]]])
print(ML_1)
L_1 = ML_1.geoms[0]
print(L_1)

**Comment by jorisvandenbossche** [comment]
That is indeed the solution (using `.geoms` to access the sub-parts of a Multi geometry). The upgrade guide has a section on this topic: https://shapely.readthedocs.io/en/stable/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable (and shapely 1.8 should also have suggested that in a deprecation warning)
