### ISSUE TITLE
LineString Not Returning Correct Coordinates

### ISSUE THREAD

**Issue by dmccorm2** [shapely/shapely#1677]
## Expected behavior and actual behavior.

Expected:
- LineString(10 10, 0 15) returns coordinates [10.0, 10.0] and [0.0, 15.0] for coords.xy

Actual:
- LineString(10 10, 0 15) returns coordinates [10.0, 0.0] and [0.0, 15.0] for coords.xy

## Steps to reproduce the problem.

```python
from shapely.geometry import LineString
my_line = LineString([(10, 10), (0, 15)])
print(my_line.coords.xy)
```

(For example, a script with required data)

## Operating system

macOS 13.0.1 (Apple Silicon)

## Shapely version and provenance

- 1.8.2 installed via poetry
- 1.8.5.post1 installed via poetry
- 2.0.0 installed via poetry

**Comment by jorisvandenbossche** [comment]
The documentation of the `xy` attribute says "Separate arrays of X and Y coordinate values", so the result seems correct to me?

```
>>> from shapely.geometry import LineString
>>> my_line = LineString([(10, 10), (0, 15)])
>>> print(my_line.coords.xy)
(array('d', [10.0, 0.0]), array('d', [10.0, 15.0]))
```

**Comment by mwtoews** [comment]
You can get the "expected" result with:
```python
>>> print(my_line.coords[:])
[(10.0, 10.0), (0.0, 15.0)]
```
which is a list of (x, y) tuples for each vertex.
