### ISSUE TITLE
when does polygonize_full() detect dangles?

### ISSUE THREAD

**Issue by fuxiaodi** [shapely/shapely#1691]
My shapely version is 1.8.0
I am confused about the dangles of polygonize_full(). According to documents of Shapely, dangles are edges which have one or both ends which are not incident on another edge endpoint. I want to output the dangles, but always failed. I think
 the lineString ((1, 1), (2, 2)) is a dangle, but it isn't a dangle because the output of dangle is empty.

for example:
lines= [
    ((0, 0), (1, 0)),
    ((1, 0), (1, 1)),
    ((1, 1), (0, 1)),
    ((0, 1), (0, 0)),
    ((1, 1), (2, 2)),
    ]

lines = [LineString(line) for line in lines]

result, dangles, cuts, invalids = polygonize_full(lines)

print(dangles)
GEOMETRYCOLLECTION EMPTY

print(cuts)
GEOMETRYCOLLECTION (LINESTRING (1 1, 2 2))

the Linestring ((1,1), (2, 2)) only has one end is connect the other lineString ((1, 0), (1, 1)), so it should be a dangle. However, it isn't as expected. Could you explain it? Could you list an example that can output dangles?

**Comment by fuxiaodi** [comment]
a similar question was answered in https://gis.stackexchange.com/questions/244726/when-does-shapelys-polygonize-full-detect-a-dangle, but it seems doesn't answer or explain my question

**Comment by fuxiaodi** [comment]
Who can explain the issue？

**Comment by jorisvandenbossche** [comment]
This was actually a bug in the documentation of shapely 1.8: the order of the returned values was not `result, dangles, cuts, invalids` as documented, but in practice it was `result, cuts, dangles, invalids`, so switching around `cuts` and `dangles`. 

With that, I think your reasoning matches the result? (the `cuts` (actually dangles) does show LINESTRING (1 1, 2 2))

(I seem to remember this was discussed before, but I can't directly find the issue)

**Comment by jorisvandenbossche** [comment]
Actually, the documentation is still incorrect (only in the function docstring that was merged from pygeos, this is already correct) -> fixing this in https://github.com/shapely/shapely/pull/1697

**Comment by fuxiaodi** [comment]
According to shapely 2.0.0 document, cut edges are connected at both ends but do not form part of polygon. I think it is wrong. For example:

lines = [
    ((0, 0), (1, 0)),
    ((1, 0), (1, 1)),
    ((1, 1), (0, 1)),
    ]

lines = [LineString(geom) for geom in lines]

result, dangles, cuts, invalids = polygonize_full(lines)

print(result)
GEOMETRYCOLLECTION EMPTY

print(dangles)
GEOMETRYCOLLECTION EMPTY

print(cuts)
GEOMETRYCOLLECTION (LINESTRING (1 1, 0 1), LINESTRING (1 0, 1 1), LINESTRING (0 0, 1 0))

print( invalids)
GEOMETRYCOLLECTION EMPTY

I think LINESTRING (1 0, 1 1) is cuts,  LINESTRING (1 1, 0 1) and  LINESTRING (0 0, 1 0)) are dangles. Am I right?  So the result of cuts actually include cuts and dangles.  

In my project, I need to differentiate cuts, dangles and invalid rings, so I have to differentiate cuts and dangles. For example, split  (GEOMETRYCOLLECTION (LINESTRING (1 1, 0 1), LINESTRING (1 0, 1 1), LINESTRING (0 0, 1 0))) into two parts.

part 1:  LINESTRING (1 1, 0 1) and  LINESTRING (0 0, 1 0))
part 2:  LINESTRING (1 0, 1 1

**Comment by fuxiaodi** [comment]
> Actually, the documentation is still incorrect (only in the function docstring that was merged from pygeos, this is already correct) -> fixing this in #1697

Thank you very much!

**Comment by jorisvandenbossche** [comment]
The documentation explains dangles and cuts as:

> Dangles are edges which have one or both ends which are not incident on
  another edge endpoint. Cut edges are connected at both ends but do not
  form part of polygon.

Since those example lines don't form any polygon, none of the lines are connected to a polygon, and thus are all dangles. 

And so since you have to swap `cuts` and `dangles` in your code example, I think it is correct that for this example there are only dangles (and all three other result parts are empty)
