### ISSUE TITLE
Contains issue for complex LineStrings

### ISSUE THREAD

**Issue by sgillies** [shapely/shapely#17]
Hi All,

For:
from shapely.geometry import LineString
good1 = LineString([(0,2),(0,0),(2,2)])
good2 = LineString([(2,0),(0,2),(0,0),(2,2)])
broken = LineString([(1,0),(0,2),(0,0),(2,2)])
contained = LineString([(0,0),(2,2)])
print good1.contains(contained), good2.contains(contained), broken.contains(contained)

I get:
True True False

where I would expect:
True True True

I am running: Shapely-1.2.14-py2.6.

Am I overlooking something?

Thanks for your help,
Julia

**Comment by mwtoews** [comment]
FYI, this issue has been filed further upstream with JTS: https://github.com/locationtech/jts/issues/396

**Comment by dr-jts** [comment]
This is now fixed by https://github.com/libgeos/geos/pull/937
