### ISSUE TITLE
Question about calculate min, max, avg width from multipolygons

### ISSUE THREAD

**Issue by phamkhactu** [shapely/shapely#1706]
Thanks for great repo
I want to calculate min, max, ave width from polygons:
![image](https://user-images.githubusercontent.com/42369268/210504423-eb97e7aa-3bcd-4953-b3c1-d09ea3775b74.png)
Here is my data:
```
{ "type": "Feature", "properties": { "OBJECTID": 1.0, "SHAPE_Leng": 0.00057672519222000005, "SHAPE_Area": 5.191152e-09, "name": null, "rongMax": null, "rongMin": null, "rongTB": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814052974000049, 21.009160664000035 ], [ 105.814018928000053, 21.00919353200004 ], [ 105.814021210000078, 21.009195662000025 ], [ 105.814026385000034, 21.009202952000066 ], [ 105.81405440900005, 21.009242426000071 ], [ 105.814090260000057, 21.009269388000064 ], [ 105.814124937000088, 21.009292263000077 ], [ 105.814203617000032, 21.009343118000061 ], [ 105.814214316000061, 21.009350654000059 ], [ 105.814223964000064, 21.009340076000058 ], [ 105.814170518000083, 21.009304149000059 ], [ 105.81414109900004, 21.009282088000077 ], [ 105.814117868000039, 21.009266112000034 ], [ 105.814087328000085, 21.009244852000052 ], [ 105.814074111000082, 21.009232288000078 ], [ 105.814072411000041, 21.009232829000041 ], [ 105.814058327000055, 21.009186317000058 ], [ 105.814055345000043, 21.009175664000054 ], [ 105.814052974000049, 21.009160664000035 ] ] ] ] } }

```
I am very appreciated your help! Thank you.

**Comment by idanmiara** [comment]
Hi,
I'm not sure if the minimum and average width are well defined, but as for the maximum width (and length) of the rotated envelope (rectangle) you could use the following code.
I've multipied your coords by 100,000 to make them easily read.

l=24.88 w=5.53

<img width="409" alt="image" src="https://user-images.githubusercontent.com/26349741/210545208-e506af90-c146-4432-8a4e-68ab689fc1a9.png">

```
import matplotlib.pyplot as plt
import numpy as np

import shapely
from shapely import transform
from shapely.plotting import plot_polygon
from shapely.geometry import shape

d = { "type": "Feature", "properties": { "OBJECTID": 1.0, "SHAPE_Leng": 0.00057672519222000005, "SHAPE_Area": 5.191152e-09, "name": None, "rongMax": None, "rongMin": None, "rongTB": None }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814052974000049, 21.009160664000035 ], [ 105.814018928000053, 21.00919353200004 ], [ 105.814021210000078, 21.009195662000025 ], [ 105.814026385000034, 21.009202952000066 ], [ 105.81405440900005, 21.009242426000071 ], [ 105.814090260000057, 21.009269388000064 ], [ 105.814124937000088, 21.009292263000077 ], [ 105.814203617000032, 21.009343118000061 ], [ 105.814214316000061, 21.009350654000059 ], [ 105.814223964000064, 21.009340076000058 ], [ 105.814170518000083, 21.009304149000059 ], [ 105.81414109900004, 21.009282088000077 ], [ 105.814117868000039, 21.009266112000034 ], [ 105.814087328000085, 21.009244852000052 ], [ 105.814074111000082, 21.009232288000078 ], [ 105.814072411000041, 21.009232829000041 ], [ 105.814058327000055, 21.009186317000058 ], [ 105.814055345000043, 21.009175664000054 ], [ 105.814052974000049, 21.009160664000035 ] ] ] ] } }
geom = shape(d["geometry"])

geom = transform(geom, lambda x: x * 100_000)
env = shapely.oriented_envelope(geom)
print(env)
def get_length_width(env):
    a = shapely.area(env)
    p = shapely.length(env)
    l = (p/2 + np.sqrt(p*p/4-4*a))/2
    w = p/2 - l
    lw = np.stack([l, w])
    return np.max(lw, axis=0), np.min(lw, axis=0)

l, w = get_length_width(env)
print(f'{l=} {w=}')

plot_polygon(geom)
plot_polygon(env)
plt.show()
```

**Comment by phamkhactu** [comment]
@idanmiara The minimun, I define: it is the smallest width.
It here:
![image](https://user-images.githubusercontent.com/42369268/210547382-49702f2b-7247-4c8f-805f-fa671e9548ac.png)
The avg, now I don't have any idea, but I think that, it maybe crop part to calculate maximun width and avg. 
I am very happy if you can give how to calculate minimum as I defined.
Thank you.

**Comment by idanmiara** [comment]
> @idanmiara The minimun, I define: it is the smallest width. It here: ![image](https://user-images.githubusercontent.com/42369268/210547382-49702f2b-7247-4c8f-805f-fa671e9548ac.png) The avg, now I don't have any idea, but I think that, it maybe crop part to calculate maximun width and avg. I am very happy if you can give how to calculate minimum as I defined. Thank you.

I understand your definition for this specific polygon, 
but mathematically (for a general polygon), I'm not sure how to define it.

**Comment by phamkhactu** [comment]
> > @idanmiara The minimun, I define: it is the smallest width. It here: ![image](https://user-images.githubusercontent.com/42369268/210547382-49702f2b-7247-4c8f-805f-fa671e9548ac.png) The avg, now I don't have any idea, but I think that, it maybe crop part to calculate maximun width and avg. I am very happy if you can give how to calculate minimum as I defined. Thank you.
> 
> I understand your definition for this specific polygon, but mathematically (for a general polygon), I'm not sure how to define it.

yeah, it is very difficult, I think that it is very interesting to solve.

**Comment by idanmiara** [comment]
Actually the envelope wouldn't give you the maximum width you requested either, as the width of the rotated rectangle is larger then the width of the polygon.
Is your can split the polygon into to LineStrings then it would be much easier and well defined.

**Comment by phamkhactu** [comment]
> Actually the envelope wouldn't give you the maximum width you requested either, as the width of the rotated rectangle is larger then the width of the polygon. If your can split the polygon into to LineStrings then it would be much easier and well defined - see `frechet_distance` https://en.wikipedia.org/wiki/Fr%C3%A9chet_distance#Intuitive_definition

yeah thank you. At that time, I only list polygons, don't have any info, so to split to LineStrings is imposible. But I will research more.

**Comment by phamkhactu** [comment]
@idanmiara 
Have you ever cut each block, Here I want to cut each block separately to make easy to estimate width, because the same direction not complicated will better. It means that in the polygons I wish it can cut to 3 blocks
![image](https://user-images.githubusercontent.com/42369268/210927050-b158cc89-a78b-493d-9282-74f65a78500e.png)
Here is my data:
```
d= { "type": "Feature", "properties": { "OBJECTID": 2.0, "SHAPE_Leng": 0.00080152089569199996, "SHAPE_Area": 6.738507e-09, "name": None, "rongMax": None, "rongMin": None, "rongTB": None }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814583953000067, 21.009283075000042 ], [ 105.814572207000083, 21.009266899000067 ], [ 105.814564240000038, 21.009280613000044 ], [ 105.814547423000079, 21.009315270000059 ], [ 105.814544528000056, 21.009321236000062 ], [ 105.814539977000038, 21.009332928000049 ], [ 105.814528267000071, 21.009364317000063 ], [ 105.814517977000037, 21.009380705000069 ], [ 105.814477338000074, 21.009441190000075 ], [ 105.814456895000035, 21.009472612000025 ], [ 105.814436680000085, 21.009503447000043 ], [ 105.814426456000035, 21.009517802000062 ], [ 105.814453746000083, 21.009528555000031 ], [ 105.814487338000049, 21.009543271000041 ], [ 105.814520236000078, 21.009557736000033 ], [ 105.814530002000083, 21.009541658000046 ], [ 105.814534012000081, 21.009531278000054 ], [ 105.814525585000069, 21.009525917000076 ], [ 105.814522115000045, 21.009531723000066 ], [ 105.814510791000032, 21.009529538000038 ], [ 105.814495522000072, 21.009525311000061 ], [ 105.814452333000077, 21.009514707000051 ], [ 105.814474484000073, 21.009478985000044 ], [ 105.814473510000084, 21.009478457000057 ], [ 105.814488416000074, 21.009454694000055 ], [ 105.81451368900008, 21.009416584000064 ], [ 105.814513187000045, 21.009416135000038 ], [ 105.814546513000039, 21.009370943000079 ], [ 105.814548002000038, 21.009367158000032 ], [ 105.814558761000058, 21.009341500000062 ], [ 105.814567124000064, 21.00931517600003 ], [ 105.814570857000035, 21.009303425000041 ], [ 105.814583953000067, 21.009283075000042 ] ] ] ] } }
```
Thank you.

**Comment by idanmiara** [comment]
Hi @phamkhactu ,
I think I have an algorithm to solve your initial problem:

Cut the polygon into 2 LineStrings by removing two edges (We would need to find the optimal edges to remove, let's call them A, B)
We have an upper bound for the width of the polygon (using `get_envelope_length_width`)
```
* upper_bound_w = `get_envelope_length_width(poly)`
* For each 2 non non adjacent edges A, B:
    * Make 2 LineStrings a, b by removing A, B from `poly`
    * `max_abw` = The minimal buffer size `w` that satisfies `contains(buffer(a, w), buffer(b, w))` (possibly by binary search for w in the range [0, upper_bound_w])
  * return the minimal `max_abw` from all possible A, B
after you found the optimal a, b and the maximum width `max_abw` you can do more buffers analysis on a, b for finding an `avg_abw` or `min_abw` 

![image](https://user-images.githubusercontent.com/26349741/210965212-62e59e62-6e63-4477-a071-eb542a368b3a.png)

**Comment by phamkhactu** [comment]
> Hi @phamkhactu , I think I have an algorithm to solve your initial problem:
> 
> Cut the polygon into 2 LineStrings by removing two edges (We would need to find the optimal edges to remove, let's call them A, B) We have an upper bound for the width of the polygon (using `get_envelope_length_width`)
> 
> * upper_bound_w = `get_envelope_length_width(poly)`
> * For each 2 non non adjacent edges A, B:
>   
>   * Make 2 LineStrings a, b by removing A, B from `poly`
>   * `max_abw` = The minimal buffer size `w` that satisfies `contains(buffer(a, w), b) and contains(buffer(b, w), a)` (possibly by binary search for w in the range `[0, upper_bound_w]`)
>   * return the minimal `max_abw` from all possible A, B
>     after you found the optimal a, b and the maximum width `max_abw` you can do more buffers analysis on a, b for finding an `avg_abw` or `min_abw`
> 
> edit: you might also use `frechet_distance` to find `max_abw`
> 
> ![image](https://user-images.githubusercontent.com/26349741/210965212-62e59e62-6e63-4477-a071-eb542a368b3a.png)

@idanmiara thank you. I will try to your idea.

**Comment by phamkhactu** [comment]
Hi @idanmiara 
Can I find the interaction between a line linear equal and a polygons
For example:
```
y = ax+b
polygons is gemometry:

{ "type": "Feature", "properties": { "OBJECTID": 1.0, "SHAPE_Leng": 0.00057672519222000005, "SHAPE_Area": 5.191152e-09, "name": null, "rongMax": null, "rongMin": null, "rongTB": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814052974000049, 21.009160664000035 ], [ 105.814018928000053, 21.00919353200004 ], [ 105.814021210000078, 21.009195662000025 ], [ 105.814026385000034, 21.009202952000066 ], [ 105.81405440900005, 21.009242426000071 ], [ 105.814090260000057, 21.009269388000064 ], [ 105.814124937000088, 21.009292263000077 ], [ 105.814203617000032, 21.009343118000061 ], [ 105.814214316000061, 21.009350654000059 ], [ 105.814223964000064, 21.009340076000058 ], [ 105.814170518000083, 21.009304149000059 ], [ 105.81414109900004, 21.009282088000077 ], [ 105.814117868000039, 21.009266112000034 ], [ 105.814087328000085, 21.009244852000052 ], [ 105.814074111000082, 21.009232288000078 ], [ 105.814072411000041, 21.009232829000041 ], [ 105.814058327000055, 21.009186317000058 ], [ 105.814055345000043, 21.009175664000054 ], [ 105.814052974000049, 21.009160664000035 ] ] ] ] } }


```
And I expected to get 2 points inner polygons egdes:
[x1,y1]
[x2,y2]
![image](https://user-images.githubusercontent.com/42369268/218298914-1e07af8c-f4a5-4ebd-b38e-ee8c30499097.png)

Thank you very much

**Comment by idanmiara** [comment]
> Hi @idanmiara Can I find the interaction between a line linear equal and a polygons For example:
> 
> ```
> y = ax+b

You could express your line equations collection as a MultiLineString. Each LineString would be corresponded to a line equation and would have two points: [polygon.min_x, y0], [polygon.max_x,  y1].
Then you can intersect the MultiLineString with the polygon to get the required points.

**Comment by phamkhactu** [comment]
> MultiLineString

Thanks for your guide @idanmiara 

But I have trouble with it, I can not get the point interaction between line and polygons

```
d = { "type": "Feature", "properties": { "OBJECTID": 6.0, "SHAPE_Leng": 0.0018435614763720001, "SHAPE_Area": 1.830693e-08, "name": None, "rongMax": None, "rongMin": None, "rongTB": None }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814233473000058, 21.009605263000026 ], [ 105.814270254000064, 21.009557108000024 ], [ 105.814294123000082, 21.009508220000043 ], [ 105.814310222000074, 21.00947741400006 ], [ 105.814272326000037, 21.009456668000041 ], [ 105.814212241000064, 21.009415109000031 ], [ 105.81420315400004, 21.00940840100003 ], [ 105.81417328200007, 21.009386347000031 ], [ 105.814165209000066, 21.009398109000074 ], [ 105.814144615000032, 21.009394712000073 ], [ 105.814124802000038, 21.009382587000061 ], [ 105.814117689000057, 21.009392403000049 ], [ 105.814070315000038, 21.009362398000064 ], [ 105.814035767000064, 21.00933989300006 ], [ 105.81399544900006, 21.009314226000072 ], [ 105.813992317000043, 21.00931666200006 ], [ 105.813938111000084, 21.009278877000042 ], [ 105.813956262000033, 21.009253924000063 ], [ 105.813898282000082, 21.009273615000041 ], [ 105.813906806000034, 21.009281664000071 ], [ 105.813926242000036, 21.009296736000067 ], [ 105.813930008000057, 21.009292257000027 ], [ 105.814022481000052, 21.009355528000071 ], [ 105.814091046000044, 21.009398283000053 ], [ 105.814108600000054, 21.009407042000078 ], [ 105.814147095000067, 21.009413957000049 ], [ 105.814147350000042, 21.009413089000077 ], [ 105.814174914000034, 21.009421213000053 ], [ 105.814174412000057, 21.009422525000048 ], [ 105.814199988000041, 21.009438416000023 ], [ 105.814196086000038, 21.00944436900005 ], [ 105.81427995100006, 21.009495137000044 ], [ 105.81422490500006, 21.009573164000074 ], [ 105.814231047000078, 21.009576607000042 ], [ 105.814197398000033, 21.009632903000067 ], [ 105.814200504000041, 21.009634568000024 ], [ 105.814165204000062, 21.009698650000075 ], [ 105.814130529000067, 21.009681203000071 ], [ 105.814110726000081, 21.009670929000038 ], [ 105.814077452000049, 21.00965476600004 ], [ 105.814043983000033, 21.009639770000035 ], [ 105.814037492000068, 21.009636667000052 ], [ 105.814028830000041, 21.009653373000049 ], [ 105.814056730000061, 21.009666333000041 ], [ 105.814085146000082, 21.009679532000064 ], [ 105.814120301000059, 21.009698368000045 ], [ 105.814155253000081, 21.009715444000051 ], [ 105.81417351500005, 21.009716377000075 ], [ 105.814180653000051, 21.009702379000032 ], [ 105.814231116000087, 21.009606946000076 ], [ 105.814233473000058, 21.009605263000026 ] ] ] ] } }


 geom = shape(d['geometry'])
 coord_ori = d["geometry"]['coordinates']
 coord_ori = np.array(coord_ori)
 coord_ori = np.squeeze(coord_ori)

 envelope = shapely.oriented_envelope(geom)
 polygon = Polygon(coord_ori.tolist())

 line = LineString([Point(105.81376320748112, 21.00938816591795), 
                                Point(105.81432561933852, 21.00900762440906)])
 intersection = polygon.intersects(line)
 print(intersection)
```
when I print(intersection), the result only **True** not get value points
I am very help for your help if could give some code for get value points
Many thank you

**Comment by phamkhactu** [comment]
@idanmiara sorry for that I use misunderstanding function. I get values
Thank you

**Comment by idanmiara** [comment]
@phamkhactu it looks that this is related to
https://geoobserver.wordpress.com/2023/03/30/qgis-tipp-flussbreiten-ermitteln-aber-wie-update/
