### ISSUE TITLE
Documentation for shapely.plotting

### ISSUE THREAD

**Issue by arthur-e** [shapely/shapely#1712]
Despite the use of the `plotting` module [in examples in the User Guide](https://shapely.readthedocs.io/en/stable/manual.html#linearrings), there appears to be [no API documentation](https://doi.org/10.1016/j.rse.2017.12.009) or User Guide entries devoted to `plotting` in the Shapely documentation.

**Comment by idanmiara** [comment]
Hi @arthur-e 
I think you put a wrong link for "no API documentation"

I've added plotting module doc reference: https://github.com/shapely/shapely/pull/1713

**Comment by arthur-e** [comment]
I did indeed! You can see what papers I'm reading.

I'm glad there's a PR for this. Thanks!

**Comment by martinfleis** [comment]
Given https://github.com/shapely/shapely/pull/1713 is now closed unmerged, this should probably be re-opened.

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/shapely/shapely/pull/1839 now

**Comment by bunnyhero** [comment]
I still don't see plotting documentation on https://shapely.readthedocs.io/en/stable/index.html (which shows version 2.0.6).

**Comment by theroggy** [comment]
It hasn't been released yet... if you look at the "latest" version of the documentation it is there...
https://shapely.readthedocs.io/en/latest/

**Comment by bunnyhero** [comment]
Thank you!
