### ISSUE TITLE
Possible negative side-effect: STRtree makes passed geometry array immutable

### ISSUE THREAD

**Issue by brendan-ward** [shapely/shapely#1714]
#1422 included a change to mark the passed-in geometries as non-writeable, and included a [note](https://github.com/shapely/shapely/pull/1422#discussion_r896004573) that we should probably check downstream usages.

I've been running into an issue with this lately with Shapely 2.0 / GeoPandas 0.12.2 where I create the tree on a GeoDataFrame's geometry column, then want to update the contents of that column selectively.

```python
tree = shapely.STRtree(df.geometry.values)
left, right = tree.query(...other geoms..., predicate='intersects')

# construct some new geometries, perhaps via intersection of geometries indexed by left and right

# fails now:
df.loc[...some index..., 'geometry'] = new_geoms
```

I had previously been using this pattern frequently with pygeos without issue (the non-writeable flag was added to shapely2, not present in pygeos).  In cases where I'd do the above and then need to do another spatial index operation, I'd simply recreate the tree from the latest geometries (sidestepping the immutability issue) and query again.

Deleting the tree does not reset the non-writeable flag; it probably should.

This may be an edge case, but there are a couple work-arounds we may want to mention in the docs:
- make a copy of the geometry array as input to the tree if you plan on modifying it later
- delete the tree after querying to enable modifying the geometry array again (once we reset the flag on delete)

**Comment by jorisvandenbossche** [comment]
Quick thought: specifically for the combination with geopandas, we _could_ also catch this error when you try to modify GeometryArray, and do a copy of the array there if it is read-only.

(that's of course only a possible solution _if_ you are using the pandas APIs to set new values, and not when doing that directly on the numpy array)
