### ISSUE TITLE
[Shapely 2] Failed to construct a polygon from a list of Points

### ISSUE THREAD

**Issue by jiawlu** [shapely/shapely#1724]
I got an error when constructing a polygon from a list of Points.

Example:
geometry.Polygon([geometry.Point(0,0),geometry.Point(1,1),geometry.Point(1,0)])

Mac OS 13.1, Shapely 2.0.0 installed from PyPI using pip.

The code above works with Shapely 1.8.

**Comment by jorisvandenbossche** [comment]
Indeed, this is a regression in 2.0.0, and is already fixed on the main branch (https://github.com/shapely/shapely/issues/1662). We plan to release 2.0.1 shortly that will include this.
