### ISSUE TITLE
`geom_factory` & creating Shapely objects from raw GEOS pointers in Python

### ISSUE THREAD

**Issue by kylebarron** [shapely/shapely#1747]
This is related to but distinct from https://github.com/shapely/shapely/issues/1443. I'm interested in sharing GEOS objects between Python and _Rust_ via its [GEOS crate](https://crates.io/crates/geos). Of course the standard restrictions apply about needing to link against the same GEOS library to prevent segfaults, but in application code this can be ensured and the onus is on the developer to ensure this.

I see in https://github.com/shapely/shapely/pull/1534 that `geom_factory` is intended to move into the C level for C/Cython applications that interact with shapely and GEOS independently. I'm wondering whether there's any appetite for keeping a low-level _Python_ function like `geom_factory` for instances where it's harder to bind against that Cython code, e.g. from Rust.

**Comment by jorisvandenbossche** [comment]
We could probably just keep `geom_factory` as a low-level / advanced function, if there are use cases and demand for this (and so remove the deprecation warning. 

To be clear, the reason that you prefer a _python_ function is that this ensures you can use generic rust-python bridge functionality "call this function from this module", instead of having to actually build against shapely's C or Cython API?

**Comment by kylebarron** [comment]
I read a bit more and I guess this can really be folded into #1443.

I took a look at how https://github.com/PyO3/rust-numpy works, which integrates Rust and numpy via its C-API. In essence, for each module it calls [`get_numpy_api`](https://github.com/PyO3/rust-numpy/blob/0a99920a91163b1b67c34d25ec644151d2e7c170/src/npyffi/array.rs#L51) which is equivalent to `import numpy.core.multiarray._ARRAY_API` in Python. That exposes Numpy's public C API for that module as a [`Capsule`](https://docs.python.org/3/c-api/capsule.html) object. Then on the Rust side it [implements FFI](https://github.com/PyO3/rust-numpy/blob/0a99920a91163b1b67c34d25ec644151d2e7c170/src/npyffi/array.rs#L58-L63) on the pointer from the capsule. The `Capsule` docs are pretty explanatory: 

> This subtype of [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) represents an opaque value, useful for C extension modules who need to pass an opaque value (as a void* pointer) through Python code to other C code. It is often used to make a C function pointer defined in one module available to other modules, so the regular import mechanism can be used to access C APIs defined in dynamically loaded modules.

So with a future stable Shapely C API, I'd only need for it to be exported via a capsule, and  not a python function.

**Comment by jorisvandenbossche** [comment]
> So with a future stable Shapely C API, I'd only need for it to be exported via a capsule, and not a python function.

That's already how it works now for our cython extensions, it uses a C API through capsules modelled after how numpy does it. So while this is not considered public/stable, you can certainly already experiment with it to see if that works. 

(see `src/c_api.c/h` defining it and `shapely/_pygeos.api_.pxd` using that in cython)

**Comment by kylebarron** [comment]
> So while this is not considered public/stable, you can certainly already experiment with it to see if that works.

Today is this only exposed through C/Cython or also through Python? I.e. is there a pure-python Shapely import statement I can run to access the `PyCapsule`?

**Comment by jorisvandenbossche** [comment]
Yes:

```
In [34]: import shapely

In [35]: shapely.lib._C_API
Out[35]: <capsule object "shapely.lib._C_API" at 0x7f1bd41438d0>
```

**Comment by kylebarron** [comment]
Very cool! I haven't fully figured out yet how to interact with that from Rust, but I think it's clear it's possible, so I'll close this and keep an eye on #1443!

**Comment by bretttully** [comment]
I'm probably being daft -- I haven't tried to use a capsule before, but is there an obvious reason why this call to `PyGEOS_CreateGeometry` would fail (using pybind11)

```
py::object Writer::cp(py::object shape) const {
    // Extract the function pointer to create a Shapely geometry from a GEOS geometry
    const py::object shapelyLib = py::module_::import("shapely.lib");
    const py::capsule shapelyApiCapsule = shapelyLib.attr("_C_API").cast<py::capsule>();
    auto raw_PyGEOS_CreateGeometry = reinterpret_cast<void **>(shapelyApiCapsule.ptr())[0];
    auto PyGEOS_CreateGeometry =
        reinterpret_cast<py::object (*)(GEOSGeometry *ptr, GEOSContextHandle_t ctx)>(raw_PyGEOS_CreateGeometry);
    std::cout << "cast function from capsule" << std::endl;

    std::cout << py::str(shape).cast<std::string>() << std::endl;
    auto geometry = reinterpret_cast<GEOSGeom_t *>(shape.attr("_geom").cast<size_t>());
    std::cout << GEOSGeomTypeId_r(mGeosCtx, geometry) << std::endl;

    py::object result = PyGEOS_CreateGeometry(geometry, mGeosCtx);
    std::cout << py::str(result).cast<std::string>() << std::endl;
    return result;
}
```

Gives

```
pysrc/tests/mvt/test_io.py::test_cp cast function from capsule
POINT (1 2)
0
Fatal Python error: Segmentation fault

Current thread 0x00007f64e92e2740 (most recent call first):
...
```

**Comment by bretttully** [comment]
This seems to work where the other form didn't...
```c++
using PyGEOS_CreateGeometryType = PyObject *(*)(GEOSGeometry *ptr, GEOSContextHandle_t ctx);
const auto shapelyApiCapsule = py::module_::import("shapely.lib").attr("_C_API").cast<py::capsule>();
const auto capsulePtr = (const void **)PyCapsule_GetPointer(shapelyApiCapsule.ptr(), "shapely.lib._C_API");
auto PyGEOS_CreateGeometry = reinterpret_cast<PyGEOS_CreateGeometryType>(capsulePtr[0]);
```

**Comment by jorisvandenbossche** [comment]
@bretttully I never used it in this way, so can't really help here. But your second code snippet from a quick look seems OK (and certainly if it is working ;)). 
You could also take a look at how pybind11 uses the numpy capsule (https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h)
