### ISSUE TITLE
`offset_curve` method of a linestring returns a much shorter linestring

### ISSUE THREAD

**Issue by DavideDaz** [shapely/shapely#1749]
## Expected behavior and actual behavior.

When I try to get the offset curve of a `LineString`, I would expect an offset curve with a similar dimension (length) of the original.  The result is instead a linestring composed by only two points and much shorter than the original

## Steps to reproduce the problem.

```
line = LineString(array([[-13615738.85998679,   4563056.89922692],
                         [-13615738.86000393,   4563056.89931759],
                         [-13615738.86000393,   4563056.89931759],
                         [-13615738.86026059,   4563056.90067453],
                         [-13615738.86026059,   4563056.90067453],
                         [-13615738.86136808,   4563056.90652975],
                         [-13615738.86136808,   4563056.90652975],
                         [-13615738.86433091,   4563056.92219422],
                         [-13615738.86433091,   4563056.92219422],
                         [-13615738.87052573,   4563056.95494603],
                         [-13615738.87052573,   4563056.95494603],
                         [-13615738.88167217,   4563057.01387686],
                         [-13615738.88167217,   4563057.01387686],
                         [-13615738.89979665,   4563057.10970003],
                         [-13615738.89979665,   4563057.10970003],
                         [-13615738.92718947,   4563057.25452392],
                         [-13615738.92718947,   4563057.25452392],
                         [-13615738.96635628,   4563057.46159531],
                         [-13615738.96635628,   4563057.46159531],
                         [-13615739.01996486,   4563057.74501785],
                         [-13615739.01996486,   4563057.74501785],
                         [-13615739.09078822,   4563058.11945128],
                         [-13615739.09078822,   4563058.11945128],
                         [-13615739.18164524,   4563058.59979747],
                         [-13615739.18164524,   4563058.59979747],
                         [-13615739.29533997,   4563059.20087942],
                         [-13615739.29533997,   4563059.20087942],
                         [-13615739.43460081,   4563059.93711982],
                         [-13615739.43460081,   4563059.93711982],
                         [-13615739.60202086,   4563060.8222254 ],
                         [-13615739.60202086,   4563060.8222254 ],
                         [-13615739.80000043,   4563061.86888334],
                         [-13615739.80000043,   4563061.86888334],
                         [-13615740.03069312,   4563063.0884757 ],
                         [-13615740.03069312,   4563063.0884757 ],
                         [-13615740.2959562 ,   4563064.49081751],
                         [-13615740.2959562 ,   4563064.49081751],
                         [-13615740.59730656,   4563066.08392354],
                         [-13615740.59730656,   4563066.08392354],
                         [-13615740.71857169,   4563066.72499214]]))

distance = 1.1178453260363115
offset = line.offset_curve(distance)
```

offset
_<LINESTRING (-13615739.958 4563056.692, -13615739.958 4563056.692)>_

## Shapely version and provenance

`shapely==2.0.1`

Was wondering if I am using correctly the `offset_curve` method

**Comment by jorisvandenbossche** [comment]
How did you install Shapely? And can you show the output of `shapely.geos_version`?

Using latest shapely with GEOS 3.11.1, I see expected behaviour:

```
>>> offset
<LINESTRING (-13615739.958 4563056.692, -13615739.958 4563056.692, -13615739...>
# full WKT
>>> offset.wkt
'LINESTRING (-13615739.958378633 4563056.691588936, -13615739.95838779 4563056.691637372, -13615739.958630601 4563056.692921089, -13615739.959738357 4563056.698777714, -13615739.962701673 4563056.714444755, -13615739.968896277 4563056.747195418, -13615739.980042702 4563056.806126174, -13615739.998167057 4563056.901948686, -13615740.025559746 4563057.046771879, -13615740.064726418 4563057.253842542, -13615740.11833484 4563057.537264238, -13615740.189158026 4563057.911696757, -13615740.28001485 4563058.39204191, -13615740.393709362 4563058.993122706, -13615740.532969965 4563059.729361851, -13615740.70038975 4563060.614466034, -13615740.898369038 4563061.661122489, -13615741.12906142 4563062.880713216, -13615741.394324169 4563064.283053276, -13615741.695674172 4563065.8761574095, -13615741.816938918 4563066.517223978)'
```

and plotting both the original line as the offset gives:

![plot-offset](https://user-images.githubusercontent.com/1020496/218336255-4ca74da0-a96c-4c98-9659-2414ac13d1ca.png)

**Comment by DavideDaz** [comment]
> How did you install Shapely? And can you show the output of `shapely.geos_version`?
> 
> Using latest shapely with GEOS 3.11.1, I see expected behaviour:
> 
> ```
> >>> offset
> <LINESTRING (-13615739.958 4563056.692, -13615739.958 4563056.692, -13615739...>
> # full WKT
> >>> offset.wkt
> 'LINESTRING (-13615739.958378633 4563056.691588936, -13615739.95838779 4563056.691637372, -13615739.958630601 4563056.692921089, -13615739.959738357 4563056.698777714, -13615739.962701673 4563056.714444755, -13615739.968896277 4563056.747195418, -13615739.980042702 4563056.806126174, -13615739.998167057 4563056.901948686, -13615740.025559746 4563057.046771879, -13615740.064726418 4563057.253842542, -13615740.11833484 4563057.537264238, -13615740.189158026 4563057.911696757, -13615740.28001485 4563058.39204191, -13615740.393709362 4563058.993122706, -13615740.532969965 4563059.729361851, -13615740.70038975 4563060.614466034, -13615740.898369038 4563061.661122489, -13615741.12906142 4563062.880713216, -13615741.394324169 4563064.283053276, -13615741.695674172 4563065.8761574095, -13615741.816938918 4563066.517223978)'
> ```
> 
> and plotting both the original line as the offset gives:
> 
> ![plot-offset](https://user-images.githubusercontent.com/1020496/218336255-4ca74da0-a96c-4c98-9659-2414ac13d1ca.png)

@jorisvandenbossche  Thank you for the reply. I installed it with `pip3` in a conda environment.

This is the  version of GEOS, they are the same so not sure of what I am missing:
```
>>> import shapely
>>> shapely.geos_version
(3, 11, 1)
```

**Comment by SuaveFool** [comment]
@DavideDaz I've seen similar errors with parallel_offset in the past, it is a GEOS error, as the same error tends to occur using other tools that wrap GEOS. I haven't found a consistent cause, but it tends to be prevalent when the vertices are close and the angle between them is "significant" enough. It may be worse because every vertex is duplicated in your dataset.

**Comment by jorisvandenbossche** [comment]
> I installed it with `pip3` in a conda environment.

Could you show the output of `conda list` in that conda environment?

**Comment by DavideDaz** [comment]
> @DavideDaz I've seen similar errors with parallel_offset in the past, it is a GEOS error, as the same error tends to occur using other tools that wrap GEOS. I haven't found a consistent cause, but it tends to be prevalent when the vertices are close and the angle between them is "significant" enough. It may be worse because every vertex is duplicated in your dataset.

@SuaveFool Thank you for the heads-up! I ended up re-installing and updating Shapely and now seems to work fine

**Comment by DavideDaz** [comment]
I am gonna close this issue
