### ISSUE TITLE
Shapely Buffering, not working as expected

### ISSUE THREAD

**Issue by aw-west-defra** [shapely/shapely#1753]
[SO Question](https://stackoverflow.com/questions/75100829/)  
Why does buffering one of my geometries have an unexpected hole in it?

```py
from shapely import LineString
from geopandas import GeoDataFrame

l = LineString([
  (250,447),
  (319,446),
  (325,387),
  (290,374),
  (259,378),
  (254,385),
  (240,409),
  (244,440),
  (250,447),
])

assert l.is_valid
assert l.is_simple

GeoDataFrame({'geometry': [
  l,
  l.buffer(80),
]}).plot(column='geometry')
```
![](https://i.stack.imgur.com/BIpH7.png)

- This is uncommon, and by removing a pair of coordinates it doesn't have a hole.  
- When using [Sedona's ST_Buffer](https://sedona.apache.org/1.3.1-incubating/api/sql/Function/#st_buffer) this happened in more cases.  
- My hack to avoid this is:  `tol=1e-3`, `l.buffer(tol).buffer(80-tol)`.
- [Serge's hack](https://stackoverflow.com/a/75142680/10450752) is:  `tol=1e-3`, `l.simplify(tol).buffer(80)`

**Comment by mwtoews** [comment]
This is an upstream bug: https://github.com/locationtech/jts/issues/876
