### ISSUE TITLE
BUG: unary_union on empty point and line leads to segmentation fault

### ISSUE THREAD

**Issue by EmanuelKuhn** [shapely/shapely#1769]
## Expected behavior and actual behavior.

Actual behavior (shapely 2.0.0) : unary_union on a list of linestring, empty point causes python to crash with segmentation fault.
Expected behavior: The empty point should be ignored when computing the unary_union, instead of crashing.

This issue seems related to #1230.

## Steps to reproduce the problem.

I'm not sure how to construct an empty point in shapely for the minimum example, but the following pygeos example causes the same segmentation fault:

`pygeos.union_all([pygeos.Geometry("POINT EMPTY"), pygeos.Geometry("LINESTRING(0 2, 1 4)")])`

## Operating system

Ubuntu 22.10

## Shapely version and provenance

shapely 2.0.0 (py310h8b84c32_0    conda-forge)

pygeos version used in example: pygeos 0.14 installed with pip

**Comment by brendan-ward** [comment]
I can reproduce on Shapely 2.0.1 on macOS:

Here is the Shapely version of the above; this bug must have come from PyGEOS.

```Python
shapely.union_all([shapely.from_wkt("POINT EMPTY"), shapely.from_wkt("LINESTRING(0 2, 1 4)")])
```

**Comment by brendan-ward** [comment]
This is coming from GEOS; can reproduce in GEOS 3.9 - 3.12.0dev via `geosop`.

This segfaults:
```bash
geosop unaryUnion -a "GEOMETRYCOLLECTION (POINT EMPTY, LINESTRING EMPTY)"                                                                                                                                                                                   
```

**Comment by jorisvandenbossche** [comment]
This is fixed on the GEOS side, so let's close the issue here.
