### ISSUE TITLE
Shapely needs a patch to work with conda on OS X

### ISSUE THREAD

**Issue by shoyer** [shapely/shapely#177]
I'm not 100% what the right solution is for shapely (which is why this issue is not a PR), but we needed to apply this patch to get Shapely to successfully build a [conda package](http://conda.pydata.org/docs/build.html) on OS X that uses the conda install of libgeos:
https://github.com/TheClimateCorporation/conda-recipes/blob/cd57916a02a4f97b71ca5937ee98e1499f131c73/shapely/osx-geos.patch

It would be nice to get a fix for this in Shapely. Here is a discussion with more context for this fix:
https://groups.google.com/a/continuum.io/d/msg/conda/kw2xC4wjI-Y/wDHMYeTZDeEJ

Note that in my version of the patch, I needed to change it look in `sys.prefix` _before_ the other locations, because I had another, non-conda version of geos installed (installed via brew) which shapely was linking to instead.

CC @ilanschnell @pelson @rsignell-usgs

**Comment by pelson** [comment]
For what it is worth, between v1.5.7 and master (specifically 2212deb2105d380345c9b558f8f4c3d3be903496) this is now fixed.

For my own records, to reproduce with conda for the bad versions:

```
from shapely import speedups
speedups.enable()
from shapely.geometry import LineString
LineString([(0, 0), (10, 0)]).wkt
```

Liking the new libgeos.py module! :tada:

**Comment by rhattersley** [comment]
> Maybe we should open a bug at bugs.python.org about this. I didn't see any related bugs in my searches.

Did this ever happen?

**Comment by ilanschnell** [comment]
When we build shapely for Anaconda, we always apply a patch which ensures that it is linking against `<sys.prefix>/lib/libgeos_c.dylib`.  It would be nice, if shapely would always try to look at his location for the geos library.

**Comment by MichaelCPell** [comment]
I've tried
1.  adding `"%s/lib" % sys.prefix` to the `DEFAULT_LIBRARY_FALLBACK` of my python "macholib/dyld.py"
2.  installing shapely with `conda install -c SciTools shapely`

and am still on square one.  I've also exhausted SO.  Has anyone been able to install shapely with anaconda on Mac 10.10?

My particular error shows as `ImportError: No module named geometry`

**Comment by shoyer** [comment]
@MichaelCPell Try the `ioos` and `conda-forge` channels as well. @ocefpaf has does [some impressive work](https://conda-forge.github.io/) getting conda builds of the Python geoscience stack working reliably.

**Comment by ocefpaf** [comment]
BTW go straight to `conda-forge`. (The `IOOS` channel is deprecated now.)

[Here](https://github.com/conda-forge/shapely-feedstock/blob/master/recipe/geos_c.patch) is the patch in case you want to roll your own conda solution.
