### ISSUE TITLE
Bug in shapely.buffer

### ISSUE THREAD

**Issue by laszipt** [shapely/shapely#1770]
The _**buffer points**_ calculation does not consider the location of the point on the map, so it becomes more and more elliptic as is it gets closer to the poles.

## Expected behavior and actual behavior.

It is expected to be a perfect circle around a single point.

## Steps to reproduce the problem.

```
from shapely import Point, buffer

point_on_equator = Point(-78.4556256102772,-0.002087481232010191)
circle   = point_on_equator.buffer(0.1)
#display resulted polygon in your preferred environment

point_in_alaska  = Point(-149.9941411317871,61.17072288201612)
ellipse  = point_in_alaska.buffer(0.1)
#display resulted polygon in your preferred environment
```

**Comment by brendan-ward** [comment]
`buffer` works in the same coordinate system as your points, so in your example it is `0.1` degrees around.  The circular buffer may become distorted if you reproject it into a different coordinate system (e.g., for display on a map); this is entirely expected.  See [Tissot's indicatrix](https://en.wikipedia.org/wiki/Tissot%27s_indicatrix) for visual examples of this.

Shapely is a planar geometry library and treats geographic coordinates just like any other planar coordinates; it does not create buffers based on a spheroid.

**Comment by laszipt** [comment]
Dear Ward,

Now I understand the way shapely is working, thanks to that.

Could you give me some hint on how to make a buffer on a spheroid or
project it in a different way ?


Thanks,
Tamás


Brendan Ward ***@***.***> ezt írta (időpont: 2023. febr. 24.,
P, 23:26):
