### ISSUE TITLE
the is_ccw() function on linestrings does not work properly

### ISSUE THREAD

**Issue by JohnnnyTang** [shapely/shapely#1778]
## Expected behavior and actual behavior.
I use reverse() function on a clockwise linestring, but the is_ccw() output of the result is still false with the coords of this linestring already being reversed.
For the context, I am processing a list of linestrings to make them all be counter clockwise.
## Steps to reproduce the problem.
```
line = LineString([[662943.696520151, 3548352.11490796], [662906.352600756, 3548348.78963826], [662877.079080498, 3548348.6653055], [662856.807823284, 3548349.57212594], [662817.303968036, 3548352.57796384]])
if is_ccw(line):
    newLine = line
else:
    newLine = line.reverse()
    print(is_ccw(newLine), newLine)
```
The 'line' above is originally a clockwise linestring, but 'newLine' generated by 'line.reverse()' still outputs 'False' in the is_ccw() function with its coords already being reversed.

## Shapely version and provenance
shapely 2.0.1 installed from conda

**Comment by martinfleis** [comment]
LineString is by definition a non-closed series of coordinates. The shape can be anything, it can be formed of a cw and ccw spirals linked together or any other configuration you can think of. Assessment of clock-wise and counter-clock-wise order for an object like that is not possible. Even though shapely does return something, the value is conceptually undefinable, so it makes no sense to use `is_ccw` on a LineString. That is why you see no difference when calling `reverse`.

**Comment by JohnnnyTang** [comment]
> LineString is by definition a non-closed series of coordinates. The shape can be anything, it can be formed of a cw and ccw spirals linked together or any other configuration you can think of. Assessment of clock-wise and counter-clock-wise order for an object like that is not possible. Even though shapely does return something, the value is conceptually undefinable, so it makes no sense to use `is_ccw` on a LineString. That is why you see no difference when calling `reverse`.
Thank you for clearing up my confusion! I confused this with the clockwise determination of three points. Really helped me a lot! Still got so much to learn.

**Comment by JohnnnyTang** [comment]
@jorisvandenbossche Thank you for noticing me this. Now I have a better understanding of this problem.
