### ISSUE TITLE
Custom Class can not inherit from Linestring class

### ISSUE THREAD

**Issue by altairgomes** [shapely/shapely#1779]
Shapely is not allowing a user class to inherit from it.

In version 1.8 I could create a class that inherits from LineString and add custom methods.
Since version 2.0, it always returns a LineString instead of my class.

## Steps to reproduce the problem.

This is just a simple class that should inherit from LineString with custom methods.

```python
import shapely.geometry as geometry
import matplotlib.pyplot as plt

class Limb(geometry.LineString):

    def plot(ax=None, **kwargs):
        ax = ax or plt.gca()
        ax.plot(*self.xy, **kwargs)
```

With shapely 1.8, I had this result and everything worked.
```python
limb = Limb([[0,1], [2,3], [4,5]])
type(limb)
## Limb
limb.plot(color='red')
```

With shapely 2.0.1, I get
```python
limb = Limb([[0,1], [2,3], [4,5]])
type(limb)
## shapely.geometry.linestring.LineString
limb.plot(color='red')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [40], in <cell line: 1>()
----> 1 limb.plot(color='red')

AttributeError: 'LineString' object has no attribute 'plot'
```

## Operating system

Ubuntu 22.4.2

## Shapely version and provenance

shapely 2.0.1 installed via pip

**Comment by tfardet** [comment]
Duplicate of #1233
See [this post](https://github.com/shapely/shapely/issues/1233#issuecomment-977837620) for a workaround.

**Comment by altairgomes** [comment]
Thanks. I'll close this issue and follow the suggestions.
