### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'segmentize'

### ISSUE THREAD

**Issue by jo-caulkins** [shapely/shapely#1800]
## Please note

I've encountered an error with LineString not having one of its built-in methods that I haven't run into before. I can't add the whole file because of privacy restrictions, but I've added the relevant block. The problem arose when I ran the same code in a new environment - specifically IDLE instead of Anaconda.

## Expected behavior and actual behavior.

Expected:
ls.segmentize working as stated in documentation, and in previous runs of the same code

Actual:
Traceback (most recent call last):
  File "C:\Users\jcaulkins\OneDrive\Documents\Python Scripts\Heatmap.py", line 206, in <module>
    findXY(slice_can_rail, can_rail_ps)
  File "C:\Users\jcaulkins\OneDrive\Documents\Python Scripts\Heatmap.py", line 189, in findXY
    linestringXY(geom.iloc[i], ps)
  File "C:\Users\jcaulkins\OneDrive\Documents\Python Scripts\Heatmap.py", line 156, in linestringXY
    myls = ls.segmentize(cell_size)
AttributeError: 'LineString' object has no attribute 'segmentize'

## Steps to reproduce the problem.
cellsize = 1000 #1 km

def linestringXY(ls, ps): #takes a LineString and list of (x,y) pairs
        myls = ls.segmentize(cell_size)
        coords = myls.coords
        ps = ps + coords

ls = LINESTRING (680643.7002899743 5329923.425448324, 683076.1819335185 5331910.825356613, 683542.4297277217 5333073.758056914, 683561.7730310401 5334065.741513717, 683348.3673427784 5335351.641466941, 682297.2181790022 5338404.134562917, 682133.3531082505 5340018.836596682, 683010.0753335394 5343722.548524387, 682973.2205643875 5345683.7627762025, 682770.8135523737 5346618.583432958, 682457.5684049097 5348062.624595362, 682790.2777787676 5349155.904663486, 682458.7721474887 5353379.490903853, 682160.1802561897 5354401.414384722) #print output not constructor input

segmentize(ls, []) 

## Operating system

Windows 11

## Shapely version and provenance

Shapely 1.8.2 installed using pip

Others:
geopandas 0.12.2
geoplot 0.5.1
cartopy 0.20.2
fiona 1.9.1
pyproj 3.3.1
packaging 23.0
rtree 1.0.1
numpy 1.24.2

all installed using pip

**Comment by mwtoews** [comment]
You will need to ensure that shapely>=2 and GEOS>=3.10 is installed for this feature to work. It seems that you are using an older version of shapely, so this error is expected.

**Comment by jorisvandenbossche** [comment]
Maybe we should add some "versionadded" notes in method/attribute docstrings?

Closing the issue since the error is expected.
