### ISSUE TITLE
geometry.mapping doesn't work for empty Point object

### ISSUE THREAD

**Issue by NoharaMasato** [shapely/shapely#1807]
## Expected behavior and actual behavior.
Expected behavior:
```bash
>>> from shapely import geometry
>>> geometry.mapping(geometry.Point())
{'type': 'Point', 'coordinates': ()}
```
Actual behavior:
```bash
>>> from shapely import geometry
>>> geometry.mapping(geometry.Point())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/3.8.13/lib/python3.8/site-packages/shapely/geometry/geo.py", line 136, in mapping
    return ob.__geo_interface__
  File "~/.pyenv/versions/3.8.13/lib/python3.8/site-packages/shapely/geometry/point.py", line 105, in __geo_interface__
    return {"type": "Point", "coordinates": self.coords[0]}
  File "~/.pyenv/versions/3.8.13/lib/python3.8/site-packages/shapely/coords.py", line 34, in __getitem__
    raise IndexError("index out of range")
IndexError: index out of range
```
We can use `geometry.mapping` function for empty features other than Point, i.e. `geometry.mapping(geometry.Polygon())`, `geometry.mapping(geometry.LineString())`. Point feature also should behave in the same way.

## Steps to reproduce the problem.
```python
from shapely import geometry
print(geometry.mapping(geometry.Polygon())) # success
print(geometry.mapping(geometry.LineString())) # success
print(geometry.mapping(geometry.MultiPoint())) # success
print(geometry.mapping(geometry.Point())) # fail
```

## Operating system

Ubuntu 20.04.6 LTS (Focal Fossa)

## Shapely version and provenance

2.0.1 installed from PyPI using pip
python 3.8.13

**Comment by mwtoews** [comment]
There doesn't seem to be a GeoJSON equivalent for `POINT EMPTY` (e.g. [here](https://lists.geojson.org/pipermail/geojson-geojson.org/2011-June/thread.html)). Two alternatives of expected behavior:

    {'type': 'Point', 'coordinates': None}
    {'type': 'Point', 'coordinates': (nan, nan)}

I don't have a strong opinion on which representation is "more correct".

**Comment by NoharaMasato** [comment]
Thank you @mwtoews for the reply.
- Other geometry type like Polygon, LineString behaves like below.
  ```python
  >>> geometry.mapping(geometry.Polygon())
  {'type': 'Polygon', 'coordinates': ()}
  >>> geometry.mapping(geometry.LineString())
  {'type': 'LineString', 'coordinates': ()}
  ```
- All the representations including your suggestions work for `geometry.shape` method.
  ```python
  >>> geometry.shape({'type': 'Point', 'coordinates': ()})
  <shapely.geometry.point.Point object at 0x7fd0d1becf70>
  >>> geometry.shape({'type': 'Point', 'coordinates': None})
  <shapely.geometry.point.Point object at 0x7fd0d1becf70>
  >>> geometry.shape({'type': 'Point', 'coordinates': (None, None)})
  <shapely.geometry.point.Point object at 0x7fd0d1becf70>
  ```
- RFC 7946 says that `GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects.` ([here](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2:~:text=GeoJSON%20processors%20MAY%20interpret%20Geometry%20objects%20with%0A%20%20%20%20%20%20empty%20%22coordinates%22%20arrays%20as%20null%20objects.))

Considering all the above points, I think `geometry.shape({'type': 'Point', 'coordinates': None})` is the best representation to follow the RFC, but in order to do that, we need to modify the representation of all the geometry types.

**Comment by Oreilles** [comment]
GEOS decided against `None`, and choose the empty array.
```py
>>> shapely.from_geojson(json.dumps({'type': 'Point', 'coordinates':[] }))
<POINT EMPTY>

>>> shapely.from_geojson(json.dumps({'type': 'Point', 'coordinates': None }))
[...]
shapely.errors.GEOSException: ParseException: Error parsing JSON: '[json.exception.type_error.302] type must be array, but is null'
```

For the sake of consistency and to avoid round-trip errors, the better bet is probably to follow that rule.

**Comment by jorisvandenbossche** [comment]
FWIW, I checked with GDAL and in contrast to GEOS, they do use `null` but for the entire geometry, not just for the coordinates ..

```python
geometries = geopandas.GeoSeries.from_wkt(["POINT EMPTY", "POLYGON EMPTY"])
df = geopandas.GeoDataFrame({"col": [1, 2], "geometry": geometries})
df.to_file("test_point_empty.geojson")
```

gives

```
{
"type": "FeatureCollection",
"name": "test_point_empty",
"features": [
{ "type": "Feature", "properties": { "col": 1 }, "geometry": null },
{ "type": "Feature", "properties": { "col": 2 }, "geometry": { "type": "Polygon", "coordinates": [ ] } }
]
}
```

That's not really something we can mimic for `mapping` though (it also looses the type information about being a Point)

**Comment by sgillies** [comment]
GeoJSON spec author here! We had no idea how confusing this would be for implementers. It may be worth updating the spec.

My interpretation of https://datatracker.ietf.org/doc/html/rfc7946#section-3.1 is that `{"type": "Point", "coordinates": []}` is the most correct.

**Comment by jorisvandenbossche** [comment]
Thanks for the confirmation, Sean! 

The PR https://github.com/shapely/shapely/pull/2120 is taking that option.
