### ISSUE TITLE
polylabel runs into infinite loop with tiny polygon

### ISSUE THREAD

**Issue by ch-koehler** [shapely/shapely#1836]
## Expected behavior and actual behavior.

**Expected:**
 `shapely.ops.polylabel` should not crash my machine! 

**Actual:**
`shapely.ops.polylabel` runs into an infinite loop, until the system runs out of memory, in rare cases with topologically questionable, but technically valid polygons.

## Steps to reproduce the problem.

```py
from shapely import wkt
from shapely.ops import polylabel


wkt_string = (
    "POLYGON ((536520.0679737709 5438764.374763639, 536520.0679737704 5438764.374763602, "
    "536520.0679737709 5438764.374763642, 536520.0679737709 5438764.374763639))"
)

polygon = wkt.loads(wkt_string)

# careful, this will eventually eat up your memory, if not interrupted manually!
polylabel(polygon)
```

I've tracked the problem down to this loop: https://github.com/shapely/shapely/blob/6cbae5d984060047d15b1b22e6ed9d912872508f/shapely/algorithms/polylabel.py#L110-L117

where in `y += cell_size` the tiny `cell_size` of `4.656612873077393e-10` is being added to the rather large `y` coordinate of `5438764.374763602`, causing the cell_size to loose its significance. Therefore, `y == y + cell_size` and `y` will never grow to the size of `maxy`.

## Operating system

Ubuntu 22.04.2 LTS based docker container `jupyter/base-notebook:notebook-6.5.3`.

## Shapely version and provenance
 2.0.1 installed from conda-forge, but also reproducible with 1.8.5 from PyPi

**Comment by jorisvandenbossche** [comment]
I verified that this will be closed by https://github.com/shapely/shapely/pull/1307 (which replaces our custom python implementation with a GEOS function).

(should add a test with this example to that PR)
