### ISSUE TITLE
Centroid of invalid MultiPolygon is defined and not within coverage of shape

### ISSUE THREAD

**Issue by philvarner** [shapely/shapely#1845]
## Expected behavior and actual behavior.

The centroid of an invalid MultiPolygon is defined, but is not within the coverage of the shape. I would expect the centroid to be undefined (None) for an invalid geometry.

## Steps to reproduce the problem.

My use case is calculating the centroid of antimeridian-spanning images. I split the antimeridian-spanning Polygon into a MultiPolygon and get the centroid of this shape. Initially, I did not realize that my initial Polygon was invalid according to the is_valid method because of a line along the antimeridian (self-intersection). If the geometry is not valid, I would not expect a centroid value to be available -- I would expect it to be None, as it has no meaning in the context of an invalid geometry. 

The shape looks like:

<img width="358" alt="image" src="https://github.com/shapely/shapely/assets/124996/bbf81e48-16fa-411e-9716-6f552ffd9c2f">

In my case, the centroid value and what i would expect for the centroid are shown below:

<img width="516" alt="image" src="https://github.com/shapely/shapely/assets/124996/c64bfab3-e33a-4cf0-8704-cbb85760dbb1">

The code to do this computation is:

```
import shapely


geometry = {
  "type": "MultiPolygon",
  "coordinates": [
    [
      [
        [
          180.0,
          66.6956303
        ],
        [
          180.0,
          66.685634
        ],
        [
          178.474107,
          66.653756
        ],
        [
          178.64650700000004,
          65.67165
        ],
        [
          180.0,
          65.699713
        ],
        [
          180.0,
          65.7104459
        ],
        [
          180.0,
          66.6956303
        ]
      ]
    ],
    [
      [
        [
          180.0,
          65.7104459
        ],
        [
          181.03381,
          65.721148
        ],
        [
          180.9557,
          66.7056
        ],
        [
          180.0,
          66.6956303
        ],
        [
          180.0,
          65.7104459
        ]
      ]
    ]
  ]
}

sg = shapely.geometry.shape(geometry)

print(f"centroid: {sg.centroid}")
print(f"convex hull: {sg.convex_hull}")
print(f"convex hull centroid: {sg.convex_hull.centroid}")
```

And gives output:

```
centroid: POINT (176.56071936504603 66.15570510691623)
convex hull: POLYGON ((178.64650700000004 65.67165, 178.474107 66.653756, 180 66.6956303, 180.9557 66.7056, 181.03381 65.721148, 180 65.699713, 178.64650700000004 65.67165))
convex hull centroid: POINT (179.77737369779035 66.19375407103354)
```

## Operating system

MacOS 13.x

## Shapely version and provenance

shapely 2.0.1
geos 3.11.1

**Comment by caspervdw** [comment]
Hi @gadomski, thanks for your report and sorry for the late response.

> I would expect the centroid to be undefined (None) for an invalid geometry.

I understand why you expect this, but GEOS (and also shapely) has the policy to “fail in exciting ways” on invalid geometries. This is for performance reasons: we don’t check preemptively on geometry validity. The only guarantee you get is that it doesn’t crash your interpreter; the returned could be anything.

So if you are unsure about the validity of your geometry, please check it explicitly!

**Comment by philvarner** [comment]
I love that policy. Now that we know this, we're checking the validity and correcting it before getting the centroid, and that has worked fine. Thanks!
