### ISSUE TITLE
Wrong distance for 3D points

### ISSUE THREAD

**Issue by Redcof** [shapely/shapely#1848]
I am getting an issue while calculating the distance between two 3D points using `distance( )` function. The function is returning a wrong value.

## Expected behavior and actual behavior.

The `distance=0` when it should be `distance=175`.

## Steps to reproduce the problem.
```
point_a = shapely.geometry.Point(577, 58, 241)
point_b = shapely.geometry.Point(577, 58, 416)
distance = point_a.distance(point_b)
```

## Operating system

Windows 10 Enterprise

## Shapely version and provenance

1.7.1

**Comment by idanmiara** [comment]
As far as I know, GEOS (and thus, also Shapely) only take into account the 2D coordinates in calculations, and ignore `Z` dimension.
I didn't find any info about this in the docs, but as you can see in the implementation, only XY are taken into account:
https://github.com/libgeos/geos/blob/main/src/algorithm/Distance.cpp

**Comment by mwtoews** [comment]
The [manual](https://shapely.readthedocs.io/en/stable/manual.html#geometric-objects) mentions in a few places that most operations are 2D plannar, and Z coordinates are usually ignored. Look [here](https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy) for good ideas to implement this yourself.

**Comment by Redcof** [comment]
@idanmiara thanks for the confirmation.

@mwtoews thanks for sharing this. I already have implemented it 😊
