### ISSUE TITLE
Shapely 2.0.2 micro release?

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#1852]
A micro release from `maint-2.0` could help resolve upstream GEOS 3.12 changes, e.g., see https://github.com/conda-forge/shapely-feedstock/pull/125

However, I suggest the binary wheels stick to GEOS 3.11.x. <s>I'll create a PR to bump the release to use [GEOS 3.11.2](https://github.com/libgeos/geos/releases/tag/3.11.2).</s> (not needed, it already is set to 3.11.2).

Here are the other pending changes: https://github.com/shapely/shapely/compare/2.0.1...maint-2.0

**Comment by mwtoews** [comment]
Pretty much the only blocking issue is #1670 which currently fail the test suite with the latest release of GEOS 3.12.0

Is #1708 suitable for inclusion for `maint-2.0` / shapely 2.0.2?

**Comment by musicinmybrain** [comment]
> Pretty much the only blocking issue is #1670 which currently fail the test suite with the latest release of GEOS 3.12.0

This matches what I see when I try packaging a snapshot of the `maint-2.0` branch, currently at eeb51ad4d80c902d5f0bcad209687f046019cb6e, for Fedora Rawhide. The only remaining test failures I see are:

```
=========================== short test summary info ============================
FAILED tests/test_constructive.py::test_oriented_envelope[geometry0-expected0]
FAILED tests/test_constructive.py::test_oriented_envelope[geometry2-expected2]
FAILED tests/test_constructive.py::test_minimum_rotated_rectangle[geometry0-expected0]
FAILED tests/test_constructive.py::test_minimum_rotated_rectangle[geometry2-expected2]
============ 4 failed, 3462 passed, 27 skipped, 3 xfailed in 6.65s =============
```

**Comment by jorisvandenbossche** [comment]
I have a PR with a (final?) set of backports: https://github.com/shapely/shapely/pull/1904 (the eq regression, cython 3 fix, and linux aarch64 wheels update)

Then I will also make a PR with updating the release date etc.

**Comment by jorisvandenbossche** [comment]
cc @shapely/shapely-team

**Comment by caspervdw** [comment]
I am :+1: on doing the release after #1904 is in.

**Comment by jorisvandenbossche** [comment]
I would like to include https://github.com/shapely/shapely/pull/1708 (the minimum_rotated_rectangle change) as well, given that this fixes a change in 2.0.x compared to 1.8

**Comment by jorisvandenbossche** [comment]
I am planning to release this evening, after merging https://github.com/shapely/shapely/pull/1708

**Comment by jorisvandenbossche** [comment]
Released!

-> https://github.com/shapely/shapely/releases/tag/2.0.2 
-> https://pypi.org/project/shapely/#files

**Comment by jorisvandenbossche** [comment]
The stable docs confusingly show a version of "0", that's caused by a "bug" (well, at least a change) in readthedocs -> https://github.com/readthedocs/readthedocs.org/issues/10715. But adding workaround in https://github.com/shapely/shapely/pull/1914
