### ISSUE TITLE
DOC: Enable pull request builds for documentation?

### ISSUE THREAD

**Issue by theroggy** [shapely/shapely#1857]
I would like to make some contributions to the shapely documentation... 

However, it would be a bit more convenient to do so if the builds for pull requests were activated. Would that be possible?

![image](https://github.com/shapely/shapely/assets/1565789/c2546a6e-a3fa-40eb-96c6-2b8bb70780b4)

**Comment by mwtoews** [comment]
Almost done. @sgillies will need to address and error shown [here](https://readthedocs.org/projects/shapely/builds/):
> Could not send GitHub build status report for shapely. Make sure you have the correct GitHub repository permissions and your [GitHub account](https://readthedocs.org/accounts/social/connections/) is connected to Read the Docs.

**Comment by mwtoews** [comment]
The PR builds are working fine, but they still don't appear in GitHub's list of checks. However, I don't know exactly where the magic button is.

**Comment by theroggy** [comment]
It indeed isn't showing yet integrated in the pull request yet.

The following step in the [troubleshooter](https://docs.readthedocs.io/en/stable/guides/pull-requests.html) solved it for me in for another project:

> ### Build status is not being reported to your Git provider
> If opening a pull request does start a new build, but the build status is not being updated with your Git provider, then your  connected account may have out dated or insufficient permisisons.

> Make sure that you have granted access to the Read the Docs [OAuth App](https://github.com/settings/applications) for your personal or organization GitHub account. You can also try reconnecting your account with your Git provider.

The project in my case wasn't granted access to readthedocs via Oauth.

**Comment by sgillies** [comment]
I've created a new webhook in the shapely settings and on RTD I can see a successful ping from GitHub.

**Comment by theroggy** [comment]
Tried creating a new pull request... but the readthedocs build still doesn't show up, so there still needs to be some bump in the wire somewhere :-(...
https://github.com/shapely/shapely/pull/1864

**Comment by sgillies** [comment]
@theroggy I see the build at https://readthedocs.org/projects/shapely/builds/ and at https://shapely--1864.org.readthedocs.build/en/1864/reference/shapely.intersects.html, but GitHub is not showing this as a PR check. I've enabled the RTD app for the shapely organization, so hopefully on your next push we'll see it in the list of PR checks.

**Comment by theroggy** [comment]
Bingo! In my latest pull request the readthedocs build is shown as a check: #1865

Thanks!
