### ISSUE TITLE
Hausdorff distance calculation does not give correct answer for flat planar rectangular poly and planar rectangular poly slanted into 3D space

### ISSUE THREAD

**Issue by fixermark** [shapely/shapely#1869]
## Expected behavior and actual behavior.

Calculation of Hausdorff distance from a flat plane at z=0 to a slanted plane with one edge in z=0 and the other in z=2 is 0, should be 2.
```
  / z = 2
 /
/
--- z = 0
```
## Steps to reproduce the problem.

```Python
import shapely
flat_plane=shapely.polygons([[0,0,0],[2,0,0],[2,1,0],[0,1,0]])
slant_plane = shapely.polygons([[0,0,0],[2,0,2],[2,1,2],[0,1,0]])
print(flat_plane.hausdorff_distance(slant_plane))
```

Result: `0.0`
Expected: `2.0`

## Operating system

Ubuntu 20.04.6 LTS

## Shapely version and provenance

2.0.1, via `pip install shapely`

**Comment by mwtoews** [comment]
Shapely (and GEOS, JTS) does not support full 3D operations like distance. Most of these operations are in 2D.

The two geometries in the issue are the same in 2D:
```python
assert shapely.force_2d(flat_plane).wkt == shapely.force_2d(slant_plane).wkt
```
If you need full 3D operations, you might find something with CGAL, e.g. [here](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPDistance)

**Comment by fixermark** [comment]
That makes sense, but it was not obvious from the documentation AFAICT, and the API allows for operating on objects with 3D coordinates and yields the wrong answer instead of raising an exception.

If 3D operations aren't expected to work, should we be throwing an exception for (polygon-polygon) operations with geometries in 3 dimensions? Alternatively (if we're worried about performance in having to check every call to avoid an exceptional case), should we add documentation to the function or elsewhere that the library will silently return incorrect values if fed polygons with 3D points?
