### ISSUE TITLE
contains_properly for PreparedGeometry does not accept array_like inputs.

### ISSUE THREAD

**Issue by JuriaanSioux** [shapely/shapely#1875]
## Expected behavior and actual behavior.

For a prepared geometry, the contains_properly does not accept array_like inputs. This in contrast to all other methods.

This is related to the custom logic with STRtree for contains_properly that does take into account the fact that 'other' can be array-like.

## Steps to reproduce the problem.

```python
from shapely import Polygon
from shapely.prepared import prep

poly = Polygon(((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)))

prep(poly).contains_properly(poly)         # this is ok, returns False

# this is not ok, raises: TypeError: Array should be one dimensional
# but you would expect it to return array([False])
prep(poly).contains_properly([poly]) 

# for example, the following returns array([True]) as you would expect
prep(poly).contains([poly])
```

## Tentative fix

I can make a pull-request to fix this issue if you want, but I am a bit hazy on where to add a test to catch this behavior. It seems like most tests for the prepared geometry have ended up in the legacy folder, and I am assuming we shouldn't be adding stuff there.

The fix would look something like this for the PreparedGeometry method:

```python
def contains_properly(self, other):
    """Returns True if the geometry properly contains the other, else False"""
    # TODO temporary hack until shapely exposes contains properly as predicate function
    from shapely import STRtree
    import numpy as np
    
    is_scalar = np.ndim(other) == 0
    other = np.atleast_1d(other)
    tree = STRtree(other)
    idx = tree.query(self.context, predicate="contains_properly")

    if is_scalar:
        return bool(len(idx))

    output = np.zeros_like(other, dtype=bool)
    output[idx] = True
    return output
```

## Operating system

Linux mint 21.2

## Shapely version and provenance

Shapely 2.0.1 on Python 3.10 installed via pip.

**Comment by jorisvandenbossche** [comment]
@JuriaanSioux Thanks for the issue report and PR. Your PR is a good fix, but I also wanted to point out on this issue that you actually no longer need to use this separate PreparedGeometry object created through `shapely.prepare.prep`. 

Starting with shapely 2.0, you can prepare normal Geometry objects "inplace". Using your example `poly` from above:

```
In [29]:  poly = Polygon(((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)))

In [30]: poly
Out[30]: <POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))>

In [31]: shapely.is_prepared(poly)
Out[31]: False

In [32]: shapely.prepare(poly)

In [33]: shapely.is_prepared(poly)
Out[33]: True

In [34]: poly.contains_properly([poly])
Out[34]: array([False])
```

And this then actually also directly works with arrays of geometries, not only with scalar geometry objects (like the `shapely.prepare` module).

At some point we need to start deprecating `shapely.prepare` (maybe we should do that for 2.1)
