### ISSUE TITLE
simplify does not remove colinear edges. 

### ISSUE THREAD

**Issue by JerryLingjieMei** [shapely/shapely#1891]
## Expected behavior and actual behavior.

Expected colinear edges to be dissolved after calling `simplify`, but after calling simplify, the three vertices (y=3.5) are still present. When the polygon is normalized prior to `simplify`, the points are dissolved as expected. There should be a bug in Pygeos that forgets to consider effects on the first and last elements of the coordinate string. 

## Steps to reproduce the problem.

```python
from shapely import Polygon, simplify

s =Polygon([(18.5, 3.5),(15.5, 3.5),(15.5, 0.0),(20.0, 0.0),(19.286758931477863, 3.5),(18.5, 3.5)])
simplify(s,1e-3)
# output: <POLYGON ((18.5 3.5, 15.5 3.5, 15.5 0, 20 0, 19.287 3.5, 18.5 3.5))>
simplify(s.normalize(),1e-3)
# output: <POLYGON ((15.5 0, 15.5 3.5, 19.287 3.5, 20 0, 15.5 0))>
```

## Operating system

Mac OS X 13.4.1

## Shapely version and provenance

2.0.1, pip

**Comment by caspervdw** [comment]
Hi @JerryLingjieMei , thanks for your question. The implementation of `simplify` is however not in shapely, but it GEOS. Can you raise your issue there? https://github.com/libgeos/geos

**Comment by JerryLingjieMei** [comment]
I did not explicitly install pygeos but internally shapely is trying to call pygeos 3.8.0. Probably sometime between 3.8 and 3.12 the issue is fixed.

**Comment by caspervdw** [comment]
In that case the issue is solved by upgrading GEOS. Thanks for the report though!
