### ISSUE TITLE
parallel_offset adding points on extremities

### ISSUE THREAD

**Issue by MatthieuMillequant** [shapely/shapely#1894]
## Expected behavior and actual behavior.

In some situations, the result of parallel_offset (or offset_curve) contains spurious points. A previous issue (https://github.com/shapely/shapely/issues/690) treated this kind of problem. The case listed in the issue works fine.

## Steps to reproduce the problem.

First a simple case reproducing the issue :

![simple_case](https://github.com/shapely/shapely/assets/77113162/c8fdcc20-3dd2-47b7-9acc-814dfb3ba716)
```
    from shapely import LineString, plotting
    import matplotlib.pyplot as plt

    base = LineString([[-1.17, 6.12],
                       [4.4, 5],
                       [-1.17, 3.88],
                       ])  # in black
    b = 6
    offset1 = base.parallel_offset(b, 'left', join_style=1)
    offset2 = base.parallel_offset(b, 'right', join_style=1)

    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 10))

    plotting.plot_line(base, ax=ax1, color='black', label='base')
    plotting.plot_line(base, ax=ax2, color='black', label='base')
    plotting.plot_line(offset1, ax=ax1, color='blue', label='left')
    plotting.plot_line(offset2, ax=ax2, color='red', label='right')
    ax1.set_aspect("equal")
    ax2.set_aspect("equal")
    ax1.legend()
    ax2.legend()
    plt.show()
```

When the offset direction is left, a buggy additional point appears at both extremities. It is not at the requested distance from the original linestring.
When the direction is right, the result should be empty.

In the second case, the result of the parallel_offset is compared to the result of the buffer method.

![buffer_case](https://github.com/shapely/shapely/assets/77113162/32c11d94-8991-419c-9e00-4223ebfb7829)

```
    from shapely import LineString, plotting
    import matplotlib.pyplot as plt

    base = LineString([[-2.1, -1],
                       [-3, 0],
                       [-5, 2],
                       [-3, 4],
                       [-2, 2],
                       [-2, 7],
                       [-1, 5],
                       [3, 8],
                       [6, 5],
                       [2, 5],
                       [4, 3],
                       [2, 3],
                       [4, 1],
                       [6, 3],
                       ])  # in black
    b = 4
    offset = base.parallel_offset(b, 'left', join_style=1)

    offset2 = base.parallel_offset(b, 'right', join_style=1)

    offset3 = base.buffer(b)

    f, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(10, 10))

    plotting.plot_line(base, ax=ax1, color='black', label='base')
    plotting.plot_line(base, ax=ax2, color='black', label='base')
    plotting.plot_line(base, ax=ax3, color='black', label='base')
    plotting.plot_line(base, ax=ax4, color='black', label='base')

    plotting.plot_line(offset, ax=ax1, color='blue', label='left')
    plotting.plot_line(offset, ax=ax3, color='blue', label='left')
    plotting.plot_line(offset, ax=ax4, color='blue', label='left')

    plotting.plot_line(offset2, ax=ax2, color='red', label='right')
    plotting.plot_line(offset2, ax=ax3, color='red', label='right')
    plotting.plot_line(offset2, ax=ax4, color='red', label='right')

    plotting.plot_polygon(offset3, ax=ax4, color='orange', label='buffer')

    ax1.set_title("left side only")
    ax2.set_title("right side only")
    ax3.set_title("both sides together")
    ax4.set_title("with buffer results")
    for ax in [ax1, ax2, ax3, ax4]:
        ax.set_aspect("equal")
        ax.legend()
    plt.show()
```

The sections of the result of parallel_offset that are not on the ring produced by the buffer method are unexpected.

## Operating system

Ubuntu 22.04.1

## Shapely version and provenance

happens with shapely installed with pypi or conda-forge, in version 2.0.1 of shapely

**Comment by caspervdw** [comment]
This is definitely an upstream issue. Can you report it at https://github.com/libgeos/geos and also report your `shapely.geos_version`?

**Comment by jorisvandenbossche** [comment]
There have been some fixes recently to offset curves o the GEOS side, and when running the above example with the latest GEOS 3.12 (the wheels still contain 3.11), I get correct results I think:

![Figure_1-1](https://github.com/shapely/shapely/assets/1020496/cbae884d-6d04-4348-bbca-dbf8ffb29c49)

![Figure_1-2](https://github.com/shapely/shapely/assets/1020496/8a3cd840-6706-4f18-bcf2-5f23c3457103)

**Comment by MatthieuMillequant** [comment]
Hi, 

sorry for the delay in response. I do not know the geos_version I used to have when the bug occured. Today, the shapely.geos_version return (3, 12, 0), and I have the same results as the comment above, which seems correct.

Thanks
