### ISSUE TITLE
shapely crashes on mac with "abort" on very large floats

### ISSUE THREAD

**Issue by RichardBowenGM** [shapely/shapely#1903]
## Expected behavior and actual behavior.

If passed a very large float, `shapely` should maintain that representation, change to infinity, raise an exception, etc. Instead, I am getting a hard crash

## Steps to reproduce the problem.

Here is a minimalized example:
```python
import shapely
p = shapely.Point(1e+279, 0)
print(p)
```

On my Mac:

```shell
python shapely_thing.py
zsh: abort      poetry run python shapely_thing.py
```
## Operating system

Mac OS X 13.4.1

## Shapely version and provenance

```python
>>> shapely.__version__
'2.0.1'
```

Installed from `PyPI` using `poetry`

## Other notes

1) It appears that the constructor runs fine (commenting out `print(p)` gets rid of the error)
2) If I replace `1e+279` with `np.inf` it also works fine (returns a point with Infinity as one of the coordinates)
3) If I replace `1e+279` with `1e+278` it works fine.
4) it works okay on linux (Ubuntu 20.04.4 LTS), the print statement gives this:

```shell
POINT POINT (1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0)```

**Comment by jorisvandenbossche** [comment]
Thanks for the report! I can actually reproduce this on Linux (Ubuntu) as well

> It appears that the constructor runs fine (commenting out print(p) gets rid of the error)

Given this, I assume this is a GEOS issue in the WKT representation. Could you do a report at https://github.com/libgeos/geos/issues?

One way to reproduce this with the GEOS command line:

```
$ geosop -a "POINT (1e+27 0)" -f wkt
POINT (1000000000000000000000000000 0)
$ geosop -a "POINT (1e+279 0)" -f wkt
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

**Comment by caspervdw** [comment]
We do have the policy of "covering up" GEOS crashes in shapely, if possible. Any ideas how we could do that here?

**Comment by jorisvandenbossche** [comment]
If we know the threshold for the coordinate value that triggers it, we could in theory check for that before calling the WKT routine? But then we have to check all the coordinates of a potentially large geometry..
