### ISSUE TITLE
make_valid deletes CRS in GeoSeries

### ISSUE THREAD

**Issue by jnclelland** [shapely/shapely#1922]
## Expected behavior and actual behavior.

Suppose that I have a GeoSeries called "test_gs" that includes a CRS.  Applying make_valid via

test_gs_valid = make_valid(test_gs)

results in a GeoSeries with no CRS.

## Steps to reproduce the problem.

test_gs = GeoSeries([Polygon([(0,0), (1,0), (1,1), (0,1)]), Polygon([(1,0), (2,0), (2,1), (1,1)])], crs = 2232)
print(test_gs.crs)
test_gs_valid = make_valid(test_gs)
print(test_gs_valid.crs)

## Operating system

Mac OS X 10.15.1

## Shapely version and provenance

2.0.1 installed from PyPI using pip

**Comment by caspervdw** [comment]
I can't reproduce this with `shapely.get_srid` / `shapely.set_srid`. So probably it is a Geopandas issue, not a Shapely issue.
Please raise the issue at https://github.com/geopandas/geopandas/issues

If you can make a minimal working example using `shapely` only, please reopen this!
