### ISSUE TITLE
Hausdorff distance behaving differently with LinearRing

### ISSUE THREAD

**Issue by MatthieuMillequant** [shapely/shapely#1934]
## Expected behavior and actual behavior.

I successively use LineString, LinearRing and Polygon to describe two simple geometries (two squares, one included in the other) and compute the hausdorff distance. The result with LineString and polygon and identical and have the expected value (the distance from the corner of one square to the closest corner), but the result with LinearRing objects is very different (it seems to be the distance from one corner to the furthest corner of the other square). 

I could not find an existing issue listing this behaviour

## Steps to reproduce the problem.

Here is the script to reproduce the issue
```python
import shapely
a = shapely.LineString([[0, 0], [0, 10], [10, 10], [10, 0], [0, 0]])
b = shapely.LineString([[1, 1], [1, 9], [9, 9], [9, 1], [1, 1]])

hd = shapely.hausdorff_distance(a, b)
print(f'LineString result {hd=}')

a = shapely.LinearRing(a)
b = shapely.LinearRing(b)

hd = shapely.hausdorff_distance(a, b)
print(f'LinearRing result {hd=}')

a = shapely.Polygon(a)
b = shapely.Polygon(b)

hd = shapely.hausdorff_distance(a, b)
print(f'Polygon result {hd=}')
```

## Operating system

Ubuntu 22.04.1

## Shapely version and provenance

It happens with shapely 2.0.2 and geos 3.11.2  installed with pip
or with shapely 2.0.2 and geos 3.12.0  installed with conda

**Comment by mwtoews** [comment]
Fixed confirmed with shapely-2.0.5
