### ISSUE TITLE
Wheel that is compatible with numpy 2.0.dev ? 

### ISSUE THREAD

**Issue by pllim** [shapely/shapely#1949]
Hi. My package requires another package that pulls in this package. I am unable to test my package using numpy 2.0.dev because of this:

```
glue/core/data_factories/helpers.py:30: in <module>
    from glue.core.component import CoordinateComponent
glue/core/component.py:5: in <module>
    import shapely
shapely/__init__.py:1: in <module>
    from shapely.lib import GEOSException  # NOQA
E   ImportError: numpy.core.multiarray failed to import
```

Are you able to provide a dev wheel that is built with numpy 2.0.dev from https://anaconda.org/scientific-python-nightly-wheels/numpy ?

Also see:

* https://github.com/numpy/numpy/issues/24300

xref https://github.com/spacetelescope/jdaviz/pull/2572 and https://github.com/glue-viz/glue/issues/2469

**Comment by jorisvandenbossche** [comment]
@pllim sorry for the slow reply! 
At the moment, we haven't set up nightly wheels that are available on a pypi index like https://anaconda.org/scientific-python-nightly-wheels/numpy (I did now ask for access (https://github.com/scientific-python/upload-nightly-action/issues/63), but cannot say anything about a timeline to get that up and running)

The main branch is building its wheels now with numpy 2.0, though, so if you download the necessary artifacts manually from https://github.com/shapely/shapely/actions/runs/7871806219 (the release workflow for currently the last commit on main), this should now work. 
(of course, I know for automated testing that is not ideal, but at least it should already allow to use such wheel locally)

**Comment by jorisvandenbossche** [comment]
See also the overview issue I opened a while ago at https://github.com/shapely/shapely/issues/1972. Will close this one in favor of that (and add a TODO to upload nightly wheels there)

**Comment by pllim** [comment]
Thank you for your response and links! Good luck!

**Comment by jorisvandenbossche** [comment]
For future reference if people end up finding this issue: we now have nightly wheels uploaded to the Scientific Python index, so you can pip install nightly wheels, see https://github.com/shapely/shapely/pull/1999 for the installation instructions that are being added to the docs.
