### ISSUE TITLE
set_precision() changes order of coordinates

### ISSUE THREAD

**Issue by DOSull** [shapely/shapely#1952]
`shapely.set_precision()` as reported in issue #1950 has side-effects. Here's another one. The position of points in the coordinate sequence of a polygon is altered.
```
p1 = shapely.geometry.Polygon([(0, 0), (0, 1), (1, 1), (1, 0)])
p2 = shapely.set_precision(p1, 1e-3)
p1, p2
```
This gives us
```
(<POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))>, <POLYGON ((0 1, 1 1, 1 0, 0 0, 0 1))>)
```
The polygon `p1` is clockwise, as is `p2` but they start at different coordinates in the sequence!

As for the previous issue this isn't a bug _per se_ but it's poorly documented, and... well... it's an unexpected side-effect of simply setting the precision.

**Comment by theroggy** [comment]
Same remarks as here: https://github.com/shapely/shapely/issues/1950#issuecomment-1865934344
