### ISSUE TITLE
Using the shapely library (buffer function)in three dimensions

### ISSUE THREAD

**Issue by zahrakheyrollahi** [shapely/shapely#1966]
I want to expand 3D data uniformly with a fixed radius. I went with the shapely library and the output appeared like this. It seems that it is not expanded in the z dimension. What should I do? Necessary
my code:
`from shapely import wkt
from shapely.geometry import Polygon
class WktFileConfig():
    def __init__(self):
        self.size=0.1
        self.file_input="D:\\programing\\python\\wkt show\\code\\2.wkt"
        self.file_output="D:\\programing\\python\\wkt show\\code\\output.wkt"
    def wktfileConfig(self):
        # Read WKT file
        self.size=float(input("Enter size : \n"))
        with open(self.file_input, 'r') as file:
            wkt_str = file.read()
        # Convert WKT to Shapely geometry
        geometry = wkt.loads(wkt_str)
        # Buffer the geometry (increase its size)
        buffered_geometry = geometry.buffer(self.size)  # Adjust the buffer size as needed
        # Write buffered geometry to a new WKT file
        with open(self.file_output, 'w') as file:
            file.write(buffered_geometry.wkt.replace("POLYGON","MULTILINESTRING"))
        print(" Create file wkt output")

app=WktFileConfig()
app.wktfileConfig()`
![IMG_20240116_162711_803](https://github.com/shapely/shapely/assets/147084302/98e59712-bf02-467d-a0c8-d0c5597a483c)
![IMG_20240116_162707_372](https://github.com/shapely/shapely/assets/147084302/fef7eb44-5f97-43c2-9438-e594d9c1c01f)
@mwtoews 
@jorisvandenbossche 
@sgillies

**Comment by sgillies** [comment]
@zahrakheyrollahi Shapely isn't a 3D library. We've got an FAQ entry about this: https://github.com/shapely/shapely/blob/main/FAQ.rst#i-used-buffer-on-a-geometry-with-z-coordinates-where-did-the-z-coordinates-go.

**Comment by zahrakheyrollahi** [comment]
> @zahrakheyrollahi Shapely isn't a 3D library. We've got an FAQ entry about this: https://github.com/shapely/shapely/blob/main/FAQ.rst#i-used-buffer-on-a-geometry-with-z-coordinates-where-did-the-z-coordinates-go.

Thanks, isn't there a 3D library that does the same thing as the shapely library?

**Comment by sgillies** [comment]
@zahrakheyrollahi I don't know what to recommend for that.
