### ISSUE TITLE
Compatibility with NumPy 2.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1972]
NumPy 2.0 is coming soon, and we should ensure shapely is fully compatible to ensure a smooth transition of our users. Overview issue on numpy's side: 

* https://github.com/numpy/numpy/issues/24300

Quick summary of the most important aspects for us:

- NumPy 2.0 as a major release changes the C ABI, so any package that builds against the NumPy C API like shapely will have to be rebuilt with numpy 2.0 to be able to run with numpy 2.0. That also means that our current released packages (built with older versions of numpy) will break (fail to import) with numpy 2.0, and so we should ideally add a `numpy<2` pin.  
  This happens at the moment when installing shapely from a wheel in an environment with numpy nightly.  
* Since numpy 1.25, we don't need `oldest-supported-numpy` anymore (https://numpy.org/devdocs/release/1.25.0-notes.html#compiling-against-the-numpy-c-api-is-now-backwards-compatible-by-default and https://github.com/scipy/oldest-supported-numpy#deprecation-notice-for-numpy-20), so for newer Python versions (where the minimum supported version of numpy is <=1.25), we can start compiling with the latest numpy.  
  This also helps with the point above, because once numpy 2.0 is released, we can therefore _built_ against numpy 2.0 and have a resulting wheel that can _run_ with both numpy 1.x and 2.0. See https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice for more details.
* Additionally to C ABI changes, there are also a whole set of changes in the Python API, and so we should test with numpy nightly to ensure we are compatible on that front.

We don't yet test with numpy nightly 

A to do list based on my current understanding:

- [x] Start testing with numpy nightly (we currently only use `--pre` in the dev build, so we only get a dev numpy when they do a beta or RC release). This will ensure that shapely at least builds and runs fine with the upcoming numpy. -> https://github.com/shapely/shapely/pull/1973
- [x] We should ideally do another release of shapely that adds a `numpy<2` pin, so that when numpy 2.0 is out and someone does `pip install shapely`, you don't get a broken env. Therefore, for the maintenance 2.0.x branch:
  - [x] Add a `numpy<2` pin to the requirements in the maintenance branch -> https://github.com/shapely/shapely/pull/1975
  - [x] Make another 2.0.x release  
- [x] For the main development branch, we don't need a runtime pin but we need to update the build dependencies for packaging:
  - [x] Update the build-system `requires` to use latest numpy instead of `oldest-supported-numpy` -> https://github.com/shapely/shapely/pull/1974
  - [x] Upload nightly wheels when possible (depending on https://github.com/scientific-python/upload-nightly-action/issues/63)
- [x] Address `copy` changes in `(as)array`  and `__array__` 
  - [x] https://github.com/shapely/shapely/pull/2007
  - [x] Update `__array__` to accept a copy keyword: https://github.com/shapely/shapely/pull/2053

**Comment by djhoese** [comment]
I don't see it mentioned above, but a recent change in numpy 2 seems to be that Cython modules (or anything using the numpy C API) must call `np.import_array()` at the top of the module. I have CI that installs shapely from github main and it now fails (used to pass with older numpy 2 nightly wheels) because of this upstream change in numpy 2.

**Comment by jorisvandenbossche** [comment]
@djhoese do you have a link to the CI in question? (failing build)

**Comment by djhoese** [comment]
@jorisvandenbossche Here you go: https://github.com/pytroll/pyresample/actions/runs/7906385079/job/21581090150

```
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
```

**Comment by jorisvandenbossche** [comment]
The problem is that `pip` by default will create an isolated build environment, and at that point it still installs numpy 1.x in that build environment. 

So one option is to change the line for shapely at https://github.com/pytroll/pyresample/blob/df92fb921f9116a819c21d75d8e6dba291622e4b/.github/workflows/ci.yaml#L66 to be `pip install --no-deps --no-build-isolation git+https://github.com/shapely/shapely`

Then that should ensure that shapely is built against the numpy 2.0 nightly you installed just before.

Another option is to figure out how to ensure pip will also install nightly packages from the extra index during the build isolation, but that I don't know exactly what that would look like.

**Comment by djhoese** [comment]
@jorisvandenbossche Thanks. What's sad is I actually knew I need `--no-build-isolation` as I've used it in another project for this same exact purpose, but thought I had already done it in pyresample. Tests are done yet, but I'm sure this will fix it. Thanks.

**Comment by jorisvandenbossche** [comment]
I am planning to do a 2.0.4 release next week to have wheels compatible with numpy 2.0

**Comment by jorisvandenbossche** [comment]
> I am planning to do a 2.0.4 release next week to have wheels compatible with numpy 2.0

This is done in the meantime: https://github.com/shapely/shapely/releases/tag/2.0.4

**Comment by mwtoews** [comment]
Refer to [NumPy docs for downstream package authors](https://numpy.org/devdocs/dev/depending_on_numpy.html#for-downstream-package-authors).

The [NumPy 2.0-specific advice](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice) suggests that for Python>=3.9 wheels, these should be built against numpy>=2.0. These wheels should also be tested with numpy==1.23.5 to check backwards compatibility with numpy 1.x.

**Comment by jorisvandenbossche** [comment]
I think everything has been done here, so closing this issue.

**Comment by Danferno** [comment]
I think the requirements file should be updated from 
`"shapely >= 2.0.0"` to `"shapely >= 2.0.4"` as that is [the first version to supply numpy 2.0 wheels](https://github.com/shapely/shapely/releases/tag/2.0.4). I am currently receiving a Numpy 2.0 related error with shapely 2.0.1 installed

```
Exception has occurred: ImportError
numpy.core.multiarray failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

  File "f:\datatog\code\backend\410-groupstructure\410-groupstructure-parser.py", line 69, in run
    import geopandas as gpd
  File "c:\virtualenvs\datatog-venv\Lib\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries
  File "c:\virtualenvs\datatog-venv\Lib\site-packages\geopandas\geoseries.py", line 13, in <module>
    import shapely
  File "c:\virtualenvs\datatog-venv\Lib\site-packages\shapely\__init__.py", line 17, in <module>
    from .lib import GEOSException  # NOQA
AttributeError: _ARRAY_API not found
```

Manually upgrading shapely to the latest version (2.1.0) fixed this for me.

**Comment by Danferno** [comment]
Ah, sorry then please ignore my remark. I installed 2.0.2 a while back and upgraded numpy (manually) sometime after and then got this issue, but if I understand correctly then there's indeed nothing you can about that scenario at this point.

To anyone finding this thread after getting `AttributeError: _ARRAY_API not found`, the solution is to upgrade shapely to 2.0.4 or higher.
