### ISSUE TITLE
shapely.geometry.LineString.intersects disregards z-value

### ISSUE THREAD

**Issue by pearlshel** [shapely/shapely#1979]
## Expected behavior and actual behavior.

Given two non-intersecting 3d LineString objects `L1` and `L2`, `L1.intersects(L2)` should return False. Currently, the method returns True, however.

## Steps to reproduce the problem.

```python
from shapely import geometry

L1 = geometry.LineString([[0,0,0], [0,5,0]])
L2 = geometry.LineString([[0,0,5], [0,5,5]])

L1.intersects(L2)
```

## Operating system

Windows 11 Pro Version	10.0.22621 Build 22621

## Shapely version and provenance

2.0.2 installed from pip 23.3.2

**Comment by mwtoews** [comment]
These geometries intersect in 2D, so this is the expected result. Spatial predicate functions are based on [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) which operates in 2D. I.e. `L1.relate(L2)` is `1FFF0FFF2` meaning the two are considered equal.

If you need 3D intersection then you'd need to seek out an alternative library.
