### ISSUE TITLE
Bug: Same shapely version different python build resturns different MULTIPOINT object

### ISSUE THREAD

**Issue by ncclementi** [shapely/shapely#1992]
I'm not sure if this goes here or in the feedstock but happy to reopen elsewhere if needed. 

I have two environments where `shapely 2.0.2` is installed but in one case is py310 and other py311. The result for multipoint in one case has extra a parentheses.
1. 
```
shapely                   2.0.2           py310hee2b506_1    conda-forge
```
```python
In [1]: import shapely

In [2]: shp_point_0 = shapely.Point(0, 0)
   ...: shp_point_1 = shapely.Point(1, 1)
   ...: shp_point_2 = shapely.Point(2, 2)

In [3]: shp_multipoint_0 = shapely.MultiPoint([shp_point_0, shp_point_1, shp_point_2])

In [4]: shp_multipoint_0
Out[4]: <MULTIPOINT ((0 0), (1 1), (2 2))>

In [5]: shapely.geos_version
Out[5]: (3, 12, 1)
```

2. 
```
shapely                   2.0.2           py311h4826c84_0    conda-forge
```

```python
In [1]: import shapely

In [2]: shp_point_0 = shapely.Point(0, 0)
   ...: shp_point_1 = shapely.Point(1, 1)
   ...: shp_point_2 = shapely.Point(2, 2)

In [3]: shp_multipoint_0 = shapely.MultiPoint([shp_point_0, shp_point_1, shp_point_2])

In [4]: shp_multipoint_0
Out[4]: <MULTIPOINT (0 0, 1 1, 2 2)>

In [5]:  shapely.geos_version
Out[5]: (3, 11, 2)
```

I noticed that the geos version is different, maybe that's the problem. But this is a problem when having snapshot tests like we have in ibis that compare outputs generated with a snapshot that looks like this

```sql
SELECT
  ST_ASWKB("result") AS result
FROM (
  SELECT
    ST_GEOMFROMTEXT('MULTIPOINT (0 0, 1 1, 2 2)') AS "result"
)
```

For the record, if you install with pip in both cases with py310 and py311, you end up with `shapely.geos_version`
`(3, 11, 2)` and `<MULTIPOINT (0 0, 1 1, 2 2)>`

cc: @jorisvandenbossche

**Comment by martinfleis** [comment]
That is a change in GEOS 3.12 (https://github.com/libgeos/geos/pull/903) which is actually a bug fix as the old format was not compliant with the WKT specification.

**Comment by ncclementi** [comment]
Thanks @martinfleis 
Closing this! We have made the corresponding xfails in ibis ci, until the fixes make it to pypi.

**Comment by jorisvandenbossche** [comment]
> I have two environments where `shapely 2.0.2` is installed but in one case is py310 and other py311.

FWIW, for conda, if you update shapely (to get a more recent build, but same version) you can have GEOS 3.12 in both your environments. For pip it will have to wait until shapely 2.1 to update GEOS to 3.12.

**Comment by jorisvandenbossche** [comment]
And something else: I don't know the exact testing context in ibis, but you could also parse the WKT with shapely and then use the `equals` method of the resulting geometries. That might be more robust than WKT string comparison (and will for example not fail on the difference above). Also if the order of coordinates in a polygon ring is different, WKT comparisons will fail while the geometries could actually be equal)

**Comment by ncclementi** [comment]
@jorisvandenbossche just for an estimate do we know when 2.1 is expected to go out?
