### ISSUE TITLE
Intersection between rectangle and far away Line returns a Line

### ISSUE THREAD

**Issue by dorianherle** [shapely/shapely#2000]
I was expecting to return None or a an empty PolygonSet, but I am getting a LineString 
```
from shapely.geometry import Polygon, LineString

# Define a rectangle polygon
rectangle = Polygon([(0, 0), (0, 2), (2, 2), (2, 0)])

# Define a line far away from the rectangle
line = LineString([(3, 3), (4, 4)])

# Attempt to find the intersection
intersection = rectangle.intersection(line)

# Check the type and representation of the intersection
intersection_type = type(intersection)
intersection_repr = repr(intersection)
```

intersection_type, intersection_repr
Result
(shapely.geometry.linestring.LineString,
 '<shapely.geometry.linestring.LineString object at 0x7ec2a7b24900>')

**Comment by jorisvandenbossche** [comment]
It's indeed a LineString and not a Polygon, but it _is_ an empty linestring:

```
>>> rectangle.intersection(line)
<LINESTRING EMPTY>
```

I am not sure how GEOS decide what type of empty geometry to return, but in general the return value of an intersection operation can be any type.

**Comment by dorianherle** [comment]
Awesome! Thank you for this insight!
