### ISSUE TITLE
TODO: fix WKT for empty M and ZM geometries

### ISSUE THREAD

**Issue by mwtoews** [shapely/shapely#2004]
On shapely `main` with #1808 to enable M and ZM in WKT outputs, one "TODO" item needs to be resolved for `test_repr_point_m_empty`. To demonstrate the issue:
```python
import shapely

assert shapely.geos_version[0:2] >= (3, 12), shapely.geos_version_string

empty_wkt = ["POINT Z EMPTY", "POINT M EMPTY", "POINT ZM EMPTY"]
empties = shapely.from_wkt(empty_wkt)

# This is one issue with repr
repr(empties)
# array([<POINT Z EMPTY>, <POINT Z EMPTY>, <POINT Z EMPTY>], dtype=object)
# but expected same as input wkt

# Another curious related issue
shapely.to_wkt(empties)
# array(['POINT Z EMPTY', None, None], dtype=object)

# But these really are different geometries
shapely.has_z(empties)
# array([ True, False,  True])
```

This is a shapely issue, and not with GEOS (3.12+). See `wkt_empty_3d_geometry` in `src/geos.c` for a possible resolution. Probably also rename away from "3D" too, since the third dimension is not always Z.

**Comment by jorisvandenbossche** [comment]
> See `wkt_empty_3d_geometry` in `src/geos.c` for a possible resolution.

Should we just skip using that helper in case of GEOS 3.12+? Assuming that GEOS can now handle those cases correctly? (AFAIK that helper was added to correct some issues on the GEOS side, but it was also added in a time we didn't consider M values, so it's not surprising that it doesn't work correctly)

**Comment by mwtoews** [comment]
Agree on skipping helper for GEOS 3.12+. I have a PR ready after #2012 is merged.
