### ISSUE TITLE
`voronoi_diagram` does not mantain order between input points and output polygons

### ISSUE THREAD

**Issue by carlosg-m** [shapely/shapely#2020]
Shapely's Voronoi does not keep order and this forces the user to perform a spatial join to recover original mapping between input points and output polygons.
```
p = np.array([[1,1],[2,4],[0,3],[5,2],[3,3],[2,2],[-2,2],[-1.5,-0.5],[2,-1]])

p_point = shapely.points(p)
p_geo = shapely.MultiPoint(p)

v = shapely.ops.voronoi_diagram(p_geo)
v = np.array(v.geoms)

p_order, v_order = shapely.STRtree(v).query(p_point, predicate='intersects')

print(p_order)
print(v_order)
#[0 1 2 3 4 5 6 7 8]
#[1 6 4 7 8 5 0 3 2]
```

**Comment by martinfleis** [comment]
In shapely 2.1, there will be a keyword allowing you to control the order. See https://github.com/shapely/shapely/pull/1968

**Comment by carlosg-m** [comment]
> In shapely 2.1, there will be a keyword allowing you to control the order. See #1968

Perfect :)

**Comment by quentinblampey** [comment]
Hello @martinfleis,
Thanks for adding the keyword to control the order, it will be very useful for some of my use cases!
Do you have a rough idea of when `shapely==2.1.0` might be released?

**Comment by martinfleis** [comment]
@quentinblampey afaik there's no date set, just a generic agreement that we should do that soon. However, there's some work that needs to be done before that and very little time people can allocate to shapely these days.

**Comment by quentinblampey** [comment]
Okay @martinfleis, thanks for letting me know, I'll wait patiently then!
