### ISSUE TITLE
Release timeline for v2.1?

### ISSUE THREAD

**Issue by andersonaddo** [shapely/shapely#2065]
I'm seeing from the v2.1 docs that v2.1 adds in some new functionality for make_valid, which I need. 

<img width="820" alt="image" src="https://github.com/shapely/shapely/assets/34724755/4de840fb-410d-46c3-bedf-a63368eca404">

When do you think 2.1 will be available via Pip?

I don't mean to add any pressure, just curious!

**Comment by mwtoews** [comment]
Great question! Quick answer is that a release timeline for 2.1 has not been established.

Here's the [link to the 2.1 milestone](https://github.com/shapely/shapely/milestone/52).

**Comment by andersonaddo** [comment]
Got it, thanks!

**Comment by jorisvandenbossche** [comment]
Forgot that this issue existed, but so created a new one to track and plan the 2.1.0 release: https://github.com/shapely/shapely/issues/2144 
I hope we can release in one of the coming weeks.
