### ISSUE TITLE
NumPy 2.0: minimum_rotated_rectangle / affine_transform failing on MacOS 14

### ISSUE THREAD

**Issue by astrofrog** [shapely/shapely#2066]
## Expected behavior and actual behavior.

The following currently fails with Numpy 2.0 (released yesterday) and shapely 2.0.4:

```
In [18]: from shapely.geometry import MultiPoint

In [19]: import numpy as np

In [20]: xp = np.frombuffer(b'\xb3\x03b\xffN!3\xc0\xcb\x92\x87\x89\xfe\xde4@\x04d\x85\xa0|\x1a5@&ww\x99E\xe52\xc0')

In [21]: yp = np.frombuffer(b'\xe1y\x97b\x82\xb6+\xc0\x92\xce\xf0W\\L,\xc0\x14\x14h\xaap\xac/@\xfa\x8e\xbaY\xf7*0@')

In [22]: mp = MultiPoint(list(zip(xp, yp, strict=True)))

In [23]: mp.minimum_rotated_rectangle
---------------------------------------------------------------------------
GEOSException                             Traceback (most recent call last)
Cell In[23], line 1
----> 1 mp.minimum_rotated_rectangle

File ~/python/dev/lib/python3.11/site-packages/shapely/geometry/base.py:428, in BaseGeometry.minimum_rotated_rectangle(self)
    416 @property
    417 def minimum_rotated_rectangle(self):
    418     """
    419     Returns the oriented envelope (minimum rotated rectangle) that
    420     encloses the geometry.
   (...)
    426     Alias of `oriented_envelope`.
    427     """
--> 428     return shapely.oriented_envelope(self)

File ~/python/dev/lib/python3.11/site-packages/shapely/constructive.py:1034, in oriented_envelope(geometry, **kwargs)
   1032 else:
   1033     f = _oriented_envelope_geos
-> 1034 return f(geometry, **kwargs)

File ~/python/dev/lib/python3.11/site-packages/shapely/algorithms/_oriented_envelope.py:52, in _oriented_envelope_min_area(geometry, **kwargs)
     49         yield (transf_rect, (ux, vx, uy, vy, 0, 0))
     51 # check for the minimum area rectangle and return it
---> 52 transf_rect, inv_matrix = min(_transformed_rects(), key=lambda r: r[0].area)
     53 return affine_transform(transf_rect, inv_matrix)

File ~/python/dev/lib/python3.11/site-packages/shapely/algorithms/_oriented_envelope.py:46, in _oriented_envelope_min_area.<locals>._transformed_rects()
     42 vx, vy = -uy, ux
     43 # transform hull from the original coordinate system to
     44 # the coordinate system defined by the edge and compute
     45 # the axes-parallel bounding rectangle.
---> 46 transf_rect = affine_transform(hull, (ux, uy, vx, vy, 0, 0)).envelope
     47 # yield the transformed rectangle and a matrix to
     48 # transform it back to the original coordinate system.
     49 yield (transf_rect, (ux, vx, uy, vy, 0, 0))

File ~/python/dev/lib/python3.11/site-packages/shapely/affinity.py:74, in affine_transform(geom, matrix)
     71 def _affine_coords(coords):
     72     return np.matmul(A, coords.T).T + off
---> 74 return shapely.transform(geom, _affine_coords, include_z=ndim == 3)

File ~/python/dev/lib/python3.11/site-packages/shapely/coordinates.py:65, in transform(geometry, transformation, include_z)
     59 if new_coordinates.shape != coordinates.shape:
     60     # if the shape is too small we will get a segfault
     61     raise ValueError(
     62         "The provided transformation returned an array with an unexpected "
     63         f"shape ({new_coordinates.shape})"
     64     )
---> 65 geometry_arr = lib.set_coordinates(geometry_arr, new_coordinates)
     66 if geometry_arr.ndim == 0 and not isinstance(geometry, np.ndarray):
     67     return geometry_arr.item()

GEOSException: IllegalArgumentException: Points of LinearRing do not form a closed linestring
```

I have to use those particular array values for the error to happen, hence the ``frombuffer`` calls. For convenience:

```
In [24]: xp
Out[24]: array([-19.13011166,  20.87107143,  21.10346416, -18.89559325])

In [25]: yp
Out[25]: array([-13.85646351, -14.14914203,  15.83679707,  16.16783677])
```

If I downgrade to Numpy 1.26.4 I don't get any error:

```
In [6]: mp.minimum_rotated_rectangle
Out[6]: <POLYGON ((20.871 -14.169, 21.105 15.855, -18.896 16.168, -19.13 -13.856, 20...>
```

What could be causing this?

## Operating system

MacOS 14.1.1

## Shapely version and provenance

Shapely was installed from PyPI using pip.

**Comment by jorisvandenbossche** [comment]
Using the packages from conda, this seems to work fine (on Linux):

```
In [5]: shapely.__version__
Out[5]: '2.0.4'

In [6]: np.__version__
Out[6]: '2.0.0'

In [7]:  mp.minimum_rotated_rectangle
Out[7]: <POLYGON ((-19.13 -13.856, -18.896 16.168, 21.105 15.855, 20.871 -14.169, -1...>
```

**Comment by jorisvandenbossche** [comment]
Also in a fresh env with shapely and numpy installed from PyPI, it works for me.

**Comment by astrofrog** [comment]
This only happens on MacOS with Silicone chips on my side by the way, I also don't see the issue on Linux or Windows.

**Comment by astrofrog** [comment]
I see this issue both on my laptop and also in CI on GitHub actions: https://github.com/astropy/reproject/actions/runs/9545693803/job/26307012551?pr=450

**Comment by jorisvandenbossche** [comment]
The functionality that is raising the error here is using `np.matmul`. I wonder if this might be affected by which implementation is being used for the matrix multiplication ..

In the release notes, I see:

> macOS Accelerate support and binary wheels for macOS >=14, with significant performance improvements for linear algebra operations on macOS, and wheels that are about 3 times smaller

Maybe that could be tested by manually installing the .._11_0_arm64.whl ?

And @astrofrog thanks for the report!

**Comment by Mec-iS** [comment]
maybe this is related:
```
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```
when try to run `orient(geom)`  and `force_2d(geom)` on a `GeoDataFrame` column:
```
gdf.geometry = gdf.geometry.apply(orient)
gdf.geometry = gdf.geometry.apply(force_2d)
```
With these versions:
```
shapely==2.0.4
geopandas==0.14.3
```
using the current official image by OSGEO `osgeo/gdal:ubuntu-small-latest`

**Comment by jorisvandenbossche** [comment]
@Mec-iS do those operations give you the same error?

**Comment by Mec-iS** [comment]
> @Mec-iS do those operations give you the same error?

`make_valid` applied in the same way works, but `orient` and `force_2d` raise:
```
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

**Comment by martinfleis** [comment]
shapely main built from source against  numpy 2.0 on apple silicon works fine for me.

**Comment by jorisvandenbossche** [comment]
@martinfleis but I assume that is with GEOS 3.12? (this issue only happens with the fallback implementation of `minimum_rotated_rectangle`, which is only used by default for GEOS < 3.12)

**Comment by martinfleis** [comment]
It is with GEOS 3.12 but calling those fallback functions directly (`_oriented_envelope_min_area_vectorized` and `_oriented_envelope_min_area`) also works fine.

**Comment by jorisvandenbossche** [comment]
And which version of MacOS do you have? NumPy 2.0 was installed from PyPI? (do you still have the output to see which wheel it downloaded?)

**Comment by martinfleis** [comment]
macOS 14.5 with numpy installed via conda

```
numpy                     2.0.0           py312hb544834_0    conda-forge
```

I can try to do the same with pure PyPI installation.

**Comment by jorisvandenbossche** [comment]
Yes, I suspect that with conda-forge it will not fail if this is specific about the numpy wheels being built with Accelerate (assuming conda forge doesn't do that?)

**Comment by martinfleis** [comment]
Okay, with numpy installed from PyPI I can reproduce this. Using `numpy-2.0.0-cp312-cp312-macosx_14_0_arm64.whl`.

**Comment by jorisvandenbossche** [comment]
@martinfleis one more question now you are at it, could you do a `%debug` when getting that error and print `new_coordinates` (that variable is used in the line that triggers the error, so you should end up there)

**Comment by martinfleis** [comment]
```py
In [6]: %debug
> /Users/martin/Git/shapely/shapely/coordinates.py(128)transform()
    126                 f"shape ({new_coordinates.shape})"
    127             )
--> 128         result = lib.set_coordinates(geometry_arr, new_coordinates)
    129     if result.ndim == 0 and not isinstance(geometry, np.ndarray):
    130         return result.item()

ipdb> new_coordinates
array([[-20.9740357 ,  13.99605905],
       [ 19.0282181 ,  13.99605905],
       [ 19.01338028, -16.02915345],
       [-20.98702857, -15.99077774],
       [-20.9740357 ,  13.99605905]])
```

**Comment by martinfleis** [comment]
> My assumption is that for some reason the start and end coordinate pair, which are identical for the input geometry, become slighty different

That is correct. Y coordinate with full precision:

```py
ipdb> new_coordinates[0][1]
np.float64(13.99605905374749)

ipdb> new_coordinates[-1][1]
np.float64(13.996059053747489)
```

**Comment by astrofrog** [comment]
@martinfleis could you find the difference between the first and last values?

**Comment by martinfleis** [comment]
@astrofrog that is in the post above, no? Explicit difference is

```py
ipdb> new_coordinates[0][1] - new_coordinates[-1][1]
np.float64(1.7763568394002505e-15)
```

**Comment by astrofrog** [comment]
Yes sorry that is what I meant, actual difference was too small to tell from your previous output. Thanks!

**Comment by jorisvandenbossche** [comment]
If we cannot rely on `np.matmul` to give exactly the same output for identical values in the input, then we should probably consider reverting https://github.com/shapely/shapely/pull/1418 (which introduced the usage of `np.matmul` in favor of manual multiplications)

cc @mwtoews

**Comment by mwtoews** [comment]
I don't fully understand why `np.matmul` would be giving poor results (did they compile it with `-ffast-math` or something?) Perhaps the previous implementation can be enabled for situations where `np.matmul` is sub-par. I'd prefer to keep the faster `np.matmul` for most end-users.

**Comment by jorisvandenbossche** [comment]
AFAIK `np.matmul` uses the BLAS implementation that numpy is built with (OpenBLAS, MKL, ..). For NumPy 2.0, and for MacOS 14, they switched to use Accelerate. Quoting the release notes:

> macOS Accelerate support and binary wheels for macOS >=14, with significant performance improvements for linear algebra operations on macOS, and wheels that are about 3 times smaller

While before also the macOS wheels shipped with a vendored libopenblas.

> Perhaps the previous implementation can be enabled for situations where `np.matmul` is sub-par. I'd prefer to keep the faster `np.matmul` for most end-users.

In theory we could detect that Accelerate is being used through `np.show_config()`, but then we should be sure that this is the reason (and that we have some guarantee it works for all other BLAS implementations)

**Comment by jorisvandenbossche** [comment]
I opened an upstream issue in NumPy to ask for feedback there on the expecations around `np.matmul` preserving equal values: https://github.com/numpy/numpy/issues/26791.

Could someone with MacOS 14 validate that my reproducible example actually reproduces the issue?

```python
coords = np.frombuffer(b'\xcb\x92\x87\x89\xfe\xde4@\x92\xce\xf0W\\L,\xc0\xb3\x03b\xffN!3\xc0\xe1y\x97b\x82\xb6+\xc0&ww\x99E\xe52\xc0\xfa\x8e\xbaY\xf7*0@\x04d\x85\xa0|\x1a5@\x14\x14h\xaap\xac/@\xcb\x92\x87\x89\xfe\xde4@\x92\xce\xf0W\\L,\xc0').reshape(5, 2)
A = np.frombuffer(b'7\xb3\xf1\xdd\xc7\xff\xef\xbf\xeb\xe4b\x9b\xf5\xf7}?\xeb\xe4b\x9b\xf5\xf7}\xbf7\xb3\xf1\xdd\xc7\xff\xef\xbf').reshape(2, 2)
result = np.matmul(A, coords.T).T
assert (result[0, :] == result[-1, :]).all()
```

**Comment by martinfleis** [comment]
Can confirm that the assertion fails when installed using the wheel from PyPI. But passes when installed from conda-forge, same as the original issue.

**Comment by jorisvandenbossche** [comment]
In https://github.com/numpy/numpy/issues/26791, the feedback seems to be that we cannot rely on `np.matmul` to give exact results (in this case the floats in the result are off by 1 ULP)

In theory we could also detect that there is this kind of small difference and correct the coord seq before creating a LinearRing / Polygon from it. However, if we start doing that we should check if the perf benefit of `np.matmul` is still worth it then.

**Comment by jorisvandenbossche** [comment]
@mwtoews would you be OK with reverting the use of `np.matmul` for now? I think we should try to resolve this in some way short term and do a 2.0.5 release.

I think the alternative is to look into `set_coordinates` to allow and correct a small difference in the last coordinate pair for a ring. We are creating the new coord seq here:

https://github.com/shapely/shapely/blob/f58b0d6f8b9da8e6765623e794d1885a8f13e5d3/src/coords.c#L176-L197

And we know when we are creating a LinearRing, so in that case we could check that the last values are the same as the first.

**Comment by mwtoews** [comment]
@jorisvandenbossche OK to revert for now, and explore alternatives.
