### ISSUE TITLE
Buffer(0) fails in LineString

### ISSUE THREAD

**Issue by MichaelRFox** [shapely/shapely#2069]
## Expected behavior and actual behavior.

I am using `buffer(0)` on geometries imported form an ESRI GIS website to correct for errors. This works fine for _Polygons_ and _MultiPolygons_ but not for _LineStrings_. When applying `buffer(0)` to a _LineString_ it returns `POLYGON EMPTY`. I would `expect buffer(0)` to return a _Polygon_ with the same bounds as the original _LineString_. 

## Steps to reproduce the problem.
``` python

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]) # the original LineString
out> LINESTRING (-77.4664 38.41264, -77.4664 38.41266)

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]).bounds
out> (-77.4664, 38.41264, -77.4664, 38.41266)

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]).buffer(0.0) # buffer(0) fails
out> POLYGON EMPTY

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]).buffer(0.0).bounds
out> (nan, nan, nan, nan)

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]).buffer(1e-7) # very small value for tolerance
out> POLYGON ((-77.46640009999999 38.41266, -77.46640009951847 38.41266000980172, -77.46640009807852 38.41266001950903, -77.46640009569403 38.41266002902847,...))

in> LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)]).buffer(1e-7).bounds
out> (-78.4664, 37.41264, -76.4664, 39.41266)
```

## Operating system

Windows 11 version 23H2

## Shapely version and provenance

Shapely v2.04 installed from PyPi using pip3
Python v 3.11

**Comment by theroggy** [comment]
Using `buffer(0)` to make features valid is an old trick... but since quite some time there is a proper function to make geometries valid. When the dedicated function is used the result seems OK:

```
import shapely
from shapely import LineString

print(shapely.make_valid(LineString([(-77.4664, 38.41264), (-77.4664, 38.41266)])))
# LINESTRING (-77.4664 38.41264, -77.4664 38.41266)
```

**Comment by mwtoews** [comment]
By design, buffer should only return polygons. E.g. take a geometry collection with three geometry dimensions and do `buffer(0)`:
```pycon
>>> import shapely
>>> gc = shapely.from_wkt("GEOMETRYCOLLECTION (POINT (1 1), LINESTRING (2 2, 3 3), POLYGON ((4 4, 5 5, 6 3, 4 4)))")
>>> gc.buffer(0).wkt
'POLYGON ((4 4, 5 5, 6 3, 4 4))'
```
only the polygon is returned. Non-polygons are discarded.

As mentioned, use [`shapely.make_valid`](https://shapely.readthedocs.io/en/latest/reference/shapely.make_valid.html) to make valid geometries.
