### ISSUE TITLE
Convert from a list of Points to a Polygon

### ISSUE THREAD

**Issue by ispmarin** [shapely/shapely#21]
Hi all,

I didn't find a mailing list of a forum, so I'm going to ask here. Is there a "canonical" form to convert from a list of Points to a Polygon? For example,

```
list_points = []
vertices = [Point(1,1), Point(2,2), Point(3,3)]
for i in xrange(len(vertices)):
    list_points.append(vertices[i])
polygon = Polygon(list_points)
```

This code doesn't work. I had to use convex_hull:

```
poly = MultiPoint(list_points).convex_hull
```

What is not exaclty what I'm looking for.

Thanks for the patience and the good work!

**Comment by kannes** [comment]
As I keep googling for this every now and then, here is how I prefer to do it:

>>> points = [Point(0,0), Point(2,2), Point(2,0)]
>>> coords = [(p.x, p.y) for p in points]
>>> poly = Polygon(coords)
>>> poly.area
2.0

timeit says things might be getting cached but @sgillies's approach seems consistently 2/3 faster (~65µs mine vs ~45µs his) so if you need super ultra hardcore performance for gazillions of points or polys, consider that.

**Comment by snorfalorpagus** [comment]
Ever so slightly faster again:
```
points = [Point(0,0), Point(2,2), Point(2,0)]
coords = [p.coords[:][0] for p in points]
poly = Polygon(coords)
poly.area
```
