### ISSUE TITLE
Error in plotting polygon with hole: no attribute 'exterior'

### ISSUE THREAD

**Issue by wei-lingfeng** [shapely/shapely#2100]
## Expected behavior and actual behavior.

Error in plotting polygon with hole. Error message is: `AttributeError: 'GeometryCollection' object has no attribute 'exterior'`

## Steps to reproduce the problem.

```
import numpy as np
from shapely.geometry import Point, Polygon
from shapely.plotting import plot_polygon

poly_with_hole = Polygon(np.array([
    [0, 0], [0, 10], [10, 10], [10, 0]
]), holes=[np.array([
    [7, 0], [5, 2], [3, 0]
])])
bug_poly = poly_with_hole.intersection(Point(5, 5).buffer(6))
plot_polygon(bug_poly)
```
`bug_poly` looks like this:
![image](https://github.com/user-attachments/assets/b8b4d272-04f3-4d00-bc39-5463fa8d2afb)
**Notice the line at the bottom**, I'm suspecting that's the root of the bug.
`bug_poly` has no attribute exterior, leading to a failure in `plot_polygon(bug_poly)`: `AttributeError: 'GeometryCollection' object has no attribute 'exterior'`

If I use the difference between the original polygon and the hole, it solves the problem and the line at the bottom disappears:
```
poly = Polygon(np.array([
    [0, 0], [0, 10], [10, 10], [10, 0]
]))
hole=Polygon(np.array([
    [7, 0], [5, 2], [3, 0]
]))
new_poly = poly.difference(hole).intersection(Point(5, 5).buffer(6))
plot_polygon(new_poly)
```
![image](https://github.com/user-attachments/assets/3b14407b-75cc-4aee-98c8-63ac7684e4d1)

## Operating system

MacOS 12.7

## Shapely version and provenance

2.0.5 installed from conda-forge using conda

**Comment by wei-lingfeng** [comment]
Thank you for your detailed response! So basically the `holes` wouldn't remove the line on the edge, resulting in a `GeometryCollection` rather than a `Polygon`, as it seems the intersection is still a `Polygon` when the holes are inside the geometry.

**Comment by theroggy** [comment]
Sorry, I didn't look properly at the initial polygon with hole: it is invalid... I edited my response above to explain that aspect as well.

**Comment by wei-lingfeng** [comment]
That clarifies the problem. I'll mark this issue as closed now. Thanks!
