### ISSUE TITLE
Shapely incompatible with NumPy 2.1.0

### ISSUE THREAD

**Issue by EwoutH** [shapely/shapely#2109]
Posting this here for visibility.

The fix is already merged, but a new release needs to be tagged.
- https://github.com/shapely/shapely/pull/2099

**Comment by jorisvandenbossche** [comment]
Shapely 2.0.6 is released that includes the fix (it's on pypi, conda-forge can still take a few hours)

**Comment by EwoutH** [comment]
Thanks!
