### ISSUE TITLE
Serialization of `POINT EMPTY` to GeoJSON should not raise

### ISSUE THREAD

**Issue by Oreilles** [shapely/shapely#2111]
This issue a copy of https://github.com/pygeos/pygeos/issues/464, I'm creating both as I don't know how the two projects are linked.

Serialization of empty points to GeoJSON raise `ValueError: GeoJSON output of empty points is currently unsupported`.

This tracks back to an [old issue](https://trac.osgeo.org/geos/ticket/1139) in GEOS that was closed 3 years ago by [this commit](https://github.com/libgeos/geos/commit/a51060c15ac2d8813e60de33bbc0ce0d07cc0d3b):

In shapely, these lines were responsible for checking is the geometry being serialized was an empty point, and raising an error if it was:
https://github.com/shapely/shapely/blob/775f7792ecd945fa30b3f98b46d99f996e275f00/src/ufuncs.c#L3562

This check should be removed, as GEOS can now perfectly handle empty points i/o for GeoJSON.

**Comment by jorisvandenbossche** [comment]
> This issue a copy of [pygeos/pygeos#464](https://github.com/pygeos/pygeos/issues/464), I'm creating both as I don't know how the two projects are linked.

We should more clearly archive the `pygeos` repo, but so all code of pygeos has been merged into shapely, and all development happens here.
