### ISSUE TITLE
FutureWarning: Series.__getitem__ treating keys as positions is deprecated.

### ISSUE THREAD

**Issue by fhg-isi** [shapely/shapely#2122]
I get a warning 

    FutureWarning: Series.__getitem__ treating keys as positions is deprecated.

when using 
```python
geometry = emitters_cluster["geometry"]   # array of Points
multi_point = MultiPoint(geometry)
```
caused by

```python
        for i in range(m):
            p = point.Point(points[i])
```
    
in [MultiPoint ](https://github.com/shapely/shapely/blob/cf4aebf74c73316e7e599c21068cfb9d156ca313/shapely/geometry/multipoint.py)   

## Shapely version and provenance

2.0.6 installed from PyPI using pip

**Comment by fhg-isi** [comment]
I suggest to replace points[i] with points.iloc[i]

**Comment by martinfleis** [comment]
> I suggest to replace points[i] with points.iloc[I]

That code is generic and does not rely on pandas, so `iloc` is not an option. But I believe that iterating directly over points may work.

E.g.

```py
        for pt in points:
            p = point.Point(pt)
            if p.is_empty:
                raise EmptyPartError("Can't create MultiPoint with empty component")
            subs.append(p)
```

**Comment by jorisvandenbossche** [comment]
> But I believe that iterating directly over points may work.

That should indeed work fine.
