### ISSUE TITLE
I've encountered a bug:Out of memory error

### ISSUE THREAD

**Issue by Zeizeikun** [shapely/shapely#2135]
![6c2f5e51f77039fbb42436b43645c50](https://github.com/user-attachments/assets/52f46891-5723-43d0-837f-0790e51e6d4c)
I'm experiencing this out of memory issue and have replaced the device with a different memory and still have the issue.

**Comment by theroggy** [comment]
It is pytorch that is running out of memory on your GPU...

Shapely doesn't use CUDA nor the GPU, so cannot be the problem...

**Comment by Zeizeikun** [comment]
> pytorch 充分利用了您的 GPU 内存……
> 
> Shapely不使用CUDA也不使用GPU，所以不可能是问题所在......

So which part of the process should be causing the whole problem? Below is my code：
explainer = shap.DeepExplainer(net2,x_train1)
shap_values = explainer.shap_values(x_test,check_additivity=False)

**Comment by martinfleis** [comment]
@Zeizeikun I think you are in the wrong repository. You probably wanted https://github.com/shap/shap.

**Comment by Zeizeikun** [comment]
> @Zeizeikun I think you are in the wrong repository. You probably wanted https://github.com/shap/shap.

Thanks for the answer. Can you be more specific?

**Comment by martinfleis** [comment]
@Zeizeikun I'm afraid I can't be more specific than that. Open issue in the repository linked above which is where shap lives. This is shapely which has nothing to do with Shapley.

**Comment by Zeizeikun** [comment]
> 'm afraid I can't be more specific than that. Open issue in the repository linked above which is where shap lives. This is shapely which has nothing to do with Shapley.

Thank you for your answer.
