### ISSUE TITLE
Documentation for `shapely.ops.transform` has reversed argument order

### ISSUE THREAD

**Issue by NBrown140** [shapely/shapely#2182]
## Expected behaviour and actual behaviour.

The documentation for `shapely.ops.transform` has the following function signature:
```
transform(geometry, transformation, include_z=False)
```
as can be seen here: https://shapely.readthedocs.io/en/stable/reference/shapely.transform.html#shapely.transform

According to the [source code](https://github.com/tomplex/Shapely/blob/master/shapely/ops.py#L241), it should be:
```
transform(transformation, geometry)
```

Notice the inversion of `transformation` and `geometry`, and the omission of `include_z=False`.

## Shapely version and provenance

2.0.6 installed from PyPI using poetry

**Comment by sgillies** [comment]
@NBrown140 It's a known issue, two different functions with the same name, that is tracked here: https://github.com/shapely/shapely/issues/1897.
