### ISSUE TITLE
`ops` module not available unless explicitly imported

### ISSUE THREAD

**Issue by samjameswilliams** [shapely/shapely#2190]
## Expected behavior and actual behavior.

I would expect that when I `import shapely` I would be able to access all the sub-modules but I get the behaviour in the next section.

It's relatively easy to work around but I find ruff will clean up the `from shapely import ops` line if I've also got a `import shapely` line unless I tell it not to.

## Steps to reproduce the problem.

```python
>>> import shapely
>>> shapely.ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'shapely' has no attribute 'ops'

>>> shapely.ops.split
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'shapely' has no attribute 'ops'

>>> from shapely import ops
>>> shapely.ops.split
<function SplitOp.split at 0x000001FBF1C3CF70>
```

## Operating system

Windows 10
Version 10.0.19045

## Shapely version and provenance

`2.0.6` installed using poetry 

Thank you for the great work on the library. Only recently started using it but it's been incredibly useful.

**Comment by mwtoews** [comment]
Not all shapely modules are loaded with `import shapely`, and the `ops` module is one of these. This is not a new behaviour.

**Comment by samjameswilliams** [comment]
> Not all shapely modules are loaded with `import shapely`, and the `ops` module is one of these. This is not a new behaviour.

Thank you for getting back to me. I'll bear this in mind as I make use of the library.
