### ISSUE TITLE
cascaded_union crashes: No Shapely geometry can be created from null value

### ISSUE THREAD

**Issue by blackmad** [shapely/shapely#47]
I started with it crashing on a union of 1506 shapes. I did a random.sample(200) on that list until I found a smaller crashing set. continuing to try to downsample that to find a minimum crashing set (all the pairs of 2 didn't crash).

I tried doing buffer(0) on all my polys, I tried exploding all my multipolys into individual loops, buffer(0) each loop, and checking is_valid, and cascaded_union was still crashing.

here's the input: http://f.cl.ly/items/343v1Q3M300f063K260V/200-fail.txt

from shapely.ops import cascaded_union
from shapely.wkt import dumps, loads
geoms = [loads(l) for l in open('200-fail.txt')]
cascaded_union(geoms)
# also fails

geoms = [loads(l).buffer(0) for l in open('200-fail.txt') if loads(l).buffer(0).is_valid]
cascaded_union(geoms)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shapely/ops.py", line 75, in cascaded_union
    return geom_factory(lgeos.methods['cascaded_union'](collection))
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/base.py", line 32, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

**Comment by eguaio** [comment]
Thank you all of you for all these helpful comments. Regards.

**Comment by kuanb** [comment]
Curious about this issue. Just observed it occurring with GEOS 3.6.2. According to the issue tracker results on GEOS that @sgillies linked to earlier in this issue, it appears 1/2 the related issue are closed and 1/2 are still open.

So it _seems_ like this is still an unresolved issue with GEOS. Is this a correct assumption?

**Comment by sgillies** [comment]
@kuanb yes, I believe you are right.

**Comment by michaelaye** [comment]
Is the test that was implemented by @sgillies in 0043a84 now failing since GEOS 3.6.2 or does that test not cover the remaining error scenario? I’m currently seeing this error with unary_union.

**Comment by bertsky** [comment]
For anyone who stumbles across this, too: You'll get `No Shapely geometry can be created from null value` (regardless of GEOS version all the way up to git master, both on Shapely 1.8 and 2.x) when using `unary_union` if any of the constituents (i.e. list member or MultiPolygon.geoms item) is **invalid**. 

(And invalidity may be due to self-crossing paths, which can be repaired by simplification, for example. And simplification is not always possible, you may need to change the init/end points of the exterior ring.)

**Comment by jorisvandenbossche** [comment]
> regardless of GEOS version all the way up to git master, both on Shapely 1.8 and 2.x

Are you sure this is also failing with Shapely 2.x? (at least I would find it surprising if the error is the same, that error message shouldn't exist anymore) 
If so, could you provide a reproducible example? (the original link with reproducible data in the top post doesn't work anymore)

**Comment by bertsky** [comment]
@jorisvandenbossche 
> Are you sure this is also failing with Shapely 2.x? (at least I would find it surprising if the error is the same, that error message shouldn't exist anymore)

sorry, that was imprecise. You are right: Shapely 2.0 does provide a different, more specific error message (just one I could not understand either):
```
>>> p = shapely.wkt.load(open('bad_polys.wkt', 'r'))
>>> len(p.geoms)
39
>>> shapely.ops.unary_union(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.7/site-packages/shapely/ops.py", line 135, in unary_union
    return shapely.union_all(geoms, axis=None)
  File "/lib/python3.7/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/lib/python3.7/site-packages/shapely/set_operations.py", line 426, in union_all
    return lib.unary_union(collections, **kwargs)
shapely.errors.GEOSException: TopologyException: side location conflict at 970.65822784810132 128.18987341772151. This can occur if the input geometry is invalid.
```

That's the exact message I get from the `geosop unaryUnion -a bad_polys.wkt` GEOS standalone tool.

> If so, could you provide a reproducible example? (the original link with reproducible data in the top post doesn't work anymore)

For the record: 
[here](https://github.com/shapely/shapely/files/10021129/bad_polys.zip) is the MultiPolygon example as wkt file.
And this is how it looks (the red subgeometry is the culprit – notice the self.intersection at the bottom): 
![textline_join_polygons_demo](https://user-images.githubusercontent.com/38561704/202169387-b3133d6a-9c56-46db-a91b-3d0d2518a658.png)

**Comment by jorisvandenbossche** [comment]
Thanks, that makes sense.

The last part of the new error message is important here: "This can occur if the input geometry is invalid."

So the union logic of GEOS expects the input to be valid geometries. You can solve this by first ensuring the input is valid (that's also why the `buffer(0)` trick might sometimes help), for example by using the `make_valid` functionality. Using your example (and using shapely 2.0, but I assume something similar will also work on 1.8):

```
>>> shapely.unary_union(p)
...
GEOSException: TopologyException: side location conflict at 970.65822784810132 128.18987341772151. This can occur if the input geometry is invalid.

>>> shapely.unary_union(shapely.make_valid(p))
<MULTIPOLYGON (((450 234, 265 225, 263 225, 190 236, 192 272, 192 296, 318 3...>
```

The result of unary_union then looks like:

![union](https://user-images.githubusercontent.com/1020496/202183805-c15036f9-73c4-4c58-9f25-4376c899ac9c.png)

**Comment by bertsky** [comment]
@jorisvandenbossche thanks for the explanation! Unfortunately, for me `validation.make_valid` is not always the right thing (I usually cannot have with MultiPolygon or GeometryCollection, so my make_valid uses a different strategy: re-link the ring, then buffer as long as necessary).

I was not aware of `shapely.plotting.plot_polygon` yet – fantastic!
