### ISSUE TITLE
Distance from empty collection is zero

### ISSUE THREAD

**Issue by jebob** [shapely/shapely#498]
### Expected behaviour:

The distance from an empty collection should be +inf.

### Actual behaviour:

The distance from an empty collection returns zero.

## Steps to reproduce the problem.
Run the following script:
```
from shapely.geometry import Point, LineString

empty_thing = LineString()
assert empty_thing.is_empty
print(empty_thing.distance(Point(1, 1)))  # Returns zero, should probably be +inf
```

## Operating system

Windows 10 64 bit

## Shapely version and provenance

Python 3.6
Shapely 1.6b4 installed from PyPI using pip

**Comment by snorfalorpagus** [comment]
This behavior is inherited from GEOS. If either geometry is empty the distance method returns 0. I think this is the relevant line of code:

https://github.com/OSGeo/geos/blob/5a730fc50dab2610a9e6c037b521accc66b7777b/src/operation/distance/DistanceOp.cpp#L146

**Comment by jebob** [comment]
Interesting. Given that they explicitly covered this case, is this WAD? Why should this be the case?

**Comment by mwtoews** [comment]
Similar to GEOS, JTS returns 0.0, so perhaps this behavior was drafted a long time ago.

PostGIS returns `null` for this scenario, since there are not any geometries to measure between. I'd suggest Shapely similarly return `None` if any of the inputs are empty.

**Comment by sgillies** [comment]
@mwtoews I'd like to see an exception raised instead of getting None: the intent is more clear.

Thanks for bringing this up, @jebob!

**Comment by bixb0012** [comment]
SQL Server spatial types return NULL, similar to PostGIS.  Esri's ArcPy generates an error.  It seems we have 0, NULL, or error depending on whom you ask.  I can see some merit behind arguments for any of them, so clear documentation is probably the most important part of addressing this issue.  After all, without a consensus among geospatial products, it is a matter of expectations and not correctness.

**Comment by sgillies** [comment]
I've changed my mind and am inclined to leave it as zero.

**Comment by jebob** [comment]
I wouldn't accept that the empty geometry is in every non-empty geometry, as the operation isn't analogous. 

1. Two identical strings are in each other, but two identical shapes may have different offsets and therefore aren't "in" each other.

2. Empty geometries should not be presumed to occupy every space, because then the intersection of an empty geometry and X geometry returns X.

3. Empty geometries must be further than any shape. dist(foo, X) <= dist(foo, union(X+Y)) by definition. If X is the empty set, then dist(foo, X) must return infinity for the identity to be valid for all foo, Y.

**Comment by sgillies** [comment]
@jebob thanks for being patient with me. I see the logic in +inf now.

Still, I think I'd prefer to treat it as undefined and raise an exception (in a feature release) for usability reasons.

**Comment by jebob** [comment]
Raising an exception seems a good compromise candidate as it is an unambiguous result, therefore preventing confusion from those who rely on GEOS/JTS returning zero.

**Comment by jorisvandenbossche** [comment]
With the latest GEOS version (3.10.3 or 3.11.0), the example in the top post now returns NaN instead of 0 (see also the discussion in https://github.com/shapely/shapely/issues/753).

This behaviour now seems consistent, and we are generally fine with NaN as result?

**Comment by jebob** [comment]
Returning NaN is fine with me.
