### ISSUE TITLE
Vectorize all GEOS functions

### ISSUE THREAD

**Issue by wmay** [shapely/shapely#501]
Vectorized functions would be a big help to GeoPandas and other projects trying to organize Shapely geometry in arrays, and there seems to be a consensus that it's best to implement the vectorized GEOS functions within Shapely. (See https://github.com/geopandas/geopandas/issues/430#issuecomment-291083993.)

After taking a look through the code I think we could implement this without too much trouble by adding a version of [topology.py](https://github.com/Toblerity/Shapely/blob/master/shapely/topology.py) that generates vectorized versions of the functions. At that point it would be easy to call the functions from the `vectorized` module, or add them to the `BaseGeometry` class, or call them in Geopandas (I think).

I just want to get some feedback to make sure I'm on the right track before I start this, and figure out where people should send the pull requests.

**Comment by wmay** [comment]
OK, I've got a rudimentary version of this working in [my vectorize branch](https://github.com/wmay/Shapely/tree/vectorize). The relevant code is in [vectorfuncs.pyx](https://github.com/wmay/Shapely/blob/vectorize/shapely/vectorized/vectorfuncs.pyx), which duplicates the functionality of topology.py, predicates.py, and impl.py.

Even though I'm sure this code could be improved, it's already cutting running times in half or more for a lot of operations compared to unvectorized code. (I think that's mostly due to avoiding Python `for` loops right now.) [Here](http://nbviewer.jupyter.org/gist/wmay/a2b003f92db99f7c5a6e7f57db8b9ff5)'s a jupyter notebook demonstrating the functions, as the code stands now.

The tasks left for making this work really well are:
* Create appropriate validation functions for arrays.
* Add support for array/array binary functions. (The binary functions right now only take an array for the second argument.)
* Improve my awkward Cython code.
* Add tests.
* Decide how to make the functions available to regular users.

And my wish list of nice features:
* Add support for multidimensional arrays and broadcasting.
* Add an option to pass pointers instead of shapely objects (because that can be much faster).
* Add an option to return an array of shapely objects instead of pointers, for convenience.
* Vectorize `shapely.geometry.base.geom_factory()`, since that seems to slow things down.

**Comment by sgillies** [comment]
@wmay this looks very promising! If I may suggest a few things: 

- test early and often, good tests help guide feature development and can be painful to write after the feature is finished (especially if they reveal that the feature isn't finished).
- generalize to N x M functions as soon as you can.
- If these could be done as ufuncs (https://docs.scipy.org/doc/numpy/reference/ufuncs.html) we'd get broadcasting and such, yes?

**Comment by wmay** [comment]
I was able to create ufuncs with `numpy.frompyfunc`, and it actually seemed to speed things up (just a bit). That simplified everything and suddenly I noticed I'm no longer using Cython since frompyfunc is doing all the work.

So now we're down to:
- Add tests.
- Create appropriate validation functions for arrays.
- Decide how to make the functions available to regular users.

And my wish list:
- Add an option to pass pointers instead of shapely objects (because that can be much faster).
- Add an option to toggle returning shapely objects / pointers for topology functions.

**Comment by wmay** [comment]
Got some basic tests set up.

This seems to be working except for some functions with non-standard behavior.

equals_exact
is_closed
buffer_with_style
topology_preserve_simplify

**Comment by wmay** [comment]
Got some basic tests set up.

So far this seems to be working except for some problem functions with extra arguments or non-standard behavior:

- buffer
- buffer_with_style
- equals_exact
- is_closed
- parallel_offset
- relate
- relate_pattern
- simplify
- topology_preserve_simplify

I also noticed there are error checking functions from geos.py that run at the end of each function. It might be worth trying to vectorize those too.

**Comment by sgillies** [comment]
Thanks for the update @wmay.

@snorfalorpagus I'm going to be out for the rest of the week, moving back to the US, unpacking and such. Could you help a bit with review and guidance if @wmay needs it?

**Comment by mrocklin** [comment]
@wmay have you considered using Cython directly?  I'm getting roughly 50-100x speedups by calling down to C in https://github.com/geopandas/geopandas/pull/467 .  By restricting yourself to `np.frompyfunc` you're probably leaving a great deal of performance on the table (though of course, any improvement is a good improvement).

**Comment by mrocklin** [comment]
To be explicit here, you would want to create a constructor for `Point` in Cython that consumed x, y, and z doubles and did all of the logic necessary, hopefully using only C calls (verifying perhaps with the `-a` mode in cython).  Then you would use this function from within the Python code if available.  

This would speed up shapely code, which would be good, but it would also provide an entry point for other libraries that wanted to use Shapely from within Cython.

**Comment by wmay** [comment]
My original code was in Cython, and when I switched to np.frompyfunc it actually sped up a little. I'm confused about why your code is running faster, and haven't had a chance to track down the culprit yet. I'm pretty sure np.frompyfunc uses C for loops so I'm not sure why there'd be a substantial difference, outside of the overhead of supporting array broadcasting.

Writing constructors in C sounds like a good idea but I think that's an issue for another branch. All of the changes here are independent of the Shapely constructor functions.

**Comment by mrocklin** [comment]
You're still calling Python functions underneath your for loops.  To write
fast Cython code you need to get away from any Python access, allocations,
etc..  It might be worth watching one of the Cython tutorials from SciPy.
Perhaps this one?  https://www.youtube.com/watch?v=gMvkiQ-gOW8

**Comment by wmay** [comment]
My functions are coming from geos.py, which I assumed was organizing a bunch of C functions. If not, it may be worth making changes at that point instead of farther downstream where this code is at.

Are the functions from geos.py slower because they're using ctypes instead of cython?

**Comment by mrocklin** [comment]
Yes.  They engage the Python interpreter.  Cython will compile your code
down to pure C so that the Python interpreter is no longer required.

**Comment by mrocklin** [comment]
OK, so if we were to do something a bit more sweeping here we might construct around an object that wrapped around a numpy ndarray that contained GEOSGeometry pointers.  This wrapper object would have methods that would call Cython code that would call GEOS C functions directly in a for loop.  This Cython function would return another numpy ndarray of pointers which would be wrapped up in yet another wrapper object.

If I or someone else were to start this would shapely maintainers be comfortable adding it into their library and maintaining it going forward?

**Comment by wmay** [comment]
I'm agnostic about what happens to the functions after we generate them.

Right now I'm just hoping to find a way to automate this process so we can take advantage of the existing structure organizing the GEOS functions. I'm hoping this ends up at a point where both the scalar and vectorized functions are managed by the dicts in `impl.py`.

The cython extern functions in `_geos.pxi` are giving me a hard time since I can't manipulate them in python. Somehow I want to be able to call them using a python string matching the function name. Maybe I could get them into some kind of C++ dict? I admit I'm getting out of my element in this kind of C/C++ development.

**Comment by mrocklin** [comment]
Yeah, I think the thing to do here is to have someone with some Cython
experience set up a few good examples that others can then come along and
extend.  This is how I got started.

**Comment by mrocklin** [comment]
Here is a notebook showing an approach that avoids Python objects altogether.  This is a very different approach but is also quite efficient.  https://gist.github.com/ef45e9466b703f817fbd221dfb6a7688

This is currently in my PR over at GeoPandas though it might be something that shapely folks want to adopt instead (if they want to go this route).

**Comment by jorisvandenbossche** [comment]
Regarding the initial topic of this issue on having 'vectorized' shapely operations, there are two enhancements we want to achieve I think: 1) convenience for the user and 2) better performance

1) Convenience for the user / user API: your current approach here is a nice way to generate vectorized functions (with not a lot of added code). Meaning that when a user has arrays of geometries, he/she no longer needs to do a list comprehension over the individual geometries, but can use a single call with the vectorized function. For example `intersects(array, geom)` instead of `[intersects(g, geom) for g in array]`. 
This is a nice improvement in usability.

2) Performance: so your proposed implementation already provides a nice API (a possible api, @mrocklin has an alternative proposal as well using a VectorizedGeometry class), but IMO doesn't give the desired speed improvement. An improvement of 2x / 3x is already nice, but I think we are rather looking for improvements in the order of 10x / 100x (and the small experiments of me and @mrocklin show that this is possible). 
To obtain this performance, I think (as far as my knowledge of it goes) it will be needed to use cython directly, as @mrocklin suggested (see the example notebooks in the original issue in geopandas (https://github.com/geopandas/geopandas/issues/430) and the PR of Matthew (https://github.com/geopandas/geopandas/issues/467))

**Comment by wmay** [comment]
It looks like I can use [C++ maps](https://gist.github.com/ctokheim/6c34dc1d672afca0676a#using-external-cc-modules) to replace the Python dicts I'm using now. And NumPy has [helpful advice for creating ufuncs in C](https://docs.scipy.org/doc/numpy/user/c-info.ufunc-tutorial.html). So I'll try to keep the current organization but with C/Cython instead of regular Python. It'll probably be the weekend before I get an example running though.

**Comment by danielsoutar** [comment]
Is this thread still active? I've been using Shapely myself for some work with lots of small objects and needing to compare them to a big LineString. The inability to use a vectorised .distance() and .within() inside my for-loop is severely hampering performance and something like this sounds perfect for that problem. I'd be happy to contribute too, assuming that's welcomed.

**Comment by wmay** [comment]
I put this on the backburner because the project I was working on that needed fast shapely loops wasn't a priority anymore.

As far as I know the concept of what I was trying to do here is sound, though it may require some awkward C++ code. And this is just one possible approach-- I can't say if it's better than other possible approaches.

I also saw earlier that geopandas was providing some vectorized shapely functions, so they may have solved your problem already.

**Comment by mrocklin** [comment]
Please excuse the self-advertisement, but we worked a bit on this.  It's
summarized here

http://matthewrocklin.com/blog/work/2017/09/21/accelerating-geopandas-1
https://github.com/geopandas/geopandas/issues/473

There is probably new information about this now.  I'm a bit out of date.

**Comment by caspervdw** [comment]
For the last couple of weeks, I did some work on this on the side. Basically, I wrapped most of the GEOS function in numpy ufuncs using this example from the [numpy docs](https://docs.scipy.org/doc/numpy/user/c-info.ufunc-tutorial.html). 

I started out using @jorisvandenbossche and @mrocklin approach (great blog posts, these really got me started on this) by putting raw pointers in ndarrays. The problem with this is the memory management: you really have to call Destroy precisely once per pointer, else you are left with a memory leak or SIGABRTs because you try to free the same memory block twice.

I ended up with a numpy structured dtype that has the shapely object along with the pointer to the GEOSGeometry. This makes sure GEOSGeometries are deallocated.

The code is now at https://github.com/caspervdw/pygeos, but I am willing to make a PR to shapely if someone wants to review/help with integrating it in shapely.

**Comment by snowman2** [comment]
This is fantastic and provides a great interface! I like the design and user interface :+1:

Out of curiosity, I did some comparisons based on: https://jorisvandenbossche.github.io/blog/2017/03/18/vectorized-shapely-cython/

Regular python time:
```python
In [3]:  from shapely.geometry import Point, Polygon 
In [4]: import numpy as np                                                     
In [5]: a = np.array([Point(i, i) for i in range(10000)], dtype=object)        
In [6]: def contains_py(array, poly): 
   ...:     return np.array([poly.contains(p) for p in array]) 
   ...:                                                                        
In [7]: poly = Polygon([(10,10), (10,100), (100,100), (100, 10)])              
In [8]: %timeit contains_py(a, poly)                                           
26.8 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
vectorized time:
```python
In [9]: a_x = np.array([x.x for x in a]) 
   ...: a_y = np.array([x.x for x in a])                                       
In [10]: import shapely.prepared                                               
In [11]: p2 = shapely.prepared.prep(poly)                                      
In [12]: import shapely.vectorized 
    ...:                                                                       
In [13]: %timeit shapely.vectorized.contains(p2, a_x, a_y)                     
1.83 ms ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
pygeos time:
```python
In [14]: from pygeos import contains                                           
In [16]: %timeit contains(poly, a)                                             
2.5 ms ± 27.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Although it does provide a 10x speedup, it is still a ways from the `209 µs` time in mentioned in the blog.

That being said I definitely think this is still a very worthwhile addition to shapely.

**Comment by jorisvandenbossche** [comment]
Interesting! 

> Although it does provide a 10x speedup from the regular Python time, it is still a ways from the 209 µs time in mentioned in the blog.

One reason for the difference might be that in the pygeos timeit you show, you pass the data as an object array, which pygeos first needs to convert to their internal structured dtype format. There seems to be a `pygeos.garr_from_shapely` to get that. Can you repeat the timing with doing first that conversion and passing that? 

Although for functions that return geometries, a conversion to shapely is done in the end, so those will still be slower (but that should not be the case for the contains example above which returns bools).

---

Regarding the memory management, the approach we take in GeoPandas is to only store the pointers, but when accessing single elements (or whenever you need an actual shapely object), we make a copy (GEOSGeom_clone_r) of it and wrap it in a Shapely object. This way shapely deals with destoying scalars, and we with properly destroying the array pointers.

@caspervdw do you know if it is possible to have a custom deallocation for numpy arrays? If you write your own dtype? (just wondering if the approach I described above would even be possible with numpy)

**Comment by snowman2** [comment]
I completely missed that :man_facepalming:. This is fantastic!
```python
In [7]: pga = pygeos.garr_from_shapely(a)                                       

In [8]: pygeos.contains(poly, pga)                                              
Out[8]: array([False, False, False, ..., False, False, False])

In [9]: %timeit pygeos.contains(poly, pga)                                      
212 µs ± 4.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by caspervdw** [comment]
@snowman2 Thanks for the benchmarks, I have done some myself as well and I got comparable results. The main overhead is indeed in the shapely geometry - pointer conversions. The Python overhead is especially pronounced when the actual GEOS function costs minimal effort (like in the `contains(point, rectangle)` example).

> Regarding the memory management, the approach we take in GeoPandas is to only store the pointers, but when accessing single elements (or whenever you need an actual shapely object), we make a copy (GEOSGeom_clone_r) of it and wrap it in a Shapely object. This way shapely deals with destoying scalars, and we with properly destroying the array pointers.

Thanks for this explanation, I missed the part that the GeoDataFrame destroys the pointers. Do you deal with broadcasting and masking as well?

> @caspervdw do you know if it is possible to have a custom deallocation for numpy arrays? If you write your own dtype? (just wondering if the approach I described above would even be possible with numpy)

I haven't found such a feature in numpy, but I haven't looked into it at great length. Subclassing the ndarray would probably be necessary.

Another approach would be writing the Geometry object as a Cython extension type. Something like https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#c-methods would be a start.

**Comment by jorisvandenbossche** [comment]
> Do you deal with broadcasting and masking as well?

Broadcasting not in the way you do with numpy (since in geopandas the array is limited to 1D for now, there no need). Masking or take we do, by keeping track of the parent "base" data which is responsible for deallocation.

> Another approach would be writing the Geometry object as a Cython extension type. 

That might be an interesting approach to have a more seamless integration between scalars and the array. But I suppose that would only be possible by writing your own array object, instead of integrating it into a numpy array as you did now?

In GeoPandas, we implemented a "duck array" (that holds a numpy array under the hood) and don't subclass ndarray.

**Comment by caspervdw** [comment]
> That might be an interesting approach to have a more seamless integration between scalars and the array. But I suppose that would only be possible by writing your own array object, instead of integrating it into a numpy array as you did now?

I am reluctant on subclassing (or ducktyping) ndarrays. I was hoping to solve this with an `object` type ndarray. If you can store a ctypes extension object in an ndarray, then you should be able to access its static attributes (e.g. `__geom__`) without the Python interpreter overhead, right?

**Comment by jorisvandenbossche** [comment]
> you should be able to access their static attributes (e.g. __geom__) without the Python interpreter overhead, right?

Not fully sure, but I think once you have object array, you will always interact with Python (since object dtype is basically a pointer to a python object), so defeating part of the gain of using cython or C/ufuncs.

**Comment by caspervdw** [comment]
> Not fully sure, but I think once you have object array, you will always interact with Python (since object dtype is basically a pointer to a python object), so defeating part of the gain of using cython or C/ufuncs.

In C, a python object is just a pointer (`PyObject *`) to a struct which includes some standard members, but may include additional ones. Cython static attributes end up there. Accessing these from C does not include the overhead. If I look at https://docs.python.org/3/extending/newtypes_tutorial.html, I could create an (immutable) extension type with `pointer` as additional attribute and with a custom `tp_dealloc` that calls the GEOSDestroy_r.

The advantage would be that we leverage python/numpy's reference counting and on the garbage collector to deallocate stuff.

Maybe a separate issue would be best to discuss this further.

**Comment by jorisvandenbossche** [comment]
@sgillies to what extent do you like to see this happen in shapely itself?

I think it would be nice to gather those vectorized GEOS interactions also in Shapely, as they are closely related to the scalar ones already available. But, it will of course be quite an expansion of the scope / APIs and possibly also technology (the current experiment of @caspervdw is in C)

**Comment by sgillies** [comment]
I'm coming to the opinion that this feature is too advanced for Shapely, which should focus itself on making easy things easy and making hard things possible. Making hard things easy is a hard task and vectorizing the GEOS functions is only one of things that would need to be done in order to make a GIS package comparable to PostGIS.

**Comment by jorisvandenbossche** [comment]
> vectorizing the GEOS functions is only one of things that would need to be done in order to make a GIS package comparable to PostGIS.

We already have GeoPandas for many of the functionalities that PostGIS provides (eg shapely should not bother itself with attributes), so I think Shapely could still focus on interfacing with GEOS.

Now, it's for sure that the ideas in this thread would be a considerable change in the technologies / amount of compiled code for the developers, so I certainly understand that is a potential reason to not to this. But I think from a user perspective, working with arrays of geometries and vectorized operations on them are not "hard things", they are IMO rather basic operations. 

Anyway, if it doesn't end up in Shapely, we should certainly think about how we can make Shapely and the "vectorized library" (be it pygeos or geopandas or something else) work well together, as it would be a pitty to have to duplicate a lot of what is in Shapely.

**Comment by caspervdw** [comment]
@sgillies I have been continuing the work on the vectorized functions in pygeos. To be able to push the involved loops to the C-level, I wrote a simple python extension type that stores the (pointer to) the GEOS geometry in a static attribute.

The deallocation is also done on the C-level. This ties the new Geometry object to the GC, preventing memory leaks and segfaults on a fundamental level.

With this new Geometry class, it seems that pygeos is going to be a reimplementation of the functionality in shapely. I think that is not a good thing. Maybe we can get in touch and think about ways to let the projects benefit from each other?

For example, I think this extension type would be an enhancement to shapely, and it would enable the vectorized functions in pygeos to seemlessly work on shapely objects.

**Comment by jorisvandenbossche** [comment]
In the meantime, Casper and I further worked on this in the PyGEOS package. I opened https://github.com/Toblerity/Shapely/issues/782 to specifically discuss potential integration of this into Shapely.

**Comment by jorisvandenbossche** [comment]
The vectorized implementations of PyGEOS are now moved into Shapely (https://github.com/shapely/shapely/issues/782, https://github.com/Toblerity/Shapely/issues/962), and available on the main branch. So I think this issue can be closed now.
