### ISSUE TITLE
Why is a type of MultiPoint not Sequence?

### ISSUE THREAD

**Issue by LostFan123** [shapely/shapely#693]
**Background:**
I implemented a general-purpose function to rotate sequences and wanted to use it to rotate a `MultiPoint`:
```python
from typing import Sequence, TypeVar

from shapely.geometry import MultiPoint, Point

T = TypeVar('T')


def rotate(sequence: Sequence[T],
           k: int = 1) -> Sequence[T]:
    """rotate([0 1 2 3], -1) -> [3 0 1 2]"""
    n = k % len(sequence)
    sequence_type = type(sequence)
    return sequence_type((*sequence[n:], *sequence[:n]))


if __name__ == '__main__':
    points = MultiPoint([Point(0, 0), Point(1, 0), Point(1, 1), Point(0, 1)])
    new_points = rotate(points, -1)
```
But I was surprised to see a warning on the last line:
```none
Expected type 'Sequence' (matched generic type 'Sequence[T]'), got 'MultiPoint' instead
```
![image](https://user-images.githubusercontent.com/20144534/55229591-c12d2000-521d-11e9-8c1d-79971346045c.png)

I expected the `MultiPoint` to be of a type `Sequence`, but apparently it's not.
The `MultiPoint` class defines all the methods of the `Sequence`: `__getitem__`, `__len__`, `__contains__`, `__iter__`, and `__reversed__`. The only methods it doesn't define are `.index` and `.count`. See [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes).

So, how about implementing those missing methods and making `MultiPoint` of a `Sequence` type?

Shapely version: 1.6.4.post1, installed from conda.

**Comment by sgillies** [comment]
Shapely doesn't use ABCs because it's from the olden days :) I'm not opposed to deriving from Sequence. There may be blockers, though, like the question of whether multipoint geometries are really ordered or not.

**Comment by jorisvandenbossche** [comment]
In the meantime, for Shapely 2.0, the MultiPoint class will no longer be sequence-like (so no getitem, len, iter, etc, see https://shapely.readthedocs.io/en/1.8.0/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable). 
Thus the question to derive from ABCs is no longer relevant, I think, so closing the issue.
