### ISSUE TITLE
parallel_offset returns MultiString with missing parts

### ISSUE THREAD

**Issue by xathis** [shapely/shapely#746]
Hi,

I'm noticing strange behavior in the parallel_offset method.

## Expected behavior and actual behavior.

parallel_offset should return a single LineString in the following example but returns a MultiLineString with a part missing.
Works correctly for some other distances or side='left' or when removing one of the points.

![incorrect](https://user-images.githubusercontent.com/175649/61411115-ea191400-a8e5-11e9-883e-c63fac1fa45c.png) incorrect behavior for distance=10
![correct](https://user-images.githubusercontent.com/175649/61411114-ea191400-a8e5-11e9-834f-5b96509fd950.png) correct behavior for distance=8

## Steps to reproduce the problem.
```python
import shapely.wkt
from matplotlib import pyplot as plt
from shapely.geometry import LineString

road = shapely.wkt.loads('LINESTRING ('
                         '424367.2267078362 4513099.023495375,'
                         ' 424370.9561004792 4513098.974304576,'
                         ' 424380.476033291 4513098.832676926,'
                         ' 424382.1039646821 4513098.816053259'
                         ')')
plt.plot(*road.coords.xy, marker='o')

line = road.parallel_offset(distance=10, side='right')

if isinstance(line, LineString):
    line = [line]

for l in line:
    plt.plot(*l.coords.xy, marker='o')

plt.gca().set_aspect('equal')
plt.show()
```

## Operating system

Mac OS X 10.14.5

## Shapely version and provenance

1.6.4.post1 installed from Conda

**Comment by sgillies** [comment]
Thanks for the report. The parallel offset method in GEOS has been buggy, that's for sure.

**Comment by LostFan123** [comment]
Also, sometimes it adds additional points to a `LineString`:
```python
from shapely import wkt

x = wkt.loads('LINESTRING (0.0000000000000000 0.0000000000000000, 0.2496337890625000 0.4992675781250000)')
x.parallel_offset(1e-10, side='left').wkt
# LINESTRING (8.94427190999916e-11 -4.47213595499958e-11, -8.94427190999916e-11 4.47213595499958e-11, 0.2496337889730573 0.4992675781697213, 0.2496337891519427 0.4992675780802787)
```

---
Shapely version: 1.6.4.post1, installed from conda.

**Comment by guyanf** [comment]
When I use postgis , sometimes there are problems.

**Comment by Jeremiah-England** [comment]
A link to the ticket in the geos bug tracker: https://trac.osgeo.org/geos/ticket/806

**Comment by jorisvandenbossche** [comment]
Using the latest released shapely and GEOS versions, this is now working correctly (the offset curve implementation has been refactored):

```
# using example from above
road = ...

line = road.parallel_offset(distance=10, side='right')

from shapely.plotting import plot_line
plot_line(road)
plot_line(line, color="C1")
```
![shapely_line_offset](https://user-images.githubusercontent.com/1020496/205444643-282c223a-deaf-464f-b092-b2ba807c589e.png)
