### ISSUE TITLE
Invalid memory access when reading WKT GEOMETRY COLLECTION containing POINT EMPTY

### ISSUE THREAD

**Issue by snorfalorpagus** [shapely/shapely#747]
## Expected behavior and actual behavior.

When trying to parse the following WKT string Shapely raises an OSError.

Discovered while investigating #742 .  

```
GEOMETRYCOLLECTION (POINT EMPTY, POINT (1 2))
```

## Steps to reproduce the problem.

Example failure:

```pycon
>>> from shapely import wkt
>>> g = wkt.loads("GEOMETRYCOLLECTION (POINT EMPTY, POINT (1 2))")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Snorfalorpagus\Desktop\Shapely\shapely\wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "C:\Users\Snorfalorpagus\Desktop\Shapely\shapely\geos.py", line 284, in read
    return geom_factory(geom)
  File "C:\Users\Snorfalorpagus\Desktop\Shapely\shapely\geometry\base.py", line 89, in geom_factory
    if lgeos.methods['has_z'](g):
OSError: exception: access violation reading 0x0000000000000010
```

Example creating it via another less direct approach, which suggests the structure is valid. Not sure where the "Z" is coming from.

```pycon
>>> point_empty = wkt.loads("POINT EMPTY")
>>> g = GeometryCollection([point_empty, Point(1, 2)])
>>> g.wkt
'GEOMETRYCOLLECTION Z (POINT EMPTY, POINT (1 2))'
```

## Operating system

Windows 10

## Shapely version and provenance

Shapely `master`

GEOS 3.7.2 installed via OSGeo4W

**Comment by sgillies** [comment]
This was fixed upstream between GEOS versions 3.7.2 and 3.10.2. I can't reproduce it with the latest.
