### ISSUE TITLE
Triangulation produces wrong results

### ISSUE THREAD

**Issue by GeorgySk** [shapely/shapely#764]
For some reason `shapely.ops.triangulate` doesn't like some geometries and loses their parts.

Simple example:
```python
from shapely.geometry import Polygon
from shapely.ops import triangulate

p = Polygon([(0, 0), (1, 0), (-1, 0.05)])
triangulate(p)
# []
```
And another one:
```python
p = Polygon([(0, 0), (0, 486), (1, 486), (1, 22), (2, 22), (2, 0)])
for x in triangulate(p):
    print(x.wkt)
# POLYGON ((0 486, 1 22, 1 486, 0 486))
# POLYGON ((1 486, 1 22, 2 22, 1 486))
# POLYGON ((0 0, 2 0, 1 22, 0 0))
# POLYGON ((1 22, 2 0, 2 22, 1 22))
```
There is a missing triangle here.
But if I replace `486` by, for example, `200`, then it will work fine:
```python
p = Polygon([(0, 0), (0, 200), (1, 200), (1, 22), (2, 22), (2, 0)])
for x in triangulate(p):
    print(x.wkt)
# POLYGON ((0 200, 0 0, 1 22, 0 200))
# POLYGON ((0 200, 1 22, 1 200, 0 200))
# POLYGON ((1 200, 1 22, 2 22, 1 200))
# POLYGON ((0 0, 2 0, 1 22, 0 0))
# POLYGON ((1 22, 2 0, 2 22, 1 22))
```

---

Shapely version: 1.6.4.post1, installed from conda.

**Comment by drnextgis** [comment]
In the first example we have just a simple triangle so getting an empty list is expected behavior, isn't it?
![image](https://user-images.githubusercontent.com/866124/63438177-2cc19500-c42c-11e9-9c18-2edaf934957e.png)

Second and third examples also give us a valid Delaunay triangulation:

![image](https://user-images.githubusercontent.com/866124/63438317-61355100-c42c-11e9-995b-123153201f85.png)

![image](https://user-images.githubusercontent.com/866124/63438413-8aee7800-c42c-11e9-9a20-095922887e91.png)

**Comment by LostFan123** [comment]
@drnextgis [`shapely.ops.triangulate`](https://shapely.readthedocs.io/en/latest/manual.html#shapely.ops.triangulate) returns Delaunay triangulation of vertices of a given geometry. And one of the [properties of Delaunay triangulation](https://en.wikipedia.org/wiki/Delaunay_triangulation#Properties) is that the union of all resulting triangles equals the convex hull of given points. So, when giving this function a triangle polygon, I think I'm right to expect the triangle itself as a result.

And even if it would be a default behavior to return empty lists then it is definitely not consistent:
```python
from shapely.geometry import Polygon
from shapely.ops import triangulate

# this is broken:
p = Polygon([(0, 0), (1, 0), (-1, 0.05)])
triangulate(p)
# []

# but this works fine:
p = Polygon([(0, 0), (1, 0), (-1, 0.1)])
triangulate(p)[0].wkt
# 'POLYGON ((-1 0.1, 0 0, 1 0, -1 0.1))'
```
---
Regarding the second and the third example. In your plot there is a missing line, hence missing triangle:
![missing_line](https://user-images.githubusercontent.com/20144534/63449838-238ef300-c441-11e9-8d39-974e37da8f49.png)

Taking in mind the aforementioned property with the convex hull, we can also perform a simple check of resulting areas:
```python
# there is a bug here:
p = Polygon([(0, 0), (0, 486), (1, 486), (1, 22), (2, 22), (2, 0)])
p.convex_hull.area, sum(triangle.area for triangle in triangulate(p))
# (740.0, 497.0)

# this works fine though:
p = Polygon([(0, 0), (0, 200), (1, 200), (1, 22), (2, 22), (2, 0)])
p.convex_hull.area, sum(triangle.area for triangle in triangulate(p))
# (311.0, 311.0)
```

**Comment by dbaston** [comment]
Confirmed for both `MULTIPOINT ((0 0), (1 0), (-1 0.05), (0 0))` and `MULTIPOINT ((0 0), (0 486), (1 486), (1 22), (2 22), (2 0))` in JTS master @dr-jts

**Comment by dr-jts** [comment]
This appears to be fixed in latest GEOS.  Can Shapely confirm?

**Comment by jorisvandenbossche** [comment]
Yes, I can confirm this is fixed with latest released GEOS and shapely. Thanks for the note!

First example no longer gives an empty list:
```
>>> p = Polygon([(0, 0), (1, 0), (-1, 0.05)])
>>> triangulate(p)
[<POLYGON ((-1 0.05, 0 0, 1 0, -1 0.05))>]
```

And the second example also now gives all expected triangles:

```
>>> p = Polygon([(0, 0), (0, 486), (1, 486), (1, 22), (2, 22), (2, 0)])
>>> for x in triangulate(p):
...     print(x.wkt) 
POLYGON ((0 486, 0 0, 1 22, 0 486))
POLYGON ((0 486, 1 22, 1 486, 0 486))
POLYGON ((1 486, 1 22, 2 22, 1 486))
POLYGON ((0 0, 2 0, 1 22, 0 0))
POLYGON ((1 22, 2 0, 2 22, 1 22))
```

and confirming the above result visually:

![delauney](https://github.com/shapely/shapely/assets/1020496/d1fb403e-57d2-4ffb-897e-fffa85d38aef)

**Comment by dr-jts** [comment]
Should be fixed by https://github.com/libgeos/geos/pull/953
