### ISSUE TITLE
shapely.ops.transform docs should state how it determines function arguments

### ISSUE THREAD

**Issue by brsr** [shapely/shapely#789]
`shapely.ops.transform(func, geom)` takes a function `func(x,y)` that can accept scalar values or iterables for `x` and `y`. It determines which kind of function by trying to call the function on an iterable. If the function throws `TypeError`, it assumes it only accepts scalars and calls it on scalars.

This isn't explained [in the current version of the docs](https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.transform). It makes sense once you know what it's doing, but it seems like magic if you don't. It would be worthwhile to add a line to the docs explaining that `transform` figures out if `func` can accept iterables by seeing whether it throws `TypeError` or not.

**Comment by tomplex** [comment]
Released in 1.7.1

**Comment by jorisvandenbossche** [comment]
As noted above, this issue was fixed already in 1.7.1, so closing.
