### ISSUE TITLE
Union of two valid shapely objects returns GEOMETRYCOLLECTION EMPTY

### ISSUE THREAD

**Issue by JulianAtkinson** [shapely/shapely#798]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

I have two valid shapely geometries which I know overlap however their union is returning a GEOMETRYCOLLECTION EMPTY.

## Steps to reproduce the problem.

b_shapely = POLYGON ((444.5285062772048 234.7431856585321, 443.7010148230925 229.7618860430344, 441.3445185334156 225.5389441384027, 437.8177726065854 222.7172645685536, 440.55589402994 224.9079812916575, 425.0778147047951 227.1393297122222, 423.6143694567681 229.7618860430344, 422.7868780026558 234.7431856585321, 423.6143694567681 239.7244852740298, 425.970865746445 243.9474271786614, 426.0465350576907 244.0079686959798, 439.7731406838622 245.2046554753943, 437.8177726065854 246.7691067485106, 441.3445185334156 243.9474271786614, 443.7010148230925 239.72448527403, 444.5285062772048 234.7431856585321))

a_shapely = POLYGON ((444.5285062772048 234.743185658532, 444.3196266317684 232.203741136358, 443.7010148230924 229.7618860430343, 442.6964437560629 227.5114595003891, 441.3445185334156 225.5389441384027, 439.6971928832886 223.9201426162366, 440.2470690638744 224.460497462327, 424.5304059230548 227.7097935177557, 423.6143694567681 229.7618860430343, 422.9957576480921 232.203741136358, 422.7868780026557 234.743185658532, 422.9957576480921 237.2826301807061, 423.6143694567681 239.7244852740297, 424.6189405237976 241.974911816675, 425.9708657464449 243.9474271786614, 425.7885129994419 243.6813669049581, 439.7572893627671 245.5071728168563, 439.6971928832886 245.5662287008275, 441.3445185334156 243.9474271786614, 442.6964437560629 241.974911816675, 443.7010148230924 239.7244852740299, 444.3196266317684 237.2826301807061, 444.5285062772048 234.743185658532))

union = a_shapely.union(b_shapely)

## Operating system

Linux

**Comment by mwtoews** [comment]
Can you find your GEOS version? `from shapely import geos; print(geos.geos_version_string)`. And did you use the `.isvalid` property to determine that they are valid?

Testing with GEOS "3.7.2-CAPI-1.11.2 b55d2125", neither of these geometries are valid, and the second a_shapely geometry is simple, while the first b_shapely geometry is not simple. When I try union, I see an expected error:
> TopologyException: Input geom 0 is invalid: Self-intersection at or near point 440.24706906387439 224.460497462327 at 440.24706906387439 224.460497462327

JTS 1.15 has a similar analysis, except they are both non-simple.

**Comment by jorisvandenbossche** [comment]
With the latest shapely and GEOS versions, I also get what @mwtoews already reported above: both geometries are invalid, and when trying to union them, you get an error about that. 

Therefore closing this issue.
