### ISSUE TITLE
TypeError: object of type 'LineString' has no len()

### ISSUE THREAD

**Issue by ender-wieczorek** [shapely/shapely#823]
## Expected behavior and actual behavior.

Expected behavior: no error.
Behavior on 1.6a2: no error.
Behavior on 1.6.b1: `TypeError: object of type 'LineString' has no len()`

## Steps to reproduce the problem.

```
from shapely.geometry import LineString, asMultiPoint

line = LineString([(0.0, 0.0), (1.0, 1.0)])
for point in asMultiPoint(line):
    pass
```

A work around is to pass `line.coords` to `asMultiPoint`.

## Operating system

Ubuntu 18.04

## Shapely version and provenance

`>=1.6b1` from pip

**Comment by sgillies** [comment]
Neither `MultiPoint()` nor `asMultiPoint()` advertise that a LineString is a valid input, so this is not a major bug. However, the exception could be more clear. Also note that version 1.6 is no longer supported now that 1.7.0 has been released.

**Comment by kylebarron** [comment]
I just got bit by a similar bug. By using `asShape` instead of `shape` for loading from GeoJSON, every time I tried to reproject I got this error.
