### ISSUE TITLE
DOC: shapely pyproj examples missing always_xy=True

### ISSUE THREAD

**Issue by BrendanMD** [shapely/shapely#878]
Given that proj may now flip axes and that Shapely expects x-y order, I suggest adding always_xy=True to the pyproj examples with a note in the text. This bit me on the ass while trying to reproject to gnomonic.
`<< project = pyproj.Transformer.from_proj(proj_in, proj_out).transform`
`>> project = pyproj.Transformer.from_proj(proj_in, proj_out, always_xy=True).transform`

**Comment by tomplex** [comment]
Released in 1.7.1.

**Comment by jorisvandenbossche** [comment]
This was fixed by https://github.com/shapely/shapely/pull/885
