### ISSUE TITLE
Deprecate the shapely.geos module

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#928]
To do item for Shapely 1.8: find a way to raise deprecation warnings for functionality in the `shapely.geos` module (as this will be completely removed in Shapely 2.0). 
Although it's not really documented / recommended, it will be used in practice I think.

Eg the WKTReader / WKTWriter (eg https://stackoverflow.com/a/29548439/653364), the `lgeos` object to directly access GEOS functions (eg https://gis.stackexchange.com/a/226912/9828, we also did this in geopandas https://github.com/geopandas/geopandas/blob/8be1fd8b2a0b7691031d59b3a54275304db8aaa9/geopandas/io/sql.py#L58)

**Comment by jorisvandenbossche** [comment]
Although the difficulty for users might be that the alternative will not yet be available in Shapely 1.8, but only in 2.0, so they can't really yet "solve" the warning.

**Comment by sgillies** [comment]
There's nothing to be done for users who are tapping into the lgeos object, it's going to be removed.

There are users of the format readers/writers, so let's try to move them to shapely.wkt?

**Comment by mwtoews** [comment]
Agree to move wkt and wbk reader/writers classes/defaults to wkt and wkb modules.

Another consideration is to add a wrapper module `shapely.geos` in Shapely 2.0 to expose a few properties/classes, depending on how easy/difficult it is to show deprecation warnings.

**Comment by jorisvandenbossche** [comment]
> There's nothing to be done for users who are tapping into the lgeos object, it's going to be removed.

Yes, I know there won't be anything equivalent in Shapely 2.0, I don't care about that (in the end, the reasons people needed it now should be covered by new functionality). 
But the main reason I opened the ticket was to see if we can / want to warn in advance about this fact that it will disappear.

> There are users of the format readers/writers, so let's try to move them to shapely.wkt?

For the WKT/WKB reading and writing, all the functionality for which you now required to use the `shapely.geos` readers and writers directly is already covered by PyGEOS functionality (eg all options from GEOS are exposed, https://pygeos.readthedocs.io/en/latest/io.html#pygeos.io.to_wkb). So I think that can be integrated in the shapely.wkt/wkb functions, without actually adding those reader/writer classes to those modules (all functionality can be exposed in the functions I think).

Another example usage I linked too was `shapely.geos.lgeos.GEOSGetSRID`, but also that is already covered in PyGEOS with a ufunc (https://pygeos.readthedocs.io/en/latest/geometry.html#pygeos.geometry.get_srid)

> Another consideration is to add a wrapper module shapely.geos in Shapely 2.0 to expose a few properties/classes

Are you thinking specifically for the WKT/WKB readers/writers?

We could also make sure that all options for which users now might have used those classes are fully exposed and documented in shapely.wkt/wkb *for Shapely 1.8*, so users can actually already migrate away from using shapely.geos directly for this use case before it gets removed.

**Comment by mwtoews** [comment]
> Are you thinking specifically for the WKT/WKB readers/writers?
> 
> We could also make sure that all options for which users now might have used those classes are fully exposed and documented in shapely.wkt/wkb _for Shapely 1.8_, so users can actually already migrate away from using shapely.geos directly for this use case before it gets removed.

Yes. For what it's worth, decisions where these modules should be put were made back in #63, so they were put in `shapyley.geos`, rather than `shapely.wkt` and `shapely.wkb`.
